// apps/web/src/app/bookings/[id]/page.tsx
"use client";

import { useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import {
  MapPin,
  Clock,
  CalendarDays,
  Timer,
  Users,
  CreditCard,
  Share2,
  XCircle,
  CheckCircle2,
  ShieldCheck,
  ShieldX,
  Ticket,
  ArrowLeft,
  Copy,
} from "lucide-react";
import { enhancedBookings, type Participant } from "@/mock/enhanced-bookings";
import { mockVenues } from "@/mock/venues";
import { mockCourts } from "@/mock/courts";
import { padelImg } from "@/lib/images";

export default function BookingDetailPage() {
  const params = useParams();
  const bookingId = params.id as string;
  const booking = enhancedBookings.find((b) => b.id === bookingId);
  const [toast, setToast] = useState<string | null>(null);

  if (!booking) {
    return (
      <div className="min-h-screen pt-28">
        <div className="container py-16 text-center">
          <p className="text-sm text-[#F7F7F7]/30">Booking not found.</p>
          <Link href="/bookings" className="mt-4 inline-flex items-center gap-2 text-sm text-[#E6FA50] hover:underline">
            <ArrowLeft className="h-3.5 w-3.5" /> Back to bookings
          </Link>
        </div>
      </div>
    );
  }

  const venue = mockVenues.find((v) => v.id === booking.venueId);
  const court = mockCourts.find((c) => c.id === booking.courtId);

  function showToast(msg: string) {
    setToast(msg);
    setTimeout(() => setToast(null), 2500);
  }

  function handleShareInvite() {
    const url = `${window.location.origin}/booking/${bookingId}/invite`;
    navigator.clipboard.writeText(url).then(() => {
      showToast("Invite link copied to clipboard");
    }).catch(() => {
      showToast("Coming soon in backend integration.");
    });
  }

  function handleCancel() {
    showToast("Coming soon in backend integration.");
  }

  return (
    <div className="min-h-screen pt-28 pb-16">
      {/* Back nav */}
      <section className="container pb-6">
        <Link href="/bookings" className="inline-flex items-center gap-2 text-sm text-[#F7F7F7]/30 transition-colors hover:text-[#F7F7F7]/60">
          <ArrowLeft className="h-3.5 w-3.5" /> Back to bookings
        </Link>
      </section>

      {/* Header */}
      <section className="container pb-8">
        <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <div className="flex items-center gap-3 mb-2">
              <StatusBadge status={booking.status} />
              <PaymentBadge status={booking.payment.status} />
            </div>
            <h1 className="heading-1 text-2xl text-[#F7F7F7] md:text-3xl">
              {venue?.name ?? "Unknown Venue"}
            </h1>
            <p className="mt-1 flex items-center gap-2 text-sm text-[#F7F7F7]/40">
              <MapPin className="h-3.5 w-3.5" />
              {venue?.location} · {venue?.city}
            </p>
          </div>
          <div className="hidden sm:block h-20 w-32 overflow-hidden rounded-xl">
            <img src={padelImg(400)} alt={venue?.name ?? ""} className="h-full w-full object-cover" />
          </div>
        </div>
      </section>

      <section className="container">
        <div className="grid grid-cols-1 gap-6 lg:grid-cols-3">
          {/* Left column — main info */}
          <div className="lg:col-span-2 space-y-6">
            {/* Booking Information */}
            <div className="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6">
              <p className="section-label mb-4">Booking Information</p>
              <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">
                <InfoCard icon={Ticket} label="Booking ID" value={booking.id.toUpperCase()} />
                <InfoCard icon={MapPin} label="Court" value={`${court?.name ?? "—"} · ${court?.type ?? ""}`} />
                <InfoCard icon={CalendarDays} label="Date" value={booking.bookingDate} />
                <InfoCard icon={Clock} label="Time" value={`${booking.startTime} – ${booking.endTime}`} />
                <InfoCard icon={Timer} label="Duration" value={`${booking.duration} min`} />
                <InfoCard icon={CalendarDays} label="Booked On" value={new Date(booking.createdAt).toLocaleDateString()} />
              </div>
            </div>

            {/* Participants */}
            <div className="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6">
              <div className="flex items-center justify-between mb-4">
                <p className="section-label">Participants</p>
                <span className="caption text-[#F7F7F7]/25">
                  {booking.participants.filter((p) => p.rsvp === "accepted").length}/{booking.participants.length} confirmed
                </span>
              </div>
              <div className="space-y-2">
                {booking.participants.map((participant) => (
                  <ParticipantRow key={participant.id} participant={participant} />
                ))}
              </div>
              {booking.status === "confirmed" && (
                <button
                  onClick={handleShareInvite}
                  className="mt-4 w-full flex items-center justify-center gap-2 rounded-xl border border-white/[0.06] py-2.5 text-xs font-medium text-[#F7F7F7]/40 transition-colors hover:border-white/[0.12] hover:text-[#F7F7F7]/70"
                >
                  <Users className="h-3.5 w-3.5" /> Invite More Friends
                </button>
              )}
            </div>

            {/* Refund Policy */}
            <div className="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6">
              <p className="section-label mb-4">Refund Policy</p>
              <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
                <div className="flex items-center gap-3 rounded-xl bg-white/[0.02] p-4">
                  <ShieldCheck className="h-5 w-5 shrink-0 text-[#E6FA50]" />
                  <div>
                    <p className="text-sm font-medium text-[#F7F7F7]/70">Full refund before H-1</p>
                    <p className="caption text-[#F7F7F7]/25">Cancel 24+ hours before booking date</p>
                  </div>
                </div>
                <div className="flex items-center gap-3 rounded-xl bg-white/[0.02] p-4">
                  <ShieldX className="h-5 w-5 shrink-0 text-red-400" />
                  <div>
                    <p className="text-sm font-medium text-[#F7F7F7]/70">Non-refundable after H-1</p>
                    <p className="caption text-[#F7F7F7]/25">Less than 24 hours before booking</p>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Right column — payment & actions */}
          <div className="space-y-6">
            {/* Payment */}
            <div id="payment" className="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6">
              <p className="section-label mb-4">Payment</p>
              <div className="space-y-3 mb-4">
                <PaymentRow label="Court fee" value={`Rp ${(booking.totalAmount / 1000).toFixed(0)}K`} />
                {booking.voucherDiscount > 0 && (
                  <PaymentRow
                    label={`Voucher (${booking.voucherCode})`}
                    value={`-Rp ${(booking.voucherDiscount / 1000).toFixed(0)}K`}
                    highlight
                  />
                )}
                <PaymentRow label="Platform fee" value={`Rp ${(booking.platformFee / 1000).toFixed(0)}K`} />
                <div className="border-t border-white/[0.04] pt-3">
                  <PaymentRow label="Total" value={`Rp ${(booking.finalAmount / 1000).toFixed(0)}K`} bold />
                </div>
              </div>

              <div className="space-y-2 rounded-xl bg-white/[0.02] p-3">
                <div className="flex items-center justify-between">
                  <span className="caption text-[#F7F7F7]/30">Method</span>
                  <span className="text-xs font-medium text-[#F7F7F7]/60">{booking.payment.method}</span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="caption text-[#F7F7F7]/30">Provider</span>
                  <span className="text-xs font-medium text-[#F7F7F7]/60 uppercase">{booking.payment.provider}</span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="caption text-[#F7F7F7]/30">Status</span>
                  <PaymentBadge status={booking.payment.status} />
                </div>
                {booking.payment.paidAt && (
                  <div className="flex items-center justify-between">
                    <span className="caption text-[#F7F7F7]/30">Paid at</span>
                    <span className="caption text-[#F7F7F7]/40">{new Date(booking.payment.paidAt).toLocaleString()}</span>
                  </div>
                )}
              </div>
            </div>

            {/* Actions */}
            <div className="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6">
              <p className="section-label mb-4">Actions</p>
              <div className="space-y-2">
                <button
                  onClick={handleShareInvite}
                  className="w-full flex items-center gap-3 rounded-xl bg-white/[0.02] px-4 py-3 text-sm text-[#F7F7F7]/60 transition-colors hover:bg-white/[0.04] hover:text-[#F7F7F7]"
                >
                  <Share2 className="h-4 w-4 text-[#50C8C8]" />
                  Share invite link
                  <Copy className="ml-auto h-3.5 w-3.5 text-[#F7F7F7]/20" />
                </button>
                <Link
                  href={`/booking/${booking.id}/payment`}
                  className="w-full flex items-center gap-3 rounded-xl bg-white/[0.02] px-4 py-3 text-sm text-[#F7F7F7]/60 transition-colors hover:bg-white/[0.04] hover:text-[#F7F7F7]"
                >
                  <CreditCard className="h-4 w-4 text-[#50C8C8]" />
                  View payment receipt
                </Link>
                {booking.status === "confirmed" && (
                  <button
                    onClick={handleCancel}
                    className="w-full flex items-center gap-3 rounded-xl bg-red-500/5 px-4 py-3 text-sm text-red-400/70 transition-colors hover:bg-red-500/10 hover:text-red-400"
                  >
                    <XCircle className="h-4 w-4" />
                    Cancel booking
                  </button>
                )}
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Toast */}
      {toast && (
        <div className="fixed bottom-6 left-1/2 z-50 -translate-x-1/2 rounded-xl border border-white/[0.06] bg-[#0C1B26] px-5 py-3 shadow-2xl">
          <p className="caption text-[#F7F7F7]/70">{toast}</p>
        </div>
      )}
    </div>
  );
}

function InfoCard({
  icon: Icon,
  label,
  value,
}: {
  icon: React.ComponentType<{ className?: string }>;
  label: string;
  value: string;
}) {
  return (
    <div className="rounded-xl bg-white/[0.02] p-3">
      <Icon className="h-3.5 w-3.5 text-[#50C8C8]" />
      <p className="heading-3 mt-1.5 text-[13px] text-[#F7F7F7] break-all">{value}</p>
      <p className="caption mt-0.5 text-[#F7F7F7]/20">{label}</p>
    </div>
  );
}

function ParticipantRow({ participant }: { participant: Participant }) {
  const rsvpStyles = {
    accepted: { icon: CheckCircle2, color: "text-[#E6FA50]", label: "Accepted" },
    pending: { icon: Clock, color: "text-amber-400", label: "Pending" },
    declined: { icon: XCircle, color: "text-red-400", label: "Declined" },
  };
  const { icon: RsvpIcon, color, label } = rsvpStyles[participant.rsvp];

  return (
    <div className="flex items-center gap-3 rounded-xl bg-white/[0.02] p-3">
      <img
        src={participant.avatarUrl}
        alt={participant.name}
        className="h-8 w-8 rounded-full object-cover"
      />
      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-2">
          <p className="text-sm text-[#F7F7F7]/70 truncate">{participant.name}</p>
          {participant.isHost && (
            <span className="rounded-full bg-[#E6FA50]/10 px-2 py-0.5 text-[9px] font-medium uppercase text-[#E6FA50]">Host</span>
          )}
        </div>
      </div>
      <div className="flex items-center gap-1.5">
        <RsvpIcon className={`h-3.5 w-3.5 ${color}`} />
        <span className={`caption ${color}`}>{label}</span>
      </div>
    </div>
  );
}

function PaymentRow({ label, value, highlight, bold }: { label: string; value: string; highlight?: boolean; bold?: boolean }) {
  return (
    <div className="flex items-center justify-between">
      <span className={`text-sm ${bold ? "font-medium text-[#F7F7F7]/70" : "text-[#F7F7F7]/40"}`}>{label}</span>
      <span className={`text-sm ${highlight ? "text-[#E6FA50]" : bold ? "font-semibold text-[#F7F7F7]" : "text-[#F7F7F7]/60"}`}>{value}</span>
    </div>
  );
}

function StatusBadge({ status }: { status: string }) {
  const styles: Record<string, string> = {
    confirmed: "bg-[#E6FA50]/10 text-[#E6FA50]",
    pending: "bg-[#50C8C8]/10 text-[#50C8C8]",
    completed: "bg-white/[0.04] text-[#F7F7F7]/30",
    cancelled: "bg-red-500/10 text-red-400/70",
  };
  return (
    <span className={`rounded-full px-2.5 py-0.5 text-[10px] font-medium uppercase tracking-[0.1em] ${styles[status] ?? "bg-white/5 text-[#F7F7F7]/30"}`}>
      {status}
    </span>
  );
}

function PaymentBadge({ status }: { status: string }) {
  const styles: Record<string, string> = {
    paid: "bg-[#E6FA50]/10 text-[#E6FA50]",
    pending: "bg-amber-500/10 text-amber-400",
    failed: "bg-red-500/10 text-red-400",
    refunded: "bg-[#50C8C8]/10 text-[#50C8C8]",
  };
  return (
    <span className={`rounded-full px-2.5 py-0.5 text-[10px] font-medium uppercase tracking-[0.1em] ${styles[status] ?? ""}`}>
      {status}
    </span>
  );
}

// apps/web/src/routes/bookings/[id]/+page.svelte
<script lang="ts">
import {
  AlertCircle,
  ArrowLeft,
  CalendarDays,
  Clock,
  Copy,
  CreditCard,
  Loader2,
  MapPin,
  Share2,
  ShieldCheck,
  ShieldX,
  Star,
  Ticket,
  Timer,
  XCircle,
} from "lucide-svelte";
import { onMount } from "svelte";
import { page } from "$app/state";
import { api } from "$lib/api/client";
import { authStore } from "$lib/auth/store.svelte";
import { formatBookingDate, formatBookingTimeRange } from "$lib/format";
import { padelImg } from "$lib/images";

const bookingId = $derived((page.params.id as string) || "");

let booking = $state<any | null>(null);
let isLoading = $state(true);
let reviewRating = $state(0);
let reviewComment = $state("");
let isSubmittingReview = $state(false);
let reviewError = $state<string | null>(null);
let reviewSubmitted = $state(false);
let toast = $state<string | null>(null);

function showToast(msg: string) {
  toast = msg;
  setTimeout(() => (toast = null), 2500);
}

function formatIDR(amount: number): string {
  if (!amount) return "Rp 0";
  return `Rp ${(amount / 1000).toFixed(0)}K`;
}

async function loadBooking() {
  if (!authStore.firebaseUser) return;
  isLoading = true;
  try {
    const token = await authStore.firebaseUser.getIdToken();
    if (!token) return;

    const res = await api.bookings({ id: bookingId }).get({
      headers: { authorization: `Bearer ${token}` },
    });
    if (res.data) {
      booking = res.data;
    }
  } catch (e) {
    console.warn("Booking detail fetch error:", e);
  } finally {
    isLoading = false;
  }
}

async function submitReview() {
  if (isSubmittingReview || reviewRating < 1) return;
  isSubmittingReview = true;
  reviewError = null;
  try {
    const token = await authStore.firebaseUser?.getIdToken();
    if (!token) return;

    const res = await api.reviews.post(
      {
        bookingId: bookingId,
        rating: reviewRating,
        comment: reviewComment.trim() || undefined,
      },
      { headers: { authorization: `Bearer ${token}` } },
    );
    if (res.data) {
      reviewSubmitted = true;
      showToast("Thanks for your review!");
    }
  } catch (err: any) {
    reviewError = err.message || "Failed to submit review";
  } finally {
    isSubmittingReview = false;
  }
}

function handleShareInvite() {
  const url = `${window.location.origin}/booking/${bookingId}/invite`;
  navigator.clipboard
    .writeText(url)
    .then(() => {
      showToast("Invite link copied to clipboard");
    })
    .catch(() => {
      showToast(`Share this invite link: ${url}`);
    });
}

$effect(() => {
  if (authStore.isInitialized && authStore.user && authStore.firebaseUser) {
    loadBooking();
  }
});

function getStatusStyle(status: string) {
  switch (status?.toLowerCase()) {
    case "confirmed":
      return "bg-[#E6FA50]/10 text-[#E6FA50]";
    case "pending":
      return "bg-[#50C8C8]/10 text-[#50C8C8]";
    case "completed":
      return "bg-white/[0.04] text-[#F7F7F7]/25";
    case "cancelled":
      return "bg-red-500/10 text-red-400/70";
    default:
      return "bg-white/5 text-[#F7F7F7]/25";
  }
}

function getPaymentStyle(status: string) {
  switch (status?.toLowerCase()) {
    case "paid":
      return "bg-[#E6FA50]/10 text-[#E6FA50]";
    case "pending":
      return "bg-amber-500/10 text-amber-400";
    case "failed":
      return "bg-red-500/10 text-red-400";
    case "refunded":
      return "bg-[#50C8C8]/10 text-[#50C8C8]";
    default:
      return "";
  }
}
</script>

<svelte:head>
  <title>Booking Summary #{bookingId.slice(0, 8)} - Padelhive</title>
</svelte:head>

<div class="min-h-screen pt-28 pb-16 bg-[#06121A]">
  <!-- Back nav -->
  <section class="container pb-6">
    <a
      href="/bookings"
      class="group inline-flex items-center gap-3 text-xs font-medium text-[#F7F7F7]/60 transition-colors hover:text-[#F7F7F7]"
    >
      <div class="flex h-7 w-7 items-center justify-center rounded-lg border border-white/[0.08] bg-white/[0.03] text-[#F7F7F7]/40 transition-all duration-200 group-hover:border-[#E6FA50]/40 group-hover:bg-[#E6FA50]/10 group-hover:text-[#E6FA50]">
        <ArrowLeft class="h-3.5 w-3.5" />
      </div>
      <span>Back to bookings</span>
    </a>
  </section>

  {#if isLoading || !authStore.isInitialized || authStore.isLoading}
    <div class="container pb-8">
      <div class="h-8 w-48 animate-pulse rounded-md bg-white/[0.04]"></div>
      <div class="mt-4 h-4 w-32 animate-pulse rounded-md bg-white/[0.04]"></div>
    </div>
    <div class="container">
      <div class="h-64 animate-pulse rounded-2xl bg-white/[0.02]"></div>
    </div>
  {:else if !booking}
    <div class="container my-8">
      <div class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-12 md:p-16 text-center max-w-xl mx-auto">
        <div class="flex h-12 w-12 items-center justify-center rounded-2xl bg-white/[0.04] text-[#E6FA50] mx-auto mb-4">
          <Ticket class="h-6 w-6" />
        </div>
        <h2 class="heading-2 text-xl font-bold text-[#F7F7F7]">Booking not found</h2>
        <p class="body mt-2 text-[#F7F7F7]/40 leading-relaxed text-sm">
          You don't have access to this reservation, or it does not exist.
        </p>
        <a
          href="/bookings"
          class="btn-lime label inline-flex items-center justify-center gap-2 rounded-full px-6 py-2.5 font-semibold text-sm bg-[#E6FA50] text-[#06121A] hover:bg-[#E6FA50]/90 transition-all mt-6"
        >
          <ArrowLeft class="h-4 w-4" />
          Back to bookings
        </a>
      </div>
    </div>
  {:else}
    {@const venue = booking.venue}
    {@const court = booking.court}
    {@const currentBooking = booking}

    <!-- Header -->
    <section class="container pb-8">
      <div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <div class="flex items-center gap-3 mb-2">
            <span class="caption rounded-full px-2.5 py-0.5 uppercase font-semibold {getStatusStyle(currentBooking.status)}">
              {currentBooking.status?.toLowerCase() || "completed"}
            </span>
            {#if currentBooking.payment}
              <span class="caption rounded-full px-2.5 py-0.5 uppercase font-semibold {getPaymentStyle(currentBooking.payment.status)}">
                {currentBooking.payment.status?.toLowerCase() || "paid"}
              </span>
            {/if}
          </div>
          <h1 class="heading-1 text-[#F7F7F7]">
            {venue?.name ?? "Unknown Venue"}
          </h1>
          <p class="body mt-1 flex items-center gap-2 text-[#F7F7F7]/40">
            <MapPin class="h-3.5 w-3.5" />
            {venue?.city}
          </p>
        </div>
        <div class="relative hidden h-20 w-32 overflow-hidden rounded-xl sm:block border border-white/[0.08]">
          <img
            src={venue?.imageUrl || padelImg(400)}
            alt={venue?.name ?? "Venue image"}
            class="h-full w-full object-cover"
          />
        </div>
      </div>
    </section>

    <!-- Main Content & Sticky Sidebar Grid -->
    <section class="container">
      <div class="grid grid-cols-1 gap-6 lg:grid-cols-3 lg:items-start">
        <!-- Main content (left column) -->
        <div class="lg:col-span-2 space-y-6">
          <!-- Booking Details -->
          <div class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6">
            <p class="section-label mb-4">Booking Information</p>
            <div class="grid grid-cols-2 gap-3 sm:grid-cols-3">
              <div class="rounded-xl bg-white/[0.02] p-3">
                <Ticket class="h-3.5 w-3.5 text-[#50C8C8]" />
                <p class="heading-3 mt-1.5 text-[#F7F7F7] break-all">#{currentBooking.id.slice(-6).toUpperCase()}</p>
                <p class="caption mt-0.5 text-[#F7F7F7]/25">Booking ID</p>
              </div>
              <div class="rounded-xl bg-white/[0.02] p-3">
                <MapPin class="h-3.5 w-3.5 text-[#50C8C8]" />
                <p class="heading-3 mt-1.5 text-[#F7F7F7] break-all">{court?.name ?? "Court A"} · {court?.type ?? "OUTDOOR"}</p>
                <p class="caption mt-0.5 text-[#F7F7F7]/25">Court</p>
              </div>
              <div class="rounded-xl bg-white/[0.02] p-3">
                <CalendarDays class="h-3.5 w-3.5 text-[#50C8C8]" />
                <p class="heading-3 mt-1.5 text-[#F7F7F7] break-all">{formatBookingDate(currentBooking.bookingDate)}</p>
                <p class="caption mt-0.5 text-[#F7F7F7]/25">Date</p>
              </div>
              <div class="rounded-xl bg-white/[0.02] p-3">
                <Clock class="h-3.5 w-3.5 text-[#50C8C8]" />
                <p class="heading-3 mt-1.5 text-[#F7F7F7] break-all">{formatBookingTimeRange(currentBooking.startsAt, currentBooking.endsAt)}</p>
                <p class="caption mt-0.5 text-[#F7F7F7]/25">Time</p>
              </div>
              <div class="rounded-xl bg-white/[0.02] p-3">
                <Timer class="h-3.5 w-3.5 text-[#50C8C8]" />
                <p class="heading-3 mt-1.5 text-[#F7F7F7] break-all">{currentBooking.durationMinutes || 60} min</p>
                <p class="caption mt-0.5 text-[#F7F7F7]/25">Duration</p>
              </div>
            </div>
          </div>

          <!-- Refund Policy -->
          <div class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6">
            <p class="section-label mb-4">Refund Policy</p>
            <div class="grid grid-cols-1 gap-3 sm:grid-cols-2">
              <div class="rounded-xl bg-white/[0.02] p-4">
                <ShieldCheck class="h-4 w-4 text-[#E6FA50]" />
                <p class="heading-3 mt-1.5 text-[#F7F7F7]">Full refund before H-1</p>
                <p class="caption mt-1 text-[#F7F7F7]/25">Cancel 24+ hours before your booking date — the full amount is returned to your original payment method.</p>
              </div>
              <div class="rounded-xl bg-white/[0.02] p-4">
                <ShieldX class="h-4 w-4 text-red-400" />
                <p class="heading-3 mt-1.5 text-[#F7F7F7]">Non-refundable after H-1</p>
                <p class="caption mt-1 text-[#F7F7F7]/25">Cancelling less than 24 hours before the start time isn't eligible for a refund.</p>
              </div>
            </div>
          </div>

          <!-- Leave a Review -->
          {#if currentBooking.status === "COMPLETED" || currentBooking.status === "completed"}
            <div class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6">
              <p class="section-label mb-4">Leave a Review</p>
              {#if reviewSubmitted}
                <div class="rounded-xl border border-[#E6FA50]/15 bg-[#E6FA50]/10 p-4">
                  <p class="body text-[#E6FA50]">{reviewError ?? "Thanks! Your review has been submitted."}</p>
                </div>
              {:else}
                <div class="space-y-4">
                  <div class="flex items-center gap-1.5">
                    {#each [1, 2, 3, 4, 5] as n}
                      <button type="button" onclick={() => (reviewRating = n)} class="transition-transform hover:scale-110">
                        <Star class="h-6 w-6 {n <= reviewRating ? 'fill-[#E6FA50] text-[#E6FA50]' : 'text-[#F7F7F7]/20'}" />
                      </button>
                    {/each}
                  </div>
                  <textarea
                    bind:value={reviewComment}
                    maxLength={1000}
                    rows={4}
                    placeholder="Share your experience (optional)"
                    class="body w-full resize-none rounded-xl border border-white/[0.06] bg-white/[0.02] px-4 py-3 text-[#F7F7F7] placeholder:text-[#F7F7F7]/25 focus:border-[#50C8C8]/40 focus:outline-none"
                  ></textarea>
                  {#if reviewError}
                    <div class="rounded-xl border border-amber-400/20 bg-amber-400/[0.06] px-4 py-3">
                      <p class="caption text-amber-300/80">{reviewError}</p>
                    </div>
                  {/if}
                  <button
                    type="button"
                    onclick={submitReview}
                    disabled={isSubmittingReview || reviewRating < 1}
                    class="label rounded-full bg-[#E6FA50] px-5 py-2.5 text-[#06121A] transition-colors hover:bg-[#E6FA50]/90 disabled:opacity-40"
                  >
                    {isSubmittingReview ? "Submitting..." : "Submit Review"}
                  </button>
                </div>
              {/if}
            </div>
          {/if}
        </div>

        <!-- Summary sidebar (sticky) -->
        <div class="space-y-6 lg:sticky lg:top-24">
          <!-- Payment -->
          <div id="payment" class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6">
            <p class="section-label mb-4">Payment</p>
            <div class="space-y-3 mb-4">
              <div class="flex items-center justify-between">
                <span class="caption text-[#F7F7F7]/40">Court fee</span>
                <span class="price text-[#F7F7F7]/60">Rp {((currentBooking.courtAmount || 300000) / 1000).toFixed(0)}K</span>
              </div>
              {#if currentBooking.voucherDiscount > 0}
                <div class="flex items-center justify-between">
                  <span class="caption text-[#F7F7F7]/40">Voucher</span>
                  <span class="price text-[#E6FA50]">-Rp {(currentBooking.voucherDiscount / 1000).toFixed(0)}K</span>
                </div>
              {/if}
              <div class="flex items-center justify-between">
                <span class="caption text-[#F7F7F7]/40">Platform fee</span>
                <span class="price text-[#F7F7F7]/60">Rp {((currentBooking.platformFee || 15000) / 1000).toFixed(0)}K</span>
              </div>
              <div class="flex items-center justify-between border-t border-white/[0.04] pt-3">
                <span class="body text-[#F7F7F7]/60 font-semibold">Total</span>
                <span class="price text-[#F7F7F7] text-xl font-bold">Rp {((currentBooking.finalAmount || 252000) / 1000).toFixed(0)}K</span>
              </div>
            </div>

            <div class="space-y-2 rounded-xl bg-white/[0.02] p-3">
              <div class="flex items-center justify-between">
                <span class="caption text-[#F7F7F7]/25">Status</span>
                <span class="caption rounded-full px-2.5 py-0.5 {getPaymentStyle(currentBooking.payment?.status || 'pending')}">
                  {currentBooking.payment?.status?.toLowerCase() || "pending"}
                </span>
              </div>
            </div>
          </div>

          <!-- Actions -->
          <div class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6">
            <p class="section-label mb-4">Actions</p>
            <div class="space-y-2">
              <button
                type="button"
                onclick={handleShareInvite}
                class="heading-3 w-full flex items-center gap-3 rounded-xl bg-white/[0.02] px-4 py-3 text-[#F7F7F7]/60 transition-colors hover:bg-white/[0.04] hover:text-[#F7F7F7]"
              >
                <Share2 class="h-4 w-4 text-[#50C8C8]" />
                Share invite link
                <Copy class="ml-auto h-3.5 w-3.5 text-[#F7F7F7]/25" />
              </button>
              <a
                href="/booking/{currentBooking.id}/payment"
                class="heading-3 w-full flex items-center gap-3 rounded-xl bg-white/[0.02] px-4 py-3 text-[#F7F7F7]/60 transition-colors hover:bg-white/[0.04] hover:text-[#F7F7F7]"
              >
                <CreditCard class="h-4 w-4 text-[#50C8C8]" />
                View payment receipt
              </a>
            </div>
          </div>
        </div>
      </div>
    </section>
  {/if}

  <!-- Toast -->
  {#if toast}
    <div class="fixed bottom-6 left-1/2 z-50 -translate-x-1/2 rounded-xl border border-white/[0.06] bg-[#0C1B26] px-5 py-3 shadow-2xl">
      <p class="caption text-[#F7F7F7]/60">{toast}</p>
    </div>
  {/if}
</div>
