// apps/web/src/routes/booking/[id]/payment/+page.svelte
<script lang="ts">
import {
  AlertCircle,
  ArrowLeft,
  Building2,
  Check,
  CheckCircle2,
  Clock,
  CreditCard,
  Info,
  Loader2,
  Lock,
  Plus,
  RefreshCw,
  ShieldCheck,
  UserPlus,
  Users,
  Wallet,
} from "lucide-svelte";
import { goto } from "$app/navigation";
import { page } from "$app/state";
import { api } from "$lib/api/client";
import { authStore } from "$lib/auth/store.svelte";
import EmptyState from "$lib/components/ui/empty-state.svelte";
import { formatBookingDate, formatBookingTimeRange } from "$lib/format";

const bookingId = $derived((page.params.id as string) || "");

let booking = $state<any | null>(null);
let invites = $state<any[]>([]);
let selectedMethod = $state("va");
let paymentIntent = $state<any | null>(null);

// Split payment states
let isSplitEnabled = $state(true);
let splitMode = $state<"equal" | "custom">("equal");

let isLoading = $state(true);
let isPaying = $state(false);
let error = $state<string | null>(null);

const PAYMENT_METHODS = [
  {
    id: "va",
    label: "Virtual Account",
    description: "BCA, Mandiri, BNI, BRI",
    icon: Building2,
  },
  {
    id: "ewallet",
    label: "E-Wallet",
    description: "GoPay, OVO, DANA, ShopeePay",
    icon: Wallet,
  },
  {
    id: "card",
    label: "Credit / Debit Card",
    description: "Visa, Mastercard",
    icon: CreditCard,
  },
];

async function loadData() {
  if (!bookingId) return;
  isLoading = true;
  error = null;
  try {
    const token = await authStore.firebaseUser?.getIdToken();
    if (!token) {
      isLoading = false;
      return;
    }

    const [bRes, iRes, pRes] = await Promise.all([
      api.bookings({ id: bookingId }).get({
        headers: { authorization: `Bearer ${token}` },
      }),
      api.bookings({ id: bookingId }).invites.get({
        headers: { authorization: `Bearer ${token}` },
      }),
      api.payments.intents
        .post(
          {
            bookingId,
            provider: "internal",
            method: selectedMethod as "va" | "ewallet" | "card",
          },
          { headers: { authorization: `Bearer ${token}` } },
        )
        .catch(() => ({ data: null })),
    ]);

    if (bRes.data) booking = bRes.data;
    if (iRes.data) invites = iRes.data;
    if (pRes.data) paymentIntent = pRes.data;
  } catch (e: any) {
    console.warn("Payment load error:", e);
    error = e.message || "Failed to load payment details";
  } finally {
    isLoading = false;
  }
}

// Reactive auth tracking to support hard reload
$effect(() => {
  if (authStore.isInitialized) {
    if (authStore.firebaseUser) {
      loadData();
    } else {
      isLoading = false;
    }
  }
});

// Calculate Split numbers dynamically
const totalAmount = $derived(booking?.finalAmount || 252000);
const platformFee = $derived(Math.round(totalAmount * 0.05));
const grandTotal = $derived(totalAmount + platformFee);

// Total active players (User + accepted/pending invites)
const totalPlayersCount = $derived(
  Math.max(1, 1 + (invites ? invites.length : 0)),
);

const pricePerPlayer = $derived(
  isSplitEnabled ? Math.round(grandTotal / totalPlayersCount) : grandTotal,
);

const paidByFriendsAmount = $derived.by(() => {
  if (!isSplitEnabled) return 0;
  const acceptedFriends = invites.filter((inv) => inv.status === "ACCEPTED");
  return acceptedFriends.length * pricePerPlayer;
});

const userFinalPayAmount = $derived.by(() => {
  if (!isSplitEnabled) return grandTotal;
  return Math.max(0, grandTotal - paidByFriendsAmount);
});

async function handlePay() {
  isPaying = true;
  error = null;

  try {
    const token = await authStore.firebaseUser?.getIdToken();
    if (!token) return;

    // Ensure payment intent exists
    let intentId = paymentIntent?.id;
    if (!intentId) {
      const pRes = await api.payments.intents.post(
        {
          bookingId,
          provider: "internal",
          method: selectedMethod as "va" | "ewallet" | "card",
        },
        { headers: { authorization: `Bearer ${token}` } },
      );
      if (pRes.data) intentId = pRes.data.id;
    }

    if (!intentId) {
      throw new Error("Could not initialize payment transaction.");
    }

    const res = await api
      .payments({ id: intentId })
      ["mark-paid"].patch(undefined, {
        headers: { authorization: `Bearer ${token}` },
      });

    if (res.data) {
      goto(`/booking/${bookingId}/success`);
    }
  } catch (err: any) {
    error = err.message || "Payment processing failed";
  } finally {
    isPaying = false;
  }
}
</script>

<svelte:head>
  <title>Payment Checkout | PadelHive</title>
</svelte:head>

<div class="min-h-screen pt-20 pb-24 bg-[#06121A]">
  <div class="container max-w-5xl pt-6">
    <!-- Back Navigation Link -->
    <a
      href={bookingId ? `/bookings/${bookingId}` : "/bookings"}
      class="group inline-flex items-center gap-3 text-xs font-medium text-[#F7F7F7]/60 transition-colors hover:text-[#F7F7F7]"
    >
      <div
        class="flex h-7 w-7 items-center justify-center rounded-lg border border-white/[0.08] bg-white/[0.03] text-[#F7F7F7]/40 transition-all duration-200 group-hover:border-[#E6FA50]/40 group-hover:bg-[#E6FA50]/10 group-hover:text-[#E6FA50]"
      >
        <ArrowLeft class="h-3.5 w-3.5" />
      </div>
      <span>Back to booking summary</span>
    </a>

    <!-- Page Header -->
    <div class="mt-4 mb-8">
      <h1 class="heading-1 text-[#F7F7F7]">
        Payment <span class="text-[#E6FA50]">Checkout</span>
      </h1>
      <p class="body mt-1 text-[#F7F7F7]/40">
        Review your reservation details, manage split payments, and complete checkout.
      </p>
    </div>

    {#if error}
      <div
        class="mb-6 flex items-center gap-3 rounded-xl border border-red-500/20 bg-red-500/10 p-4"
      >
        <AlertCircle class="h-5 w-5 shrink-0 text-red-400" />
        <p class="body text-red-100/90">{error}</p>
      </div>
    {/if}

    {#if isLoading || !authStore.isInitialized || authStore.isLoading}
      <!-- Loading Skeleton -->
      <div class="grid grid-cols-1 gap-8 lg:grid-cols-[1fr_360px]">
        <div class="space-y-6">
          <div class="h-44 animate-pulse rounded-2xl border border-white/[0.06] bg-[#0C1B26]"></div>
          <div class="h-64 animate-pulse rounded-2xl border border-white/[0.06] bg-[#0C1B26]"></div>
          <div class="h-48 animate-pulse rounded-2xl border border-white/[0.06] bg-[#0C1B26]"></div>
        </div>
        <div class="h-96 animate-pulse rounded-2xl border border-white/[0.06] bg-[#0C1B26]"></div>
      </div>
    {:else if !booking}
      <!-- Empty Not Found -->
      <div class="mx-auto max-w-xl py-12 text-center">
        <EmptyState
          icon={CreditCard}
          title="Booking not found"
          description="This booking reservation could not be found or you don't have access to pay."
          actionLabel="Back to bookings"
          actionHref="/bookings"
        />
      </div>
    {:else}
      <!-- Main Content Grid -->
      <div class="grid grid-cols-1 gap-8 lg:grid-cols-[1fr_360px]">
        <!-- Left Column: Details, Split Payment & Payment Method -->
        <div class="space-y-8">
          <!-- 1. BOOKING DETAILS CARD -->
          <div class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6 space-y-4">
            <h2 class="text-xs font-semibold tracking-wider text-[#F7F7F7]/60 uppercase">
              BOOKING DETAILS
            </h2>
            <div class="grid grid-cols-1 sm:grid-cols-2 gap-4 text-sm pt-1">
              <div class="flex flex-col">
                <span class="text-xs font-medium text-[#F7F7F7]/40 mb-0.5">Venue</span>
                <span class="font-semibold text-[#F7F7F7]">{booking.venue?.name || "Padel Arena"}</span>
              </div>

              <div class="flex flex-col">
                <span class="text-xs font-medium text-[#F7F7F7]/40 mb-0.5">Court</span>
                <span class="font-semibold text-[#F7F7F7]">
                  {booking.court?.name || "Court A"}
                  {#if booking.court?.type}
                    <span class="ml-1.5 rounded bg-white/[0.06] px-2 py-0.5 text-[10px] font-normal text-[#F7F7F7]/60 uppercase">
                      {booking.court.type}
                    </span>
                  {/if}
                </span>
              </div>

              <div class="flex flex-col">
                <span class="text-xs font-medium text-[#F7F7F7]/40 mb-0.5">Date</span>
                <span class="font-semibold text-[#F7F7F7]">
                  {booking.bookingDate ? formatBookingDate(new Date(booking.bookingDate)) : "Sat, Aug 15, 2026"}
                </span>
              </div>

              <div class="flex flex-col">
                <span class="text-xs font-medium text-[#F7F7F7]/40 mb-0.5">Time</span>
                <span class="font-semibold text-[#E6FA50]">
                  {formatBookingTimeRange(booking.startsAt, booking.endsAt)}
                </span>
              </div>
            </div>
          </div>

          <!-- 2. SPLIT PAYMENT SECTION -->
          <div class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6 space-y-5">
            <!-- Header with Toggle -->
            <div class="flex items-center justify-between">
              <div class="flex items-center gap-2.5">
                <Users class="h-4 w-4 text-[#50C8C8]" />
                <div>
                  <h2 class="text-xs font-semibold tracking-wider text-[#F7F7F7] uppercase">
                    SPLIT PAYMENT
                  </h2>
                  <p class="text-xs text-[#F7F7F7]/40 mt-0.5">
                    Split the cost equally among all players
                  </p>
                </div>
              </div>

              <!-- Toggle Switch -->
              <button
                type="button"
                role="switch"
                aria-checked={isSplitEnabled}
                aria-label="Toggle split payment"
                onclick={() => (isSplitEnabled = !isSplitEnabled)}
                class="relative inline-flex h-6 w-11 shrink-0 cursor-pointer rounded-full p-0.5 transition-colors duration-200 ease-in-out focus:outline-none {isSplitEnabled ? 'bg-[#E6FA50]' : 'bg-white/[0.15]'}"
              >
                <span
                  class="pointer-events-none inline-block h-5 w-5 transform rounded-full bg-white shadow-md transition-transform duration-200 ease-in-out {isSplitEnabled ? 'translate-x-5' : 'translate-x-0'}"
                ></span>
              </button>
            </div>

            {#if isSplitEnabled}
              <!-- Mode selector: Equal vs Custom -->
              <div class="flex h-10 w-full rounded-xl border border-white/[0.08] bg-white/[0.02] p-1">
                <button
                  type="button"
                  onclick={() => (splitMode = "equal")}
                  class="flex-1 rounded-lg text-xs font-semibold transition-all {splitMode === 'equal' ? 'bg-[#06121A] text-[#E6FA50] shadow-sm' : 'text-[#F7F7F7]/40 hover:text-[#F7F7F7]'}"
                >
                  Equal
                </button>
                <button
                  type="button"
                  onclick={() => (splitMode = "custom")}
                  class="flex-1 rounded-lg text-xs font-semibold transition-all {splitMode === 'custom' ? 'bg-[#06121A] text-[#E6FA50] shadow-sm' : 'text-[#F7F7F7]/40 hover:text-[#F7F7F7]'}"
                >
                  Custom
                </button>
              </div>

              <!-- Info/Notice box -->
              <div class="rounded-xl border border-amber-500/20 bg-amber-500/10 p-3.5 flex items-center gap-3">
                <Info class="h-4 w-4 shrink-0 text-amber-400" />
                <p class="text-xs text-amber-200/90 leading-relaxed">
                  Split is active. Each player pays their share. Friends who haven't paid will be charged separately.
                </p>
              </div>

              <!-- Price Per Player Summary Bar -->
              <div class="flex items-center justify-between rounded-xl border border-white/[0.06] bg-white/[0.02] p-4">
                <div>
                  <span class="text-xs font-medium text-[#F7F7F7]/60 block">Price per player</span>
                  <span class="text-[11px] text-[#F7F7F7]/40">
                    Total Rp {(grandTotal / 1000).toFixed(0)}K ÷ {totalPlayersCount} players
                  </span>
                </div>
                <span class="text-lg font-bold text-[#E6FA50]">
                  Rp {(pricePerPlayer / 1000).toFixed(0)}K
                </span>
              </div>

              <!-- Players List -->
              <div class="space-y-3 pt-1">
                <!-- User (Main Organizer) -->
                <div class="flex items-center justify-between rounded-xl border border-white/[0.06] bg-white/[0.015] p-3.5">
                  <div class="flex items-center gap-3">
                    <div class="flex h-9 w-9 items-center justify-center rounded-full bg-[#E6FA50]/15 text-sm font-bold text-[#E6FA50]">
                      {(authStore.user?.name || authStore.user?.email || "U")[0].toUpperCase()}
                    </div>
                    <div>
                      <p class="text-xs font-semibold text-[#F7F7F7]">
                        {authStore.user?.name || "You (Host)"}
                      </p>
                      <p class="text-[11px] text-[#F7F7F7]/40">
                        Rp {(pricePerPlayer / 1000).toFixed(0)}K
                      </p>
                    </div>
                  </div>

                  <span class="rounded-full bg-[#E6FA50] px-4 py-1.5 text-xs font-bold text-[#06121A]">
                    Pay Rp {(pricePerPlayer / 1000).toFixed(0)}K
                  </span>
                </div>

                <!-- Invited Friends -->
                {#each invites as invite}
                  <div class="flex items-center justify-between rounded-xl border border-white/[0.06] bg-white/[0.015] p-3.5">
                    <div class="flex items-center gap-3">
                      <div class="flex h-9 w-9 items-center justify-center rounded-full bg-[#50C8C8]/15 text-sm font-bold text-[#50C8C8]">
                        {(invite.name || invite.email || "F")[0].toUpperCase()}
                      </div>
                      <div>
                        <p class="text-xs font-semibold text-[#F7F7F7]">
                          {invite.name || invite.email}
                        </p>
                        <p class="text-[11px] text-[#F7F7F7]/40">
                          Rp {(pricePerPlayer / 1000).toFixed(0)}K
                        </p>
                      </div>
                    </div>

                    {#if invite.status === "ACCEPTED"}
                      <div class="flex items-center gap-1.5 rounded-full bg-emerald-400/10 px-3 py-1 text-xs font-semibold text-emerald-400">
                        <CheckCircle2 class="h-3.5 w-3.5" />
                        <span>Paid</span>
                      </div>
                    {:else}
                      <div class="flex items-center gap-1.5 rounded-full bg-white/[0.06] px-3 py-1 text-xs font-medium text-[#F7F7F7]/60">
                        <Clock class="h-3.5 w-3.5 text-[#50C8C8]" />
                        <span>Pending</span>
                      </div>
                    {/if}
                  </div>
                {/each}
              </div>

              <!-- Invite Friends Button Shortcut -->
              <a
                href="/booking/{bookingId}/invite"
                class="flex items-center justify-center gap-2.5 rounded-xl border border-dashed border-white/[0.12] bg-white/[0.01] p-3.5 text-xs font-medium text-[#F7F7F7]/70 transition-all hover:border-[#E6FA50]/40 hover:bg-[#E6FA50]/5 hover:text-[#E6FA50]"
              >
                <UserPlus class="h-4 w-4" />
                <span>Invite more friends to split cost</span>
              </a>
            {/if}
          </div>

          <!-- 3. PAYMENT METHOD SECTION -->
          <div class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6 space-y-4">
            <h2 class="text-xs font-semibold tracking-wider text-[#F7F7F7]/60 uppercase">
              PAYMENT METHOD
            </h2>
            <div class="space-y-3">
              {#each PAYMENT_METHODS as method}
                {@const MethodIcon = method.icon}
                <button
                  type="button"
                  onclick={() => (selectedMethod = method.id)}
                  class="flex w-full items-center justify-between rounded-xl border p-4 text-left transition-all {selectedMethod ===
                  method.id
                    ? 'border-[#E6FA50] bg-[#E6FA50]/10 shadow-sm'
                    : 'border-white/[0.06] bg-white/[0.015] hover:border-white/[0.12]'}"
                >
                  <div class="flex items-center gap-3.5">
                    <div class="flex h-10 w-10 items-center justify-center rounded-xl bg-white/[0.04]">
                      <MethodIcon class="h-5 w-5 text-[#50C8C8]" />
                    </div>
                    <div>
                      <p class="text-sm font-semibold text-[#F7F7F7]">{method.label}</p>
                      <p class="text-xs text-[#F7F7F7]/40">{method.description}</p>
                    </div>
                  </div>
                  <div class="flex h-5 w-5 items-center justify-center rounded-full border transition-colors {selectedMethod === method.id ? 'border-[#E6FA50] bg-[#E6FA50]' : 'border-white/20'}">
                    {#if selectedMethod === method.id}
                      <div class="h-2 w-2 rounded-full bg-[#06121A]"></div>
                    {/if}
                  </div>
                </button>
              {/each}
            </div>
          </div>
        </div>

        <!-- Right Column: Order Summary (Sticky) -->
        <div class="lg:relative">
          <div class="lg:sticky lg:top-24">
            <div class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6 space-y-6 shadow-2xl">
              <h3 class="text-xs font-semibold tracking-wider text-[#F7F7F7] uppercase">
                ORDER SUMMARY
              </h3>

              <div class="space-y-3 border-y border-white/[0.06] py-4 text-xs">
                <div class="flex justify-between">
                  <span class="text-[#F7F7F7]/60">Court rental</span>
                  <span class="font-medium text-[#F7F7F7]">Rp {(totalAmount / 1000).toFixed(0)}K</span>
                </div>

                <div class="flex justify-between">
                  <span class="text-[#F7F7F7]/60">Platform fee (5%)</span>
                  <span class="font-medium text-[#F7F7F7]">Rp {(platformFee / 1000).toFixed(0)}K</span>
                </div>

                {#if isSplitEnabled && paidByFriendsAmount > 0}
                  <div class="flex justify-between text-emerald-400">
                    <span>Paid by friends</span>
                    <span>-Rp {(paidByFriendsAmount / 1000).toFixed(0)}K</span>
                  </div>
                {/if}

                <div class="flex justify-between items-baseline pt-3 border-t border-white/[0.06]">
                  <span class="text-sm font-semibold text-[#F7F7F7]">You pay</span>
                  <span class="text-2xl font-extrabold text-[#E6FA50]">
                    Rp {(userFinalPayAmount / 1000).toFixed(0)}K
                  </span>
                </div>
              </div>

              <!-- Pay CTA Button -->
              <button
                type="button"
                disabled={isPaying}
                onclick={handlePay}
                class="btn-lime label flex h-12 w-full items-center justify-center gap-2 rounded-full font-bold text-[#06121A] disabled:opacity-50"
              >
                {#if isPaying}
                  <Loader2 class="h-4 w-4 animate-spin" />
                  <span>Processing Payment...</span>
                {:else}
                  <span>Pay Now · Rp {(userFinalPayAmount / 1000).toFixed(0)}K</span>
                {/if}
              </button>

              <!-- Security guarantee -->
              <div class="flex items-center justify-center gap-2 text-[11px] text-[#F7F7F7]/40 text-center">
                <ShieldCheck class="h-4 w-4 text-[#50C8C8]" />
                <span>Secure payment provided by Midtrans</span>
              </div>

              <!-- Cancellation policy note box -->
              <div class="rounded-xl border border-white/[0.04] bg-white/[0.015] p-3 text-[11px] text-[#F7F7F7]/40 leading-relaxed">
                Free cancellation up to 24h before booking. After that, standard refund policy applies.
              </div>
            </div>
          </div>
        </div>
      </div>
    {/if}
  </div>
</div>

// apps/web/src/app/(app)/booking/[id]/payment/page.tsx
"use client";

import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { queryKeys } from "@/lib/queries";
import Script from "next/script";
import Link from "next/link";
import { useRouter } from "next/navigation";
import {
  ArrowLeft,
  CreditCard,
  Wallet,
  Building2,
  Users,
  CheckCircle2,
  Clock,
  AlertCircle,
  Shield,
  UserPlus,
} from "lucide-react";
import { ApiRequestError, createPaymentIntent, markPaymentPaid, getBookingById } from "@/lib/api";

declare global {
  interface Window {
    snap: {
      pay: (
        token: string,
        options?: {
          onSuccess?: (result: any) => void;
          onPending?: (result: any) => void;
          onError?: (result: any) => void;
          onClose?: () => void;
        }
      ) => void;
    };
  }
}

interface SplitPlayer {
  id: string;
  name: string;
  avatar: string;
  amount: number;
  status: "paid" | "pending" | "unpaid";
}

const PAYMENT_METHODS = [
  {
    id: "va",
    label: "Virtual Account",
    description: "BCA, Mandiri, BNI, BRI",
    icon: Building2,
  },
  {
    id: "ewallet",
    label: "E-Wallet",
    description: "GoPay, OVO, DANA, ShopeePay",
    icon: Wallet,
  },
  {
    id: "card",
    label: "Credit / Debit Card",
    description: "Visa, Mastercard",
    icon: CreditCard,
  },
];

const SPLIT_PLAYERS: SplitPlayer[]= [
  {
    id: "p1",
    name: "You",
    avatar: "https://i.pravatar.cc/150?u=you",
    amount: 0,
    status: "pending",
  },
  {
    id: "p2",
    name: "Andi Saputra",
    avatar: "https://i.pravatar.cc/150?u=andi",
    amount: 0,
    status: "paid",
  },
  {
    id: "p3",
    name: "Budi Rahmat",
    avatar: "https://i.pravatar.cc/150?u=budi",
    amount: 0,
    status: "pending",
  },
  {
    id: "p4",
    name: "Clara Wijaya",
    avatar: "https://i.pravatar.cc/150?u=clara",
    amount: 0,
    status: "unpaid",
  },
];

const SPLIT_STATUS_CONFIG = {
  paid: {
    label: "Paid",
    icon: CheckCircle2,
    color: "text-green-400",
    bg: "bg-green-400/10",
  },
  pending: {
    label: "Pending",
    icon: Clock,
    color: "text-yellow-400",
    bg: "bg-yellow-400/10",
  },
  unpaid: {
    label: "Not Paid",
    icon: AlertCircle,
    color: "text-red-400",
    bg: "bg-red-400/10",
  },
};

export default function PaymentPage({
  params,
}: {
  params: { id: string };
}) {
  const router = useRouter();
  const [selectedMethod, setSelectedMethod] = useState<string | null>(null);
  const [splitEnabled, setSplitEnabled] = useState(false);
  const [processing, setProcessing] = useState(false);
  const [paymentError, setPaymentError] = useState<string | null>(null);
  const [markingPaid, setMarkingPaid] = useState(false);

  const isDemoMode = process.env.NEXT_PUBLIC_MIDTRANS_IS_PRODUCTION !== "true";
  const snapScriptUrl = isDemoMode
    ? "https://app.sandbox.midtrans.com/snap/snap.js"
    : "https://app.midtrans.com/snap/snap.js";
  const clientKey = process.env.NEXT_PUBLIC_MIDTRANS_CLIENT_KEY;

  const { data: booking, isLoading: isBookingLoading, isError: isBookingError } = useQuery({
    queryKey: queryKeys.bookings.detail(params.id),
    queryFn: () => getBookingById(params.id),
  });

  const venue = booking?.venue.name ?? "—";
  const court = booking?.court.name ?? "—";
  const date = booking?.bookingDate ?? "—";
  const start = booking?.startsAt ?? "—";
  const end = booking?.endsAt ?? "—";
  const amount = booking?.courtAmount ?? 0;
  const venueId = booking?.venue.id ?? "";

  const platformFee = booking?.platformFee ?? 0;
  const totalAmount = booking?.finalAmount ?? 0;

  const playerCount = SPLIT_PLAYERS.length;
  const perPlayer = Math.ceil(totalAmount / playerCount);

  const players = SPLIT_PLAYERS.map((p) => ({
    ...p,
    amount: perPlayer,
  }));

  const paidAmount = players
    .filter((p) => p.status === "paid")
    .reduce((sum, p) => sum + p.amount, 0);
  const yourShare = splitEnabled ? totalAmount - paidAmount : totalAmount;

  const formattedDate = (() => {
    try {
      return new Date(date).toLocaleDateString("en-US", {
        weekday: "short",
        month: "short",
        day: "numeric",
      });
    } catch {
      return date;
    }
  })();

  async function handlePay() {
    if (!selectedMethod || processing || !booking) return;

    if (typeof window === "undefined" || !window.snap) {
      setPaymentError("Payment module is still loading. Please try again in a moment.");
      setProcessing(false);
      return;
    }

    setProcessing(true);
    setPaymentError(null);

    try {
      const paymentIntent = await createPaymentIntent(
        { bookingId: params.id, method: selectedMethod as "va" | "ewallet" | "card" }
      );
      
      if (paymentIntent.providerToken) {
        window.snap.pay(paymentIntent.providerToken, {
          onSuccess: () => {
            router.push(`/booking/${params.id}/success?paymentId=${paymentIntent.id}`);
          },
          onPending: () => {
            router.push(`/booking/${params.id}/success?paymentId=${paymentIntent.id}`);
          },
          onError: () => {
            setPaymentError("Payment failed or was declined. Please try again.");
            setProcessing(false);
          },
          onClose: () => {
            setProcessing(false);
          }
        });
      } else {
        setPaymentError("Missing payment token. Please try again.");
        setProcessing(false);
      }
    } catch (error) {
      if (error instanceof ApiRequestError) {
        if (error.status === 401 || error.status === 403) {
          setPaymentError("Sign in before creating a payment intent.");
        } else if (error.status === 404) {
          setPaymentError("Booking or payment was not found.");
        } else if (error.status === 400) {
          setPaymentError("This booking cannot be paid with the selected method.");
        } else if (error.status && error.status >= 500) {
          setPaymentError("Payment service is unavailable. Please try again later.");
        } else {
          setPaymentError("Could not create payment intent. Please try again.");
        }
      } else {
        setPaymentError("Payment service is unavailable. Please try again later.");
      }
      setProcessing(false);
    }
  }

  async function handleMarkPaid() {
    if (markingPaid) return;

    setMarkingPaid(true);
    setPaymentError(null);

    try {
      let paymentId = booking?.payment?.id;
      if (!paymentId) {
        try {
          const paymentIntent = await createPaymentIntent({ bookingId: params.id, method: "va" });
          paymentId = paymentIntent.id;
        } catch (err: any) {
          if (err instanceof ApiRequestError && err.status === 409) {
            const freshBooking = await getBookingById(params.id);
            if (freshBooking.payment?.id) {
              paymentId = freshBooking.payment.id;
            } else {
              throw new Error("Could not resolve existing payment.");
            }
          } else {
            throw err;
          }
        }
      }

      const paidPayment = await markPaymentPaid(paymentId);
      router.push(`/booking/${params.id}/success?paymentId=${paidPayment.id}`);
    } catch (error) {
      if (error instanceof ApiRequestError) {
        setPaymentError(error.message || "Could not mark demo payment as paid.");
      } else {
        setPaymentError("Payment service is unavailable.");
      }
    } finally {
      setMarkingPaid(false);
    }
  }



  return (
    <div className="min-h-screen pt-20">
      <Script src={snapScriptUrl} data-client-key={clientKey} strategy="afterInteractive" />
      <div className="container max-w-4xl py-8">
        {/* Back */}
        <Link
          href={`/venues/${venueId}/book`}
          className="inline-flex items-center gap-2 text-sm text-[#F7F7F7]/40 hover:text-[#F7F7F7]/60 transition-colors"
        >
          <ArrowLeft className="h-4 w-4" />
          Back to booking
        </Link>

        {/* Header */}
        <div className="mt-6">
          <h1 className="heading-1 text-2xl text-[#F7F7F7] md:text-3xl">
            Payment
          </h1>
          <p className="mt-2 text-sm text-[#F7F7F7]/40">
            Complete your booking
          </p>
        </div>

        <div className="mt-8 grid grid-cols-1 gap-8 lg:grid-cols-[1fr_380px]">
          {/* Left — Payment options */}
          <div className="space-y-8">
            {/* Booking Summary Card */}
            <div className="rounded-xl border border-white/[0.06] bg-[#0C1B26] p-5">
              <h3 className="heading-3 text-sm text-[#F7F7F7]/60 uppercase tracking-wider">
                Booking Details
              </h3>
              <div className="mt-4 space-y-3">
                {isBookingLoading ? (
                  <div className="text-sm text-[#F7F7F7]/40">Loading booking details...</div>
                ) : isBookingError ? (
                  <div className="text-sm text-red-400">Error loading booking details.</div>
                ) : (
                  <>
                    <div className="flex items-center justify-between text-sm">
                      <span className="text-[#F7F7F7]/40">Venue</span>
                      <span className="text-[#F7F7F7]/80">{venue}</span>
                    </div>
                    <div className="flex items-center justify-between text-sm">
                      <span className="text-[#F7F7F7]/40">Court</span>
                      <span className="text-[#F7F7F7]/80">{court}</span>
                    </div>
                    <div className="flex items-center justify-between text-sm">
                      <span className="text-[#F7F7F7]/40">Date</span>
                      <span className="text-[#F7F7F7]/80">{formattedDate}</span>
                    </div>
                    <div className="flex items-center justify-between text-sm">
                      <span className="text-[#F7F7F7]/40">Time</span>
                      <span className="text-[#F7F7F7]/80">
                        {start} – {end}
                      </span>
                    </div>
                  </>
                )}
              </div>
            </div>

            {/* Split Payment Toggle */}
            <div>
              <div className="flex items-center justify-between">
                <h2 className="heading-3 text-sm text-[#F7F7F7]/60 uppercase tracking-wider">
                  <Users className="mr-2 inline h-3.5 w-3.5" />
                  Split Payment
                </h2>
                <button
                  onClick={() => setSplitEnabled(!splitEnabled)}
                  className={`relative h-6 w-11 rounded-full transition-colors ${
                    splitEnabled ? "bg-[#E6FA50]" : "bg-white/[0.1]"
                  }`}
                >
                  <span
                    className={`absolute top-0.5 h-5 w-5 rounded-full bg-white shadow transition-transform ${
                      splitEnabled ? "left-[22px]" : "left-0.5"
                    }`}
                  />
                </button>
              </div>
              <p className="mt-1 text-[11px] text-[#F7F7F7]/25">
                Split the cost equally among all players
              </p>

              {splitEnabled && (
                <div className="mt-4 space-y-3">
                  <div className="rounded-xl border border-[#E6FA50]/10 bg-[#E6FA50]/[0.03] p-4">
                    <div className="flex items-center justify-between">
                      <span className="text-sm text-[#F7F7F7]/60">
                        Price per player
                      </span>
                      <span className="text-sm font-semibold text-[#E6FA50]">
                        Rp {perPlayer.toLocaleString("id-ID")}
                      </span>
                    </div>
                    <p className="mt-1 text-[10px] text-[#F7F7F7]/25">
                      Total Rp {totalAmount.toLocaleString("id-ID")} ÷{" "}
                      {playerCount} players
                    </p>
                  </div>

                  {players.map((player) => {
                    const config = SPLIT_STATUS_CONFIG[player.status];
                    const StatusIcon = config.icon;
                    return (
                      <div
                        key={player.id}
                        className="flex items-center justify-between rounded-xl border border-white/[0.06] bg-[#0C1B26] p-4"
                      >
                        <div className="flex items-center gap-3">
                          <img
                            src={player.avatar}
                            alt={player.name}
                            className="h-9 w-9 rounded-full object-cover"
                          />
                          <div>
                            <p className="text-sm font-medium text-[#F7F7F7]/80">
                              {player.name}
                            </p>
                            <p className="text-[11px] text-[#F7F7F7]/25">
                              Rp {player.amount.toLocaleString("id-ID")}
                            </p>
                          </div>
                        </div>
                        <div
                          className={`flex items-center gap-1.5 rounded-full px-3 py-1.5 ${config.bg}`}
                        >
                          <StatusIcon
                            className={`h-3.5 w-3.5 ${config.color}`}
                          />
                          <span
                            className={`text-[11px] font-medium ${config.color}`}
                          >
                            {config.label}
                          </span>
                        </div>
                      </div>
                    );
                  })}

                  <div className="rounded-lg bg-white/[0.02] p-3">
                    <p className="text-[11px] text-[#F7F7F7]/25">
                      You pay the remaining balance. Friends who haven&apos;t
                      paid will be charged their share separately.
                    </p>
                  </div>
                </div>
              )}
            </div>

            {/* Invite Friends Link */}
            <Link
              href={`/booking/${params.id}/invite`}
              className="flex items-center gap-3 rounded-xl border border-dashed border-white/[0.08] bg-white/[0.01] p-4 transition-colors hover:border-[#50C8C8]/20 hover:bg-[#50C8C8]/[0.02]"
            >
              <div className="flex h-10 w-10 items-center justify-center rounded-full bg-[#50C8C8]/10">
                <UserPlus className="h-4 w-4 text-[#50C8C8]" />
              </div>
              <div>
                <p className="text-sm font-medium text-[#F7F7F7]/60">
                  Invite Friends
                </p>
                <p className="text-[11px] text-[#F7F7F7]/25">
                  Share your booking link and manage RSVPs
                </p>
              </div>
            </Link>

            {/* Payment Method */}
            <div>
              <h2 className="heading-3 text-sm text-[#F7F7F7]/60 uppercase tracking-wider">
                <CreditCard className="mr-2 inline h-3.5 w-3.5" />
                Payment Method
              </h2>
              <div className="mt-4 space-y-3">
                {PAYMENT_METHODS.map((method) => {
                  const Icon = method.icon;
                  const isSelected = selectedMethod === method.id;
                  return (
                    <button
                      key={method.id}
                      onClick={() => setSelectedMethod(method.id)}
                      className={`flex w-full items-center gap-4 rounded-xl border p-4 text-left transition-all ${
                        isSelected
                          ? "border-[#E6FA50]/40 bg-[#E6FA50]/5"
                          : "border-white/[0.06] bg-[#0C1B26] hover:border-white/[0.12]"
                      }`}
                    >
                      <div
                        className={`flex h-10 w-10 items-center justify-center rounded-lg ${
                          isSelected
                            ? "bg-[#E6FA50]/15 text-[#E6FA50]"
                            : "bg-white/[0.04] text-[#F7F7F7]/40"
                        }`}
                      >
                        <Icon className="h-5 w-5" />
                      </div>
                      <div className="flex-1">
                        <p
                          className={`text-sm font-medium ${
                            isSelected
                              ? "text-[#E6FA50]"
                              : "text-[#F7F7F7]/60"
                          }`}
                        >
                          {method.label}
                        </p>
                        <p className="text-[11px] text-[#F7F7F7]/25">
                          {method.description}
                        </p>
                      </div>
                      <div
                        className={`h-5 w-5 rounded-full border-2 ${
                          isSelected
                            ? "border-[#E6FA50] bg-[#E6FA50]"
                            : "border-white/[0.15]"
                        }`}
                      >
                        {isSelected && (
                          <div className="flex h-full w-full items-center justify-center">
                            <div className="h-2 w-2 rounded-full bg-[#06121A]" />
                          </div>
                        )}
                      </div>
                    </button>
                  );
                })}
              </div>
            </div>
          </div>

          {/* Right — Order Summary */}
          <div className="lg:relative">
            <div className="lg:sticky lg:top-28">
              <div className="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6">
                <h3 className="heading-3 text-sm text-[#F7F7F7]/60 uppercase tracking-wider">
                  Order Summary
                </h3>

                <div className="mt-5 space-y-3">
                  <div className="flex items-center justify-between text-sm">
                    <span className="text-[#F7F7F7]/40">Court rental</span>
                    <span className="text-[#F7F7F7]/60">
                      Rp {amount.toLocaleString("id-ID")}
                    </span>
                  </div>
                  <div className="flex items-center justify-between text-sm">
                    <span className="text-[#F7F7F7]/40">Platform fee (5%)</span>
                    <span className="text-[#F7F7F7]/60">
                      Rp {platformFee.toLocaleString("id-ID")}
                    </span>
                  </div>
                  {booking && booking.voucherDiscount > 0 && (
                    <div className="flex items-center justify-between text-sm">
                      <span className="text-[#F7F7F7]/40">Voucher discount</span>
                      <span className="text-[#E6FA50]/80">- Rp {booking.voucherDiscount.toLocaleString("id-ID")}</span>
                    </div>
                  )}
                  {splitEnabled && (
                    <div className="flex items-center justify-between text-sm">
                      <span className="text-[#F7F7F7]/40">
                        Paid by friends
                      </span>
                      <span className="text-green-400/70">
                        - Rp {paidAmount.toLocaleString("id-ID")}
                      </span>
                    </div>
                  )}
                </div>

                <div className="mt-4 border-t border-white/[0.06] pt-4">
                  <div className="flex items-center justify-between">
                    <span className="text-sm font-medium text-[#F7F7F7]/60">
                      {splitEnabled ? "You pay" : "Total"}
                    </span>
                    <span className="price text-xl text-[#F7F7F7]">
                      Rp {yourShare.toLocaleString("id-ID")}
                    </span>
                  </div>
                </div>

                {paymentError && (
                  <div className="mt-4 rounded-xl border border-red-500/20 bg-red-500/10 p-3">
                    <p className="text-[11px] leading-relaxed text-red-200/80">{paymentError}</p>
                  </div>
                )}

                <button
                  onClick={handlePay}
                  disabled={!selectedMethod || processing || !booking || !clientKey}
                  className="btn-lime mt-6 flex h-12 w-full items-center justify-center rounded-full text-[11px] font-semibold uppercase tracking-[0.08em] disabled:opacity-30 disabled:cursor-not-allowed"
                >
                  {processing ? "Processing..." : "Pay with Midtrans"}
                </button>

                {!clientKey && (
                  <div className="mt-2 rounded-xl border border-red-500/20 bg-red-500/10 p-3">
                    <p className="text-[11px] leading-relaxed text-red-200/80">Missing Midtrans Client Key configuration.</p>
                  </div>
                )}

                {isDemoMode && (
                  <button
                    onClick={handleMarkPaid}
                    disabled={markingPaid || processing || !booking}
                    className="mt-3 flex h-12 w-full items-center justify-center rounded-full border border-white/[0.08] text-[11px] font-semibold uppercase tracking-[0.08em] text-[#F7F7F7]/60 transition-colors hover:border-[#E6FA50]/30 hover:text-[#E6FA50] disabled:opacity-30 disabled:cursor-not-allowed"
                  >
                    {markingPaid ? "Marking Paid..." : "Mark as Paid (Demo)"}
                  </button>
                )}

                <div className="mt-4 flex items-center justify-center gap-2 text-[11px] text-[#F7F7F7]/25">
                  <Shield className="h-3 w-3" />
                  <span>Secure payment provided by Midtrans</span>
                </div>

                <div className="mt-3 rounded-lg bg-white/[0.02] p-3">
                  <p className="text-[11px] leading-relaxed text-[#F7F7F7]/25">
                    Free cancellation up to 24h before booking. After that,
                    standard refund policy applies.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
