// apps/web/src/routes/bookings/[id]/+page.svelte
<script lang="ts">
import {
  AlertCircle,
  ArrowLeft,
  CalendarDays,
  Clock,
  Copy,
  CreditCard,
  Loader2,
  MapPin,
  Share2,
  ShieldCheck,
  ShieldX,
  Star,
  Ticket,
  Timer,
  XCircle,
} from "lucide-svelte";
import { onMount } from "svelte";
import { page } from "$app/state";
import { api } from "$lib/api/client";
import { authStore } from "$lib/auth/store.svelte";
import { formatBookingDate, formatBookingTimeRange } from "$lib/format";
import { padelImg } from "$lib/images";

const bookingId = $derived((page.params.id as string) || "");

let booking = $state<any | null>(null);
let isLoading = $state(true);
let reviewRating = $state(0);
let reviewComment = $state("");
let isSubmittingReview = $state(false);
let reviewError = $state<string | null>(null);
let reviewSubmitted = $state(false);
let toast = $state<string | null>(null);

function showToast(msg: string) {
  toast = msg;
  setTimeout(() => (toast = null), 2500);
}

function formatIDR(amount: number): string {
  if (!amount) return "Rp 0";
  return `Rp ${(amount / 1000).toFixed(0)}K`;
}

async function loadBooking() {
  if (!authStore.firebaseUser) return;
  isLoading = true;
  try {
    const token = await authStore.firebaseUser.getIdToken();
    if (!token) return;

    const res = await api.bookings({ id: bookingId }).get({
      headers: { authorization: `Bearer ${token}` },
    });
    if (res.data) {
      booking = res.data;
    }
  } catch (e) {
    console.warn("Booking detail fetch error:", e);
  } finally {
    isLoading = false;
  }
}

async function submitReview() {
  if (isSubmittingReview || reviewRating < 1) return;
  isSubmittingReview = true;
  reviewError = null;
  try {
    const token = await authStore.firebaseUser?.getIdToken();
    if (!token) return;

    const res = await api.reviews.post(
      {
        bookingId: bookingId,
        rating: reviewRating,
        comment: reviewComment.trim() || undefined,
      },
      { headers: { authorization: `Bearer ${token}` } },
    );
    if (res.data) {
      reviewSubmitted = true;
      showToast("Thanks for your review!");
    }
  } catch (err: any) {
    reviewError = err.message || "Failed to submit review";
  } finally {
    isSubmittingReview = false;
  }
}

function handleShareInvite() {
  const url = `${window.location.origin}/booking/${bookingId}/invite`;
  navigator.clipboard
    .writeText(url)
    .then(() => {
      showToast("Invite link copied to clipboard");
    })
    .catch(() => {
      showToast(`Share this invite link: ${url}`);
    });
}

$effect(() => {
  if (authStore.isInitialized && authStore.user && authStore.firebaseUser) {
    loadBooking();
  }
});

function getStatusStyle(status: string) {
  switch (status?.toLowerCase()) {
    case "confirmed":
      return "bg-[#E6FA50]/10 text-[#E6FA50]";
    case "pending":
      return "bg-[#50C8C8]/10 text-[#50C8C8]";
    case "completed":
      return "bg-white/[0.04] text-[#F7F7F7]/25";
    case "cancelled":
      return "bg-red-500/10 text-red-400/70";
    default:
      return "bg-white/5 text-[#F7F7F7]/25";
  }
}

function getPaymentStyle(status: string) {
  switch (status?.toLowerCase()) {
    case "paid":
      return "bg-[#E6FA50]/10 text-[#E6FA50]";
    case "pending":
      return "bg-amber-500/10 text-amber-400";
    case "failed":
      return "bg-red-500/10 text-red-400";
    case "refunded":
      return "bg-[#50C8C8]/10 text-[#50C8C8]";
    default:
      return "";
  }
}
</script>

<svelte:head>
  <title>Booking Summary #{bookingId.slice(0, 8)} - Padelhive</title>
</svelte:head>

<div class="min-h-screen pt-28 pb-16 bg-[#06121A]">
  <!-- Back nav -->
  <section class="container pb-6">
    <a
      href="/bookings"
      class="group inline-flex items-center gap-3 text-xs font-medium text-[#F7F7F7]/60 transition-colors hover:text-[#F7F7F7]"
    >
      <div class="flex h-7 w-7 items-center justify-center rounded-lg border border-white/[0.08] bg-white/[0.03] text-[#F7F7F7]/40 transition-all duration-200 group-hover:border-[#E6FA50]/40 group-hover:bg-[#E6FA50]/10 group-hover:text-[#E6FA50]">
        <ArrowLeft class="h-3.5 w-3.5" />
      </div>
      <span>Back to bookings</span>
    </a>
  </section>

  {#if isLoading || !authStore.isInitialized || authStore.isLoading}
    <div class="container pb-8">
      <div class="h-8 w-48 animate-pulse rounded-md bg-white/[0.04]"></div>
      <div class="mt-4 h-4 w-32 animate-pulse rounded-md bg-white/[0.04]"></div>
    </div>
    <div class="container">
      <div class="h-64 animate-pulse rounded-2xl bg-white/[0.02]"></div>
    </div>
  {:else if !booking}
    <div class="container my-8">
      <div class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-12 md:p-16 text-center max-w-xl mx-auto">
        <div class="flex h-12 w-12 items-center justify-center rounded-2xl bg-white/[0.04] text-[#E6FA50] mx-auto mb-4">
          <Ticket class="h-6 w-6" />
        </div>
        <h2 class="heading-2 text-xl font-bold text-[#F7F7F7]">Booking not found</h2>
        <p class="body mt-2 text-[#F7F7F7]/40 leading-relaxed text-sm">
          You don't have access to this reservation, or it does not exist.
        </p>
        <a
          href="/bookings"
          class="btn-lime label inline-flex items-center justify-center gap-2 rounded-full px-6 py-2.5 font-semibold text-sm bg-[#E6FA50] text-[#06121A] hover:bg-[#E6FA50]/90 transition-all mt-6"
        >
          <ArrowLeft class="h-4 w-4" />
          Back to bookings
        </a>
      </div>
    </div>
  {:else}
    {@const venue = booking.venue}
    {@const court = booking.court}
    {@const currentBooking = booking}

    <!-- Header -->
    <section class="container pb-8">
      <div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <div class="flex items-center gap-3 mb-2">
            <span class="caption rounded-full px-2.5 py-0.5 uppercase font-semibold {getStatusStyle(currentBooking.status)}">
              {currentBooking.status?.toLowerCase() || "completed"}
            </span>
            {#if currentBooking.payment}
              <span class="caption rounded-full px-2.5 py-0.5 uppercase font-semibold {getPaymentStyle(currentBooking.payment.status)}">
                {currentBooking.payment.status?.toLowerCase() || "paid"}
              </span>
            {/if}
          </div>
          <h1 class="heading-1 text-[#F7F7F7]">
            {venue?.name ?? "Unknown Venue"}
          </h1>
          <p class="body mt-1 flex items-center gap-2 text-[#F7F7F7]/40">
            <MapPin class="h-3.5 w-3.5" />
            {venue?.city}
          </p>
        </div>
        <div class="relative hidden h-20 w-32 overflow-hidden rounded-xl sm:block border border-white/[0.08]">
          <img
            src={venue?.imageUrl || padelImg(400)}
            alt={venue?.name ?? "Venue image"}
            class="h-full w-full object-cover"
          />
        </div>
      </div>
    </section>

    <!-- Main Content & Sticky Sidebar Grid -->
    <section class="container">
      <div class="grid grid-cols-1 gap-6 lg:grid-cols-3 lg:items-start">
        <!-- Main content (left column) -->
        <div class="lg:col-span-2 space-y-6">
          <!-- Booking Details -->
          <div class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6">
            <p class="section-label mb-4">Booking Information</p>
            <div class="grid grid-cols-2 gap-3 sm:grid-cols-3">
              <div class="rounded-xl bg-white/[0.02] p-3">
                <Ticket class="h-3.5 w-3.5 text-[#50C8C8]" />
                <p class="heading-3 mt-1.5 text-[#F7F7F7] break-all">#{currentBooking.id.slice(-6).toUpperCase()}</p>
                <p class="caption mt-0.5 text-[#F7F7F7]/25">Booking ID</p>
              </div>
              <div class="rounded-xl bg-white/[0.02] p-3">
                <MapPin class="h-3.5 w-3.5 text-[#50C8C8]" />
                <p class="heading-3 mt-1.5 text-[#F7F7F7] break-all">{court?.name ?? "Court A"} · {court?.type ?? "OUTDOOR"}</p>
                <p class="caption mt-0.5 text-[#F7F7F7]/25">Court</p>
              </div>
              <div class="rounded-xl bg-white/[0.02] p-3">
                <CalendarDays class="h-3.5 w-3.5 text-[#50C8C8]" />
                <p class="heading-3 mt-1.5 text-[#F7F7F7] break-all">{formatBookingDate(currentBooking.bookingDate)}</p>
                <p class="caption mt-0.5 text-[#F7F7F7]/25">Date</p>
              </div>
              <div class="rounded-xl bg-white/[0.02] p-3">
                <Clock class="h-3.5 w-3.5 text-[#50C8C8]" />
                <p class="heading-3 mt-1.5 text-[#F7F7F7] break-all">{formatBookingTimeRange(currentBooking.startsAt, currentBooking.endsAt)}</p>
                <p class="caption mt-0.5 text-[#F7F7F7]/25">Time</p>
              </div>
              <div class="rounded-xl bg-white/[0.02] p-3">
                <Timer class="h-3.5 w-3.5 text-[#50C8C8]" />
                <p class="heading-3 mt-1.5 text-[#F7F7F7] break-all">{currentBooking.durationMinutes || 60} min</p>
                <p class="caption mt-0.5 text-[#F7F7F7]/25">Duration</p>
              </div>
            </div>
          </div>

          <!-- Refund Policy -->
          <div class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6">
            <p class="section-label mb-4">Refund Policy</p>
            <div class="grid grid-cols-1 gap-3 sm:grid-cols-2">
              <div class="rounded-xl bg-white/[0.02] p-4">
                <ShieldCheck class="h-4 w-4 text-[#E6FA50]" />
                <p class="heading-3 mt-1.5 text-[#F7F7F7]">Full refund before H-1</p>
                <p class="caption mt-1 text-[#F7F7F7]/25">Cancel 24+ hours before your booking date — the full amount is returned to your original payment method.</p>
              </div>
              <div class="rounded-xl bg-white/[0.02] p-4">
                <ShieldX class="h-4 w-4 text-red-400" />
                <p class="heading-3 mt-1.5 text-[#F7F7F7]">Non-refundable after H-1</p>
                <p class="caption mt-1 text-[#F7F7F7]/25">Cancelling less than 24 hours before the start time isn't eligible for a refund.</p>
              </div>
            </div>
          </div>

          <!-- Leave a Review -->
          {#if currentBooking.status === "COMPLETED" || currentBooking.status === "completed"}
            <div class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6">
              <p class="section-label mb-4">Leave a Review</p>
              {#if reviewSubmitted}
                <div class="rounded-xl border border-[#E6FA50]/15 bg-[#E6FA50]/10 p-4">
                  <p class="body text-[#E6FA50]">{reviewError ?? "Thanks! Your review has been submitted."}</p>
                </div>
              {:else}
                <div class="space-y-4">
                  <div class="flex items-center gap-1.5">
                    {#each [1, 2, 3, 4, 5] as n}
                      <button type="button" onclick={() => (reviewRating = n)} class="transition-transform hover:scale-110">
                        <Star class="h-6 w-6 {n <= reviewRating ? 'fill-[#E6FA50] text-[#E6FA50]' : 'text-[#F7F7F7]/20'}" />
                      </button>
                    {/each}
                  </div>
                  <textarea
                    bind:value={reviewComment}
                    maxLength={1000}
                    rows={4}
                    placeholder="Share your experience (optional)"
                    class="body w-full resize-none rounded-xl border border-white/[0.06] bg-white/[0.02] px-4 py-3 text-[#F7F7F7] placeholder:text-[#F7F7F7]/25 focus:border-[#50C8C8]/40 focus:outline-none"
                  ></textarea>
                  {#if reviewError}
                    <div class="rounded-xl border border-amber-400/20 bg-amber-400/[0.06] px-4 py-3">
                      <p class="caption text-amber-300/80">{reviewError}</p>
                    </div>
                  {/if}
                  <button
                    type="button"
                    onclick={submitReview}
                    disabled={isSubmittingReview || reviewRating < 1}
                    class="label rounded-full bg-[#E6FA50] px-5 py-2.5 text-[#06121A] transition-colors hover:bg-[#E6FA50]/90 disabled:opacity-40"
                  >
                    {isSubmittingReview ? "Submitting..." : "Submit Review"}
                  </button>
                </div>
              {/if}
            </div>
          {/if}
        </div>

        <!-- Summary sidebar (sticky) -->
        <div class="space-y-6 lg:sticky lg:top-24">
          <!-- Payment -->
          <div id="payment" class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6">
            <p class="section-label mb-4">Payment</p>
            <div class="space-y-3 mb-4">
              <div class="flex items-center justify-between">
                <span class="caption text-[#F7F7F7]/40">Court fee</span>
                <span class="price text-[#F7F7F7]/60">Rp {((currentBooking.courtAmount || 300000) / 1000).toFixed(0)}K</span>
              </div>
              {#if currentBooking.voucherDiscount > 0}
                <div class="flex items-center justify-between">
                  <span class="caption text-[#F7F7F7]/40">Voucher</span>
                  <span class="price text-[#E6FA50]">-Rp {(currentBooking.voucherDiscount / 1000).toFixed(0)}K</span>
                </div>
              {/if}
              <div class="flex items-center justify-between">
                <span class="caption text-[#F7F7F7]/40">Platform fee</span>
                <span class="price text-[#F7F7F7]/60">Rp {((currentBooking.platformFee || 15000) / 1000).toFixed(0)}K</span>
              </div>
              <div class="flex items-center justify-between border-t border-white/[0.04] pt-3">
                <span class="body text-[#F7F7F7]/60 font-semibold">Total</span>
                <span class="price text-[#F7F7F7] text-xl font-bold">Rp {((currentBooking.finalAmount || 252000) / 1000).toFixed(0)}K</span>
              </div>
            </div>

            <div class="space-y-2 rounded-xl bg-white/[0.02] p-3">
              <div class="flex items-center justify-between">
                <span class="caption text-[#F7F7F7]/25">Status</span>
                <span class="caption rounded-full px-2.5 py-0.5 {getPaymentStyle(currentBooking.payment?.status || 'pending')}">
                  {currentBooking.payment?.status?.toLowerCase() || "pending"}
                </span>
              </div>
            </div>
          </div>

          <!-- Actions -->
          <div class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6">
            <p class="section-label mb-4">Actions</p>
            <div class="space-y-2">
              <button
                type="button"
                onclick={handleShareInvite}
                class="heading-3 w-full flex items-center gap-3 rounded-xl bg-white/[0.02] px-4 py-3 text-[#F7F7F7]/60 transition-colors hover:bg-white/[0.04] hover:text-[#F7F7F7]"
              >
                <Share2 class="h-4 w-4 text-[#50C8C8]" />
                Share invite link
                <Copy class="ml-auto h-3.5 w-3.5 text-[#F7F7F7]/25" />
              </button>
              <a
                href="/booking/{currentBooking.id}/payment"
                class="heading-3 w-full flex items-center gap-3 rounded-xl bg-white/[0.02] px-4 py-3 text-[#F7F7F7]/60 transition-colors hover:bg-white/[0.04] hover:text-[#F7F7F7]"
              >
                <CreditCard class="h-4 w-4 text-[#50C8C8]" />
                View payment receipt
              </a>
            </div>
          </div>
        </div>
      </div>
    </section>
  {/if}

  <!-- Toast -->
  {#if toast}
    <div class="fixed bottom-6 left-1/2 z-50 -translate-x-1/2 rounded-xl border border-white/[0.06] bg-[#0C1B26] px-5 py-3 shadow-2xl">
      <p class="caption text-[#F7F7F7]/60">{toast}</p>
    </div>
  {/if}
</div>

// apps/web/src/app/(app)/bookings/[id]/page.tsx
"use client";

import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { formatBookingDate, formatBookingTimeRange } from "@/lib/format";
import Image from "next/image";
import { useParams } from "next/navigation";
import Link from "next/link";
import {
  MapPin,
  Clock,
  CalendarDays,
  Timer,
  Users,
  CreditCard,
  Share2,
  XCircle,
  CheckCircle2,
  ShieldCheck,
  ShieldX,
  Ticket,
  ArrowLeft,
  Copy,
  Star,
} from "lucide-react";
import { ApiRequestError, cancelBooking, getBookingById, createReview } from "@/lib/api";
import { queryKeys } from "@/lib/queries";
import { getUserFacingErrorMessage } from "@/lib/errors";
import { padelImg } from "@/lib/images";
import { ErrorBanner } from "@/components/ui/error-state";

export default function BookingDetailPage() {
  const params = useParams();
  const bookingId = params.id as string;
  const [toast, setToast] = useState<string | null>(null);
  const [isCancelled, setIsCancelled] = useState(false);
  const [showCancelModal, setShowCancelModal] = useState(false);
  const [isCancelling, setIsCancelling] = useState(false);
  const [refundMessage, setRefundMessage] = useState<string | null>(null);

  const [reviewRating, setReviewRating] = useState(0);
  const [reviewComment, setReviewComment] = useState("");
  const [isSubmittingReview, setIsSubmittingReview] = useState(false);
  const [reviewError, setReviewError] = useState<string | null>(null);
  const [reviewSubmitted, setReviewSubmitted] = useState(false);

  const { data: booking, isLoading, error, refetch, isFetching } = useQuery({
    queryKey: queryKeys.bookings.detail(bookingId),
    queryFn: () => getBookingById(bookingId),
  });

  if (isLoading) {
    return (
      <div className="min-h-screen pt-28 pb-16">
        <div className="container pb-8">
          <div className="h-8 w-48 animate-pulse rounded-md bg-white/[0.04]"></div>
          <div className="mt-4 h-4 w-32 animate-pulse rounded-md bg-white/[0.04]"></div>
        </div>
        <div className="container">
          <div className="h-64 animate-pulse rounded-2xl bg-white/[0.02]"></div>
        </div>
      </div>
    );
  }

  if (error) {
    if (error instanceof ApiRequestError && error.status === 404) {
      return (
        <div className="min-h-screen pt-28">
          <div className="container py-16 text-center">
            <p className="text-sm text-[#F7F7F7]/25">Booking not found.</p>
            <Link href="/bookings" className="mt-4 inline-flex items-center gap-2 text-sm text-[#E6FA50] hover:underline">
              <ArrowLeft className="h-3.5 w-3.5" /> Back to bookings
            </Link>
          </div>
        </div>
      );
    }
    return (
      <div className="min-h-screen pt-28 pb-16">
        <section className="container pb-6">
          <Link href="/bookings" className="inline-flex items-center gap-2 text-sm text-[#F7F7F7]/25 transition-colors hover:text-[#F7F7F7]/60">
            <ArrowLeft className="h-3.5 w-3.5" /> Back to bookings
          </Link>
        </section>
        <section className="container">
          <ErrorBanner title="Couldn't load booking" error={error} onRetry={() => refetch()} isRetrying={isFetching} />
        </section>
      </div>
    );
  }

  if (!booking) {
    return null;
  }

  const currentBooking = booking;
  const venue = booking.venue;
  const court = booking.court;

  function showToast(msg: string) {
    setToast(msg);
    setTimeout(() => setToast(null), 2500);
  }

  function handleShareInvite() {
    const url = `${window.location.origin}/booking/${bookingId}/invite`;
    navigator.clipboard.writeText(url).then(() => {
      showToast("Invite link copied to clipboard");
    }).catch(() => {
      showToast(`Share this invite link: ${url}`);
    });
  }

  function getBookingStart(): Date {
    return new Date(currentBooking.startsAt);
  }

  function getRefundNote(): string {
    const isEligible = getBookingStart().getTime() - Date.now() >= 24 * 60 * 60 * 1000;
    if (isEligible && currentBooking.payment?.status === "PAID") {
      return "Full refund eligible. A pending refund request will be created after cancellation.";
    }
    if (isEligible) {
      return "Full refund eligible, but no paid payment exists for this booking.";
    }
    return "Non-refundable: less than 24 hours before booking start.";
  }

  function getSuccessMessage(result: { isRefundEligible?: boolean; refundAmount?: number; refundPolicyReason?: string }): string {
    if (result.isRefundEligible && result.refundAmount && result.refundAmount > 0) {
      return `Booking cancelled. Pending refund: Rp ${result.refundAmount.toLocaleString("id-ID")}.`;
    }
    return `Booking cancelled. ${result.refundPolicyReason ?? "No refund record needed."}`;
  }

  function handleCancel() {
    setShowCancelModal(true);
  }

  async function confirmCancel() {
    if (isCancelling) return;

    setIsCancelling(true);

    try {
      const result = await cancelBooking(bookingId);
      setIsCancelled(true);
      setShowCancelModal(false);
      const message = getSuccessMessage(result);
      setRefundMessage(message);
      showToast(message);
    } catch (error) {
      if (error instanceof ApiRequestError) {
        if (error.status === 404) {
          showToast("Booking was not found for this account.");
        } else if (error.status === 400) {
          showToast(getUserFacingErrorMessage(error) || "This booking cannot be cancelled.");
        } else {
          showToast(getUserFacingErrorMessage(error));
        }
      } else {
        showToast(getUserFacingErrorMessage(error));
      }
    } finally {
      setIsCancelling(false);
    }
  }

  async function submitReview() {
    if (isSubmittingReview || reviewRating < 1) return;
    setIsSubmittingReview(true);
    setReviewError(null);
    try {
      await createReview({ bookingId, rating: reviewRating, comment: reviewComment.trim() || undefined });
      setReviewSubmitted(true);
      showToast("Thanks for your review!");
    } catch (error) {
      if (error instanceof ApiRequestError && error.status === 409) {
        setReviewSubmitted(true);
        setReviewError("You've already reviewed this booking.");
      } else {
        setReviewError(getUserFacingErrorMessage(error));
      }
    } finally {
      setIsSubmittingReview(false);
    }
  }

  return (
    <div className="min-h-screen pt-28 pb-16">
      {/* Back nav */}
      <section className="container pb-6">
        <Link href="/bookings" className="inline-flex items-center gap-2 text-sm text-[#F7F7F7]/25 transition-colors hover:text-[#F7F7F7]/60">
          <ArrowLeft className="h-3.5 w-3.5" /> Back to bookings
        </Link>
      </section>

      {/* Header */}
      <section className="container pb-8">
        <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <div className="flex items-center gap-3 mb-2">
              <StatusBadge status={isCancelled ? "cancelled" : currentBooking.status.toLowerCase()} />
              {currentBooking.payment && <PaymentBadge status={isCancelled ? "refunded" : currentBooking.payment.status.toLowerCase()} />}
            </div>
            <h1 className="heading-1 text-2xl text-[#F7F7F7] md:text-3xl">
              {venue?.name ?? "Unknown Venue"}
            </h1>
            <p className="mt-1 flex items-center gap-2 text-sm text-[#F7F7F7]/40">
              <MapPin className="h-3.5 w-3.5" />
              {venue?.city}
            </p>
          </div>
          <div className="relative hidden h-20 w-32 overflow-hidden rounded-xl sm:block">
            <Image
              src={padelImg(400)}
              alt={venue?.name ?? "Venue image"}
              fill
              sizes="128px"
              className="object-cover"
            />
          </div>
        </div>
      </section>

      <section className="container">
        <div className="grid grid-cols-1 gap-6 lg:grid-cols-3 lg:items-start">
          {/* Main content */}
          <div className="lg:col-span-2 space-y-6">
            {/* Booking Details */}
            <div className="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6">
              <p className="section-label mb-4">Booking Information</p>
              <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">
                <div className="rounded-xl bg-white/[0.02] p-3">
                  <Ticket className="h-3.5 w-3.5 text-[#50C8C8]" />
                  <p className="heading-3 mt-1.5 text-[13px] text-[#F7F7F7] break-all">{`#${currentBooking.id.slice(-6).toUpperCase()}`}</p>
                  <p className="caption mt-0.5 text-[#F7F7F7]/25">Booking ID</p>
                </div>
                <div className="rounded-xl bg-white/[0.02] p-3">
                  <MapPin className="h-3.5 w-3.5 text-[#50C8C8]" />
                  <p className="heading-3 mt-1.5 text-[13px] text-[#F7F7F7] break-all">{`${court?.name ?? "—"} · ${court?.type ?? ""}`}</p>
                  <p className="caption mt-0.5 text-[#F7F7F7]/25">Court</p>
                </div>
                <div className="rounded-xl bg-white/[0.02] p-3">
                  <CalendarDays className="h-3.5 w-3.5 text-[#50C8C8]" />
                  <p className="heading-3 mt-1.5 text-[13px] text-[#F7F7F7] break-all">{formatBookingDate(currentBooking.bookingDate)}</p>
                  <p className="caption mt-0.5 text-[#F7F7F7]/25">Date</p>
                </div>
                <div className="rounded-xl bg-white/[0.02] p-3">
                  <Clock className="h-3.5 w-3.5 text-[#50C8C8]" />
                  <p className="heading-3 mt-1.5 text-[13px] text-[#F7F7F7] break-all">{formatBookingTimeRange(currentBooking.startsAt, currentBooking.endsAt)}</p>
                  <p className="caption mt-0.5 text-[#F7F7F7]/25">Time</p>
                </div>
                <div className="rounded-xl bg-white/[0.02] p-3">
                  <Timer className="h-3.5 w-3.5 text-[#50C8C8]" />
                  <p className="heading-3 mt-1.5 text-[13px] text-[#F7F7F7] break-all">{`${currentBooking.durationMinutes} min`}</p>
                  <p className="caption mt-0.5 text-[#F7F7F7]/25">Duration</p>
                </div>
              </div>
            </div>

            {/* Refund Policy */}
            <div className="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6">
              <p className="section-label mb-4">Refund Policy</p>
              <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
                <div className="rounded-xl bg-white/[0.02] p-4">
                  <ShieldCheck className="h-4 w-4 text-[#E6FA50]" />
                  <p className="heading-3 mt-1.5 text-[13px] text-[#F7F7F7]">Full refund before H-1</p>
                  <p className="caption mt-1 text-[#F7F7F7]/25">Cancel 24+ hours before your booking date — the full amount is returned to your original payment method.</p>
                </div>
                <div className="rounded-xl bg-white/[0.02] p-4">
                  <ShieldX className="h-4 w-4 text-red-400" />
                  <p className="heading-3 mt-1.5 text-[13px] text-[#F7F7F7]">Non-refundable after H-1</p>
                  <p className="caption mt-1 text-[#F7F7F7]/25">Cancelling less than 24 hours before the start time isn&apos;t eligible for a refund.</p>
                </div>
              </div>
            </div>

            {currentBooking.status === "COMPLETED" && (
              <div className="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6">
                <p className="section-label mb-4">Leave a Review</p>
                {reviewSubmitted ? (
                  <div className="rounded-xl border border-[#E6FA50]/15 bg-[#E6FA50]/10 p-4">
                    <p className="text-sm text-[#E6FA50]">{reviewError ?? "Thanks! Your review has been submitted."}</p>
                  </div>
                ) : (
                  <div className="space-y-4">
                    <div className="flex items-center gap-1.5">
                      {[1, 2, 3, 4, 5].map((n) => (
                        <button key={n} type="button" onClick={() => setReviewRating(n)} className="transition-transform hover:scale-110">
                          <Star className={`h-6 w-6 ${n <= reviewRating ? "fill-[#E6FA50] text-[#E6FA50]" : "text-[#F7F7F7]/20"}`} />
                        </button>
                      ))}
                    </div>
                    <textarea
                      value={reviewComment}
                      onChange={(e) => setReviewComment(e.target.value)}
                      maxLength={1000}
                      rows={4}
                      placeholder="Share your experience (optional)"
                      className="w-full resize-none rounded-xl border border-white/[0.06] bg-white/[0.02] px-4 py-3 text-sm text-[#F7F7F7] placeholder:text-[#F7F7F7]/25 focus:border-[#50C8C8]/40 focus:outline-none"
                    />
                    {reviewError && (
                      <div className="rounded-xl border border-amber-400/20 bg-amber-400/[0.06] px-4 py-3">
                        <p className="text-xs text-amber-300/80">{reviewError}</p>
                      </div>
                    )}
                    <button
                      onClick={submitReview}
                      disabled={isSubmittingReview || reviewRating < 1}
                      className="rounded-full bg-[#E6FA50] px-5 py-2.5 text-[11px] font-semibold uppercase tracking-[0.08em] text-[#06121A] transition-colors hover:bg-[#E6FA50]/90 disabled:opacity-40"
                    >
                      {isSubmittingReview ? "Submitting..." : "Submit Review"}
                    </button>
                  </div>
                )}
              </div>
            )}
          </div>

          {/* Summary sidebar (sticky) */}
          <div className="space-y-6 lg:sticky lg:top-24">
            {/* Payment */}
            <div id="payment" className="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6">
              <p className="section-label mb-4">Payment</p>
              <div className="space-y-3 mb-4">
                <PaymentRow label="Court fee" value={`Rp ${(currentBooking.courtAmount / 1000).toFixed(0)}K`} />
                {currentBooking.voucherDiscount > 0 && (
                  <PaymentRow
                    label="Voucher"
                    value={`-Rp ${(currentBooking.voucherDiscount / 1000).toFixed(0)}K`}
                    highlight
                  />
                )}
                <PaymentRow label="Platform fee" value={`Rp ${(currentBooking.platformFee / 1000).toFixed(0)}K`} />
                <div className="flex items-center justify-between border-t border-white/[0.04] pt-3">
                  <span className="text-sm font-medium text-[#F7F7F7]/60">Total</span>
                  <span className="price text-lg text-[#F7F7F7]">{`Rp ${(currentBooking.finalAmount / 1000).toFixed(0)}K`}</span>
                </div>
              </div>

              <div className="space-y-2 rounded-xl bg-white/[0.02] p-3">
                <div className="flex items-center justify-between">
                  <span className="caption text-[#F7F7F7]/25">Status</span>
                  <PaymentBadge status={isCancelled ? "refunded" : (currentBooking.payment?.status.toLowerCase() ?? "pending")} />
                </div>
                {refundMessage && (
                  <div className="rounded-xl border border-[#E6FA50]/15 bg-[#E6FA50]/10 p-3">
                    <p className="text-xs leading-5 text-[#E6FA50]">{refundMessage}</p>
                  </div>
                )}
              </div>
            </div>

            {/* Actions */}
            <div className="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6">
              <p className="section-label mb-4">Actions</p>
              <div className="space-y-2">
                <button
                  onClick={handleShareInvite}
                  className="w-full flex items-center gap-3 rounded-xl bg-white/[0.02] px-4 py-3 heading-3 text-[13px] text-[#F7F7F7]/60 transition-colors hover:bg-white/[0.04] hover:text-[#F7F7F7]"
                >
                  <Share2 className="h-4 w-4 text-[#50C8C8]" />
                  Share invite link
                  <Copy className="ml-auto h-3.5 w-3.5 text-[#F7F7F7]/25" />
                </button>
                <Link
                  href={`/booking/${currentBooking.id}/payment`}
                  className="w-full flex items-center gap-3 rounded-xl bg-white/[0.02] px-4 py-3 heading-3 text-[13px] text-[#F7F7F7]/60 transition-colors hover:bg-white/[0.04] hover:text-[#F7F7F7]"
                >
                  <CreditCard className="h-4 w-4 text-[#50C8C8]" />
                  View payment receipt
                </Link>
                {currentBooking.status === "CONFIRMED" && !isCancelled && (
                  <>
                    <div className="my-1 border-t border-white/[0.04]" />
                    <button
                      onClick={handleCancel}
                      className="w-full flex items-center gap-3 rounded-xl bg-red-500/5 px-4 py-3 heading-3 text-[13px] text-red-400/70 transition-colors hover:bg-red-500/10 hover:text-red-400"
                    >
                      <XCircle className="h-4 w-4" />
                      Cancel booking
                    </button>
                  </>
                )}
              </div>
            </div>
          </div>
        </div>
      </section>

      {showCancelModal && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 px-4">
          <div className="w-full max-w-md rounded-2xl border border-white/[0.08] bg-[#0C1B26] p-6 shadow-2xl">
            <p className="section-label">Cancel Booking</p>
            <h2 className="heading-2 mt-3 text-xl text-[#F7F7F7]">Cancel this booking?</h2>
            <p className="mt-2 text-sm leading-6 text-[#F7F7F7]/40">
              This will cancel your booking and release the court time.
            </p>
            <div className="mt-4 rounded-xl border border-white/[0.06] bg-white/[0.03] p-4">
              <p className="text-sm font-medium text-[#F7F7F7]/60">Refund eligibility</p>
              <p className="mt-1 text-xs leading-5 text-[#F7F7F7]/40">{getRefundNote()}</p>
            </div>
            <div className="mt-6 flex flex-col gap-3 sm:flex-row sm:justify-end">
              <button
                onClick={() => setShowCancelModal(false)}
                disabled={isCancelling}
                className="rounded-full border border-white/[0.08] px-5 py-2.5 text-[11px] font-medium uppercase tracking-[0.08em] text-[#F7F7F7]/60 transition-colors hover:border-white/[0.15] hover:text-[#F7F7F7]/80 disabled:opacity-40"
              >
                Keep Booking
              </button>
              <button
                onClick={confirmCancel}
                disabled={isCancelling}
                className="rounded-full bg-red-500/15 px-5 py-2.5 text-[11px] font-semibold uppercase tracking-[0.08em] text-red-300 transition-colors hover:bg-red-500/25 disabled:opacity-40"
              >
                {isCancelling ? "Cancelling..." : "Cancel Booking"}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Toast */}
      {toast && (
        <div className="fixed bottom-6 left-1/2 z-50 -translate-x-1/2 rounded-xl border border-white/[0.06] bg-[#0C1B26] px-5 py-3 shadow-2xl">
          <p className="caption text-[#F7F7F7]/60">{toast}</p>
        </div>
      )}
    </div>
  );
}





function PaymentRow({ label, value, highlight, bold }: { label: string; value: string; highlight?: boolean; bold?: boolean }) {
  return (
    <div className="flex items-center justify-between">
      <span className={`caption ${bold ? "text-[#F7F7F7]/60" : "text-[#F7F7F7]/40"}`}>{label}</span>
      <span className={`heading-3 text-[13px] ${highlight ? "text-[#E6FA50]" : bold ? "text-[#F7F7F7]" : "text-[#F7F7F7]/60"}`}>{value}</span>
    </div>
  );
}

function StatusBadge({ status }: { status: string }) {
  const styles: Record<string, string> = {
    confirmed: "bg-[#E6FA50]/10 text-[#E6FA50]",
    pending: "bg-[#50C8C8]/10 text-[#50C8C8]",
    completed: "bg-white/[0.04] text-[#F7F7F7]/25",
    cancelled: "bg-red-500/10 text-red-400/70",
  };
  return (
    <span className={`rounded-full px-2.5 py-0.5 text-[10px] font-medium uppercase tracking-[0.1em] ${styles[status] ?? "bg-white/5 text-[#F7F7F7]/25"}`}>
      {status}
    </span>
  );
}

function PaymentBadge({ status }: { status: string }) {
  const styles: Record<string, string> = {
    paid: "bg-[#E6FA50]/10 text-[#E6FA50]",
    pending: "bg-amber-500/10 text-amber-400",
    failed: "bg-red-500/10 text-red-400",
    refunded: "bg-[#50C8C8]/10 text-[#50C8C8]",
  };
  return (
    <span className={`rounded-full px-2.5 py-0.5 text-[10px] font-medium uppercase tracking-[0.1em] ${styles[status] ?? ""}`}>
      {status}
    </span>
  );
}
