// apps/web/src/app/dashboard/page.tsx
"use client";

import { useQuery } from "@tanstack/react-query";
import {
  ArrowRight,
  Building2,
  CalendarDays,
  Clock,
  DollarSign,
  Plus,
  Tag,
  TrendingUp,
} from "lucide-react";
import Link from "next/link";
import { ErrorBanner } from "@/components/ui/error-state";
import { getOwnerDashboard } from "@/lib/api";
import { queryKeys } from "@/lib/queries";
import { useAuthStore } from "@/stores/auth-store";

export default function DashboardPage() {
  const user = useAuthStore((s) => s.user);
  const { data, isLoading, isError, error, refetch, isFetching } = useQuery({
    queryKey: queryKeys.dashboard.owner(),
    queryFn: getOwnerDashboard,
  });

  if (isLoading) {
    const firstName = user?.name?.split(" ")[0] ?? "there";
    return (
      <div className="pt-element pb-component">
        {/* WELCOME */}
        <section className="container pb-component">
          <p className="caption text-[#F7F7F7]/25">Good morning</p>
          <h1 className="heading-1 mt-2 text-[#F7F7F7]">
            Welcome back, <span className="text-[#E6FA50]">{firstName}</span>
          </h1>
          <div className="mt-3 h-5 w-48 animate-pulse rounded-md bg-white/[0.04]" />
        </section>

        {/* KPIs */}
        <section className="container pb-component">
          <div className="grid grid-cols-2 gap-4 lg:grid-cols-5">
            {[...Array(5)].map((_, i) => (
              <div
                key={i}
                className="h-[120px] animate-pulse rounded-2xl border border-white/[0.06] bg-[#0C1B26]"
              />
            ))}
          </div>
        </section>

        {/* REVENUE + UTILIZATION */}
        <section className="container pb-component">
          <div className="grid grid-cols-1 gap-5 lg:grid-cols-[2fr_1fr]">
            <div className="h-[300px] animate-pulse rounded-2xl border border-white/[0.06] bg-[#0C1B26]" />
            <div className="h-[300px] animate-pulse rounded-2xl border border-white/[0.06] bg-[#0C1B26]" />
          </div>
        </section>

        {/* TODAY'S SCHEDULE */}
        <section className="container pb-component">
          <div className="h-[250px] animate-pulse rounded-2xl border border-white/[0.06] bg-[#0C1B26]" />
        </section>

        {/* RECENT BOOKINGS */}
        <section className="container pb-component">
          <div className="h-[250px] animate-pulse rounded-2xl border border-white/[0.06] bg-[#0C1B26]" />
        </section>

        {/* QUICK ACTIONS */}
        <section className="container pb-component">
          <div className="mb-5 h-5 w-24 animate-pulse rounded-md bg-white/[0.04]" />
          <div className="grid grid-cols-2 gap-4 md:grid-cols-4">
            {[...Array(4)].map((_, i) => (
              <div
                key={i}
                className="h-[104px] animate-pulse rounded-2xl border border-white/[0.06] bg-[#0C1B26]"
              />
            ))}
          </div>
        </section>
      </div>
    );
  }

  if (isError || !data) {
    const firstName = user?.name?.split(" ")[0] ?? "there";
    return (
      <div className="pt-element pb-component container">
        <p className="caption text-[#F7F7F7]/25">Good morning</p>
        <h1 className="heading-1 mt-2 text-[#F7F7F7]">
          Welcome back, <span className="text-[#E6FA50]">{firstName}</span>
        </h1>
        <div className="mt-8">
          <ErrorBanner
            title="Couldn't load your dashboard"
            error={error}
            onRetry={() => refetch()}
            isRetrying={isFetching}
          />
        </div>
      </div>
    );
  }

  const {
    kpis,
    revenueSeries,
    courtUtilization,
    todaysSchedule,
    recentBookings,
  } = data;

  const maxRevenue = Math.max(...revenueSeries.map((d) => d.value), 1);
  const firstName = user?.name?.split(" ")[0] ?? "there";

  return (
    <div className="pt-element pb-component">
      {/* ─── WELCOME ─── */}
      <section className="container pb-component">
        <p className="caption text-[#F7F7F7]/25">Good morning</p>
        <h1 className="heading-1 mt-2 text-[#F7F7F7]">
          Welcome back, <span className="text-[#E6FA50]">{firstName}</span>
        </h1>
        <p className="body mt-3 text-[#F7F7F7]/40">
          Your venues generated{" "}
          <span className="price text-[#50C8C8]">
            Rp {(kpis.weeklyRevenue / 1000).toFixed(0)}K
          </span>{" "}
          this week.
        </p>
      </section>

      {/* ─── KPIs ─── */}
      <section className="container pb-component">
        <div className="grid grid-cols-2 gap-4 lg:grid-cols-5">
          <KPICard
            icon={DollarSign}
            label="Revenue"
            value={`Rp ${(kpis.weeklyRevenue / 1000).toFixed(0)}K`}
          />
          <KPICard
            icon={CalendarDays}
            label="Bookings"
            value={kpis.weeklyBookings.toString()}
          />
          <KPICard
            icon={TrendingUp}
            label="Occupancy"
            value={`${kpis.occupancyRate}%`}
          />
          <KPICard
            icon={Building2}
            label="Active Courts"
            value={kpis.activeCourts.toString()}
          />
          <KPICard
            icon={Clock}
            label="Pending Payments"
            value={kpis.pendingPayments.toString()}
            highlight
          />
        </div>
      </section>

      {/* ─── REVENUE + UTILIZATION ─── */}
      <section className="container pb-component">
        <div className="grid grid-cols-1 gap-5 lg:grid-cols-[2fr_1fr]">
          {/* Revenue chart */}
          <div className="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-8">
            <div className="flex items-start justify-between">
              <div>
                <p className="section-label">Revenue This Week</p>
                <p className="metric mt-3 text-[#F7F7F7]">
                  Rp {(kpis.weeklyRevenue / 1000).toFixed(0)}K
                </p>
              </div>
              <div className="flex gap-1">
                <button className="label rounded-lg bg-[#E6FA50]/10 px-3 py-1.5 text-[#E6FA50]">
                  Weekly
                </button>
                <button className="label rounded-lg bg-white/[0.03] px-3 py-1.5 text-[#F7F7F7]/25">
                  Monthly
                </button>
              </div>
            </div>

            <div className="mt-10 flex h-40 items-end gap-2">
              {revenueSeries.map((d, i) => (
                <div
                  key={i}
                  className="flex flex-1 flex-col items-center gap-2"
                >
                  <div
                    className="w-full rounded-md bg-[#E6FA50]/15 transition-colors duration-200 hover:bg-[#E6FA50]/30"
                    style={{ height: `${(d.value / maxRevenue) * 140}px` }}
                  />
                  <span className="caption text-[#F7F7F7]/25">{d.label}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Court utilization */}
          <div className="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-8">
            <p className="section-label">Court Utilization</p>

            <div className="mt-8 space-y-5">
              {courtUtilization.slice(0, 5).map((court, i) => (
                <CourtBar
                  key={i}
                  name={court.name}
                  percentage={court.occupancyRate}
                />
              ))}
              {courtUtilization.length === 0 && (
                <p className="body text-[#F7F7F7]/40">No active courts.</p>
              )}
            </div>

            <div className="mt-8 border-t border-white/[0.04] pt-5">
              <p className="caption text-[#F7F7F7]/25">Average occupancy</p>
              <p className="metric mt-1 text-[#E6FA50]">
                {kpis.occupancyRate}%
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* ─── TODAY'S SCHEDULE ─── */}
      <section className="container pb-component">
        <div className="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-8">
          <div className="flex items-center justify-between mb-6">
            <p className="section-label">Today&apos;s Schedule</p>
            <span className="caption text-[#F7F7F7]/25">
              {todaysSchedule.length} bookings
            </span>
          </div>

          <div className="space-y-0">
            {todaysSchedule.length === 0 ? (
              <p className="body text-[#F7F7F7]/40">No bookings today.</p>
            ) : (
              todaysSchedule.map((slot, i) => {
                const isConfirmed = slot.status === "CONFIRMED";
                return (
                  <div
                    key={i}
                    className="flex items-center gap-5 border-b border-white/[0.03] py-3.5 last:border-0"
                  >
                    <span className="metric w-12 shrink-0 text-[#F7F7F7]/40">
                      {slot.time}
                    </span>
                    <div
                      className={`h-2.5 w-2.5 shrink-0 rounded-full ${isConfirmed ? "bg-[#E6FA50]" : "border-2 border-[#50C8C8] bg-transparent"}`}
                    />
                    <div className="flex-1">
                      <p className="heading-3 text-[#F7F7F7]">{slot.player}</p>
                      <p className="caption text-[#F7F7F7]/25">{slot.court}</p>
                    </div>
                    <span
                      className={`caption rounded-full px-2 py-0.5 uppercase ${isConfirmed ? "bg-[#E6FA50]/10 text-[#E6FA50]" : "bg-[#50C8C8]/10 text-[#50C8C8]"}`}
                    >
                      {slot.status.replace(/_/g, " ")}
                    </span>
                  </div>
                );
              })
            )}
          </div>
        </div>
      </section>

      {/* ─── RECENT BOOKINGS ─── */}
      <section className="container pb-component">
        <div className="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-8">
          <div className="flex items-center justify-between mb-6">
            <p className="section-label">Recent Bookings</p>
            <Link
              href="/dashboard/bookings"
              className="group flex items-center gap-1 caption text-[#F7F7F7]/25 transition-colors hover:text-[#E6FA50]"
            >
              View all{" "}
              <ArrowRight className="h-3 w-3 transition-transform group-hover:translate-x-0.5" />
            </Link>
          </div>

          <div className="space-y-2">
            {recentBookings.length === 0 ? (
              <p className="body text-[#F7F7F7]/40">No recent bookings.</p>
            ) : (
              recentBookings.map((booking) => {
                const isConfirmed = booking.status === "CONFIRMED";
                const isPending = booking.status === "PENDING_PAYMENT";
                return (
                  <div
                    key={booking.id}
                    className="flex items-center gap-4 rounded-lg bg-white/[0.02] p-3.5 transition-colors hover:bg-white/[0.04]"
                  >
                    <div className="flex-1 min-w-0">
                      <p className="heading-3 truncate text-[#F7F7F7]">
                        {booking.venueName}
                      </p>
                      <p className="caption mt-0.5 text-[#F7F7F7]/25">
                        {booking.courtName} · {booking.bookingDate} ·{" "}
                        {booking.time}
                      </p>
                    </div>
                    <p className="price shrink-0 text-[#F7F7F7]/60">
                      Rp {(booking.finalAmount / 1000).toFixed(0)}K
                    </p>
                    <div
                      className={`h-2 w-2 shrink-0 rounded-full ${isConfirmed ? "bg-[#E6FA50]" : isPending ? "bg-[#50C8C8]" : "bg-[#F7F7F7]/25"}`}
                    />
                  </div>
                );
              })
            )}
          </div>
        </div>
      </section>

      {/* ─── QUICK ACTIONS ─── */}
      <section className="container pb-component">
        <p className="section-label mb-5">Quick Actions</p>
        <div className="grid grid-cols-2 gap-4 md:grid-cols-4">
          <QuickAction icon={Plus} label="Add Court" href="/dashboard/courts" />
          <QuickAction
            icon={Tag}
            label="Create Promo"
            href="/dashboard/revenue"
          />
          <QuickAction
            icon={CalendarDays}
            label="Manage Schedule"
            href="/dashboard/hours"
          />
          <QuickAction
            icon={Building2}
            label="View Venues"
            href="/dashboard/venues"
          />
        </div>
      </section>
    </div>
  );
}

function KPICard({
  icon: Icon,
  label,
  value,
  highlight,
}: {
  icon: React.ComponentType<{ className?: string }>;
  label: string;
  value: string;
  highlight?: boolean;
}) {
  return (
    <div
      className={`rounded-2xl border p-6 ${highlight ? "border-[#50C8C8]/20 bg-[#50C8C8]/5" : "border-white/[0.06] bg-[#0C1B26]"}`}
    >
      <div className="flex items-center justify-between">
        <Icon className="h-4 w-4 text-[#50C8C8]" />
      </div>
      <p className="metric mt-3 text-[#F7F7F7]">{value}</p>
      <p className="caption mt-1 text-[#F7F7F7]/25">{label}</p>
    </div>
  );
}

function CourtBar({ name, percentage }: { name: string; percentage: number }) {
  return (
    <div>
      <div className="flex items-center justify-between mb-1.5">
        <span className="label text-[#F7F7F7]/40">{name}</span>
        <span className="metric text-[#E6FA50]">{percentage}%</span>
      </div>
      <div className="h-1.5 w-full overflow-hidden rounded-full bg-white/[0.04]">
        <div
          className="h-full rounded-full bg-[#E6FA50]/70"
          style={{ width: `${percentage}%` }}
        />
      </div>
    </div>
  );
}

function QuickAction({
  icon: Icon,
  label,
  href,
}: {
  icon: React.ComponentType<{ className?: string }>;
  label: string;
  href: string;
}) {
  return (
    <Link
      href={href}
      className="flex flex-col items-center gap-3 rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6 transition-all duration-200 hover:border-[#E6FA50]/20 hover:bg-[#E6FA50]/5"
    >
      <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-[#E6FA50]/10">
        <Icon className="h-4 w-4 text-[#E6FA50]" />
      </div>
      <span className="caption text-[#F7F7F7]/40">{label}</span>
    </Link>
  );
}

// apps/web/src/routes/dashboard/+page.svelte
<script lang="ts">
import {
  ArrowRight,
  Building2,
  CalendarDays,
  Clock,
  DollarSign,
  Plus,
  Tag,
  TrendingUp,
} from "lucide-svelte";
import { api } from "$lib/api/client";
import { authStore } from "$lib/auth/store.svelte";

let data = $state<any | null>(null);
let isLoading = $state(true);
let isError = $state(false);

const user = $derived(authStore.user);
const firstName = $derived(user?.name?.split(" ")[0] ?? "there");

async function loadDashboard() {
  if (!authStore.firebaseUser) return;
  isLoading = true;
  isError = false;
  try {
    const token = await authStore.firebaseUser.getIdToken();
    if (!token) return;

    const res = await api.bookings["owner-dashboard"].get({
      headers: { authorization: `Bearer ${token}` },
    });
    if (res.data) {
      data = res.data;
    }
  } catch (e) {
    console.warn("Owner dashboard error:", e);
    isError = true;
  } finally {
    isLoading = false;
  }
}

$effect(() => {
  if (authStore.isInitialized && authStore.user && authStore.firebaseUser) {
    loadDashboard();
  }
});

const maxRevenue = $derived(
  data?.revenueSeries
    ? Math.max(...data.revenueSeries.map((d: any) => d.value), 1)
    : 1,
);
</script>

<svelte:head>
  <title>Owner Dashboard - Padelhive</title>
</svelte:head>

<div class="pt-element pb-component">
  <!-- WELCOME -->
  <section class="container pb-component pt-8">
    <p class="caption text-[#F7F7F7]/25">Good morning</p>
    <h1 class="heading-1 mt-2 text-[#F7F7F7]">
      Welcome back, <span class="text-[#E6FA50]">{firstName}</span>
    </h1>
    {#if data && data.kpis}
      <p class="body mt-3 text-[#F7F7F7]/40">
        Your venues generated{" "}
        <span class="price text-[#50C8C8]">
          Rp {((data.kpis.weeklyRevenue || 0) / 1000).toFixed(0)}K
        </span>{" "}
        this week.
      </p>
    {/if}
  </section>

  {#if isLoading || !authStore.isInitialized || authStore.isLoading}
    <!-- Full 1:1 Owner Skeleton UI -->
    <!-- KPIs Skeleton -->
    <section class="container pb-component">
      <div class="grid grid-cols-2 gap-4 lg:grid-cols-5">
        {#each Array.from({ length: 5 }) as _, i}
          <div
            class="h-[120px] animate-pulse rounded-2xl border border-white/[0.06] bg-[#0C1B26]"
          ></div>
        {/each}
      </div>
    </section>

    <!-- Revenue + Utilization Skeleton -->
    <section class="container pb-component">
      <div class="grid grid-cols-1 gap-5 lg:grid-cols-[2fr_1fr]">
        <div class="h-[300px] animate-pulse rounded-2xl border border-white/[0.06] bg-[#0C1B26]"></div>
        <div class="h-[300px] animate-pulse rounded-2xl border border-white/[0.06] bg-[#0C1B26]"></div>
      </div>
    </section>

    <!-- Today's Schedule Skeleton -->
    <section class="container pb-component">
      <div class="h-[200px] animate-pulse rounded-2xl border border-white/[0.06] bg-[#0C1B26]"></div>
    </section>

    <!-- Recent Bookings Skeleton -->
    <section class="container pb-component">
      <div class="h-[250px] animate-pulse rounded-2xl border border-white/[0.06] bg-[#0C1B26]"></div>
    </section>

    <!-- Quick Actions Skeleton -->
    <section class="container pb-component">
      <div class="mb-5 h-5 w-24 animate-pulse rounded-md bg-white/[0.04]"></div>
      <div class="grid grid-cols-2 gap-4 md:grid-cols-4">
        {#each Array.from({ length: 4 }) as _, i}
          <div
            class="h-[104px] animate-pulse rounded-2xl border border-white/[0.06] bg-[#0C1B26]"
          ></div>
        {/each}
      </div>
    </section>
  {:else if data}
    <!-- KPIs -->
    <section class="container pb-component">
      <div class="grid grid-cols-2 gap-4 lg:grid-cols-5">
        <div
          class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6"
        >
          <div class="flex items-center justify-between">
            <DollarSign class="h-4 w-4 text-[#50C8C8]" />
          </div>
          <p class="metric mt-3 text-[#F7F7F7]">
            Rp {((data.kpis?.weeklyRevenue || 0) / 1000).toFixed(0)}K
          </p>
          <p class="caption mt-1 text-[#F7F7F7]/25">Revenue</p>
        </div>

        <div
          class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6"
        >
          <div class="flex items-center justify-between">
            <CalendarDays class="h-4 w-4 text-[#50C8C8]" />
          </div>
          <p class="metric mt-3 text-[#F7F7F7]">{data.kpis?.weeklyBookings || 0}</p>
          <p class="caption mt-1 text-[#F7F7F7]/25">Bookings</p>
        </div>

        <div
          class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6"
        >
          <div class="flex items-center justify-between">
            <TrendingUp class="h-4 w-4 text-[#50C8C8]" />
          </div>
          <p class="metric mt-3 text-[#F7F7F7]">{data.kpis?.occupancyRate || 0}%</p>
          <p class="caption mt-1 text-[#F7F7F7]/25">Occupancy</p>
        </div>

        <div
          class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6"
        >
          <div class="flex items-center justify-between">
            <Building2 class="h-4 w-4 text-[#50C8C8]" />
          </div>
          <p class="metric mt-3 text-[#F7F7F7]">{data.kpis?.activeCourts || 0}</p>
          <p class="caption mt-1 text-[#F7F7F7]/25">Active Courts</p>
        </div>

        <div
          class="rounded-2xl border border-[#50C8C8]/20 bg-[#50C8C8]/5 p-6"
        >
          <div class="flex items-center justify-between">
            <Clock class="h-4 w-4 text-[#50C8C8]" />
          </div>
          <p class="metric mt-3 text-[#F7F7F7]">{data.kpis?.pendingPayments || 0}</p>
          <p class="caption mt-1 text-[#F7F7F7]/25">Pending Payments</p>
        </div>
      </div>
    </section>

    <!-- REVENUE + UTILIZATION -->
    <section class="container pb-component">
      <div class="grid grid-cols-1 gap-5 lg:grid-cols-[2fr_1fr]">
        <!-- Revenue chart -->
        <div
          class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-8"
        >
          <div class="flex items-start justify-between">
            <div>
              <p class="section-label">Revenue This Week</p>
              <p class="metric mt-3 text-[#F7F7F7]">
                Rp {((data.kpis?.weeklyRevenue || 0) / 1000).toFixed(0)}K
              </p>
            </div>
            <div class="flex gap-1">
              <button
                type="button"
                class="label rounded-lg bg-[#E6FA50]/10 px-3 py-1.5 text-[#E6FA50]"
              >
                Weekly
              </button>
              <button
                type="button"
                class="label rounded-lg bg-white/[0.03] px-3 py-1.5 text-[#F7F7F7]/25"
              >
                Monthly
              </button>
            </div>
          </div>

          <div class="mt-10 flex h-40 items-end gap-2">
            {#each (data.revenueSeries || []) as d, i}
              <div class="flex flex-1 flex-col items-center gap-2">
                <div
                  class="w-full rounded-md bg-[#E6FA50]/15 transition-colors duration-200 hover:bg-[#E6FA50]/30"
                  style="height: {(d.value / maxRevenue) * 140}px"
                ></div>
                <span class="caption text-[#F7F7F7]/25">{d.label}</span>
              </div>
            {/each}
          </div>
        </div>

        <!-- Court utilization -->
        <div
          class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-8"
        >
          <p class="section-label">Court Utilization</p>

          <div class="mt-8 space-y-5">
            {#each (data.courtUtilization || []).slice(0, 5) as court}
              <div>
                <div class="flex items-center justify-between mb-1.5">
                  <span class="label text-[#F7F7F7]/40">{court.name}</span>
                  <span class="metric text-[#E6FA50]"
                    >{court.occupancyRate}%</span
                  >
                </div>
                <div
                  class="h-1.5 w-full overflow-hidden rounded-full bg-white/[0.04]"
                >
                  <div
                    class="h-full rounded-full bg-[#E6FA50]/70"
                    style="width: {court.occupancyRate}%"
                  ></div>
                </div>
              </div>
            {/each}
            {#if !data.courtUtilization || data.courtUtilization.length === 0}
              <p class="body text-[#F7F7F7]/40">No active courts.</p>
            {/if}
          </div>

          <div class="mt-8 border-t border-white/[0.04] pt-5">
            <p class="caption text-[#F7F7F7]/25">Average occupancy</p>
            <p class="metric mt-1 text-[#E6FA50]">
              {data.kpis?.occupancyRate || 0}%
            </p>
          </div>
        </div>
      </div>
    </section>

    <!-- TODAY'S SCHEDULE -->
    <section class="container pb-component">
      <div
        class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-8"
      >
        <div class="flex items-center justify-between mb-6">
          <p class="section-label">Today's Schedule</p>
          <span class="caption text-[#F7F7F7]/25">
            {data.todaysSchedule?.length || 0} bookings
          </span>
        </div>

        <div class="space-y-0">
          {#if !data.todaysSchedule || data.todaysSchedule.length === 0}
            <p class="body text-[#F7F7F7]/40">No bookings today.</p>
          {:else}
            {#each data.todaysSchedule as slot}
              {@const isConfirmed = slot.status === "CONFIRMED"}
              <div
                class="flex items-center gap-5 border-b border-white/[0.03] py-3.5 last:border-0"
              >
                <span class="metric w-12 shrink-0 text-[#F7F7F7]/40">
                  {slot.time}
                </span>
                <div
                  class="h-2.5 w-2.5 shrink-0 rounded-full {isConfirmed
                    ? 'bg-[#E6FA50]'
                    : 'border-2 border-[#50C8C8] bg-transparent'}"
                ></div>
                <div class="flex-1">
                  <p class="heading-3 text-[#F7F7F7]">{slot.player}</p>
                  <p class="caption text-[#F7F7F7]/25">{slot.court}</p>
                </div>
                <span
                  class="caption rounded-full px-2 py-0.5 uppercase {isConfirmed
                    ? 'bg-[#E6FA50]/10 text-[#E6FA50]'
                    : 'bg-[#50C8C8]/10 text-[#50C8C8]'}"
                >
                  {slot.status ? slot.status.replace(/_/g, " ") : "CONFIRMED"}
                </span>
              </div>
            {/each}
          {/if}
        </div>
      </div>
    </section>

    <!-- RECENT BOOKINGS -->
    <section class="container pb-component">
      <div class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-8">
        <div class="flex items-center justify-between mb-6">
          <p class="section-label">Recent Bookings</p>
          <a
            href="/dashboard/bookings"
            class="group flex items-center gap-1 caption text-[#F7F7F7]/25 transition-colors hover:text-[#E6FA50]"
          >
            View all
            <ArrowRight class="h-3 w-3 transition-transform group-hover:translate-x-0.5" />
          </a>
        </div>

        <div class="space-y-2">
          {#if !data.recentBookings || data.recentBookings.length === 0}
            <p class="body text-[#F7F7F7]/40">No recent bookings.</p>
          {:else}
            {#each data.recentBookings as booking (booking.id)}
              {@const isConfirmed = booking.status === "CONFIRMED"}
              {@const isPending = booking.status === "PENDING_PAYMENT"}
              <div
                class="flex items-center gap-4 rounded-lg bg-white/[0.02] p-3.5 transition-colors hover:bg-white/[0.04]"
              >
                <div class="flex-1 min-w-0">
                  <p class="heading-3 truncate text-[#F7F7F7]">
                    {booking.venueName}
                  </p>
                  <p class="caption mt-0.5 text-[#F7F7F7]/25">
                    {booking.courtName} · {booking.bookingDate} · {booking.time}
                  </p>
                </div>
                <p class="price shrink-0 text-[#F7F7F7]/60">
                  Rp {((booking.finalAmount || 0) / 1000).toFixed(0)}K
                </p>
                <div
                  class="h-2 w-2 shrink-0 rounded-full {isConfirmed
                    ? 'bg-[#E6FA50]'
                    : isPending
                      ? 'bg-[#50C8C8]'
                      : 'bg-[#F7F7F7]/25'}"
                ></div>
              </div>
            {/each}
          {/if}
        </div>
      </div>
    </section>

    <!-- QUICK ACTIONS -->
    <section class="container pb-component">
      <p class="section-label mb-5">Quick Actions</p>
      <div class="grid grid-cols-2 gap-4 md:grid-cols-4">
        <a
          href="/dashboard/courts"
          class="flex flex-col items-center gap-3 rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6 transition-all duration-200 hover:border-[#E6FA50]/20 hover:bg-[#E6FA50]/5"
        >
          <div
            class="flex h-9 w-9 items-center justify-center rounded-lg bg-[#E6FA50]/10"
          >
            <Plus class="h-4 w-4 text-[#E6FA50]" />
          </div>
          <span class="caption text-[#F7F7F7]/40">Add Court</span>
        </a>

        <a
          href="/dashboard/revenue"
          class="flex flex-col items-center gap-3 rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6 transition-all duration-200 hover:border-[#E6FA50]/20 hover:bg-[#E6FA50]/5"
        >
          <div
            class="flex h-9 w-9 items-center justify-center rounded-lg bg-[#E6FA50]/10"
          >
            <Tag class="h-4 w-4 text-[#E6FA50]" />
          </div>
          <span class="caption text-[#F7F7F7]/40">Create Promo</span>
        </a>

        <a
          href="/dashboard/hours"
          class="flex flex-col items-center gap-3 rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6 transition-all duration-200 hover:border-[#E6FA50]/20 hover:bg-[#E6FA50]/5"
        >
          <div
            class="flex h-9 w-9 items-center justify-center rounded-lg bg-[#E6FA50]/10"
          >
            <CalendarDays class="h-4 w-4 text-[#E6FA50]" />
          </div>
          <span class="caption text-[#F7F7F7]/40">Manage Schedule</span>
        </a>

        <a
          href="/dashboard/venues"
          class="flex flex-col items-center gap-3 rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6 transition-all duration-200 hover:border-[#E6FA50]/20 hover:bg-[#E6FA50]/5"
        >
          <div
            class="flex h-9 w-9 items-center justify-center rounded-lg bg-[#E6FA50]/10"
          >
            <Building2 class="h-4 w-4 text-[#E6FA50]" />
          </div>
          <span class="caption text-[#F7F7F7]/40">View Venues</span>
        </a>
      </div>
    </section>
  {/if}
</div>
