// apps/web/src/app/(marketing)/vouchers/page.tsx
"use client";

import { useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { queryKeys } from "@/lib/queries";
import {
  Ticket,
  Percent,
  DollarSign,
  Calendar,
  Copy,
  CheckCircle2,
  X,
} from "lucide-react";
import { getVouchers } from "@/lib/api";
import { Skeleton } from "@/components/ui/skeleton";
import { EmptyState, ErrorBanner } from "@/components/ui/error-state";
import { type Voucher } from "@/types";

export default function VouchersPage() {
  const [filter, setFilter] = useState<"active" | "expired">("active");
  const [selectedVoucher, setSelectedVoucher] = useState<Voucher | null>(null);
  const [toast, setToast] = useState<string | null>(null);
  const { data, isLoading: isLoadingVouchers, isError } = useQuery({
    queryKey: queryKeys.vouchers.all(),
    queryFn: getVouchers,
  });

  const vouchers = data ?? [];

  const hasApiData = Boolean(data && data.length > 0);
  const shouldShowLoading = isLoadingVouchers && !hasApiData;

  const active = vouchers.filter((v) => v.isActive);
  const expired = vouchers.filter((v) => !v.isActive);
  const filtered = filter === "active" ? active : expired;

  function showToast(msg: string) {
    setToast(msg);
    setTimeout(() => setToast(null), 2500);
  }

  function copyCode(code: string) {
    navigator.clipboard.writeText(code).then(() => {
      showToast(`Copied "${code}" to clipboard`);
    }).catch(() => {
      showToast(`Code: ${code}`);
    });
  }

  function formatDiscount(voucher: Voucher): string {
    if (voucher.type === "percentage") return `${voucher.value}% OFF`;
    return `Rp ${(voucher.value / 1000).toFixed(0)}K OFF`;
  }

  return (
    <div className="min-h-screen py-section-sm space-y-subsection">
      <section className="container">
        <span className="section-label block mb-4">Rewards</span>
        <h1 className="heading-1 text-[#F7F7F7]">
          Promo & <span className="text-[#E6FA50]">Vouchers</span>
        </h1>
        <p className="body mt-2 text-[#F7F7F7]/40">
          Use voucher codes to get discounts on your bookings.
        </p>
        {isError && !shouldShowLoading && (
          <div className="mt-5">
            <ErrorBanner
              title="Couldn't load vouchers"
              description="An error occurred while fetching vouchers. Please try again later."
            />
          </div>
        )}
      </section>

      {/* Tabs */}
      <section className="container">
        <div className="flex gap-1 border-b border-white/[0.06]">
          {(["active", "expired"] as const).map((tab) => (
            <button
              key={tab}
              onClick={() => setFilter(tab)}
              className={`label relative px-5 py-3 uppercase transition-colors ${
                filter === tab
                  ? "text-[#E6FA50]"
                  : "text-[#F7F7F7]/25 hover:text-[#F7F7F7]/60"
              }`}
            >
              {tab} ({tab === "active" ? active.length : expired.length})
              {filter === tab && (
                <span className="absolute bottom-0 left-0 right-0 h-[2px] bg-[#E6FA50]" />
              )}
            </button>
          ))}
        </div>
      </section>

      {/* Voucher Grid */}
      <section className="container">
        {shouldShowLoading ? (
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
            {[...Array(6)].map((_, i) => (
              <div key={i} className="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6">
                <div className="flex items-center justify-between mb-4">
                  <Skeleton className="h-[26px] w-[72px] rounded-full" />
                </div>
                <Skeleton className="h-6 w-32 mb-3 rounded-md" />
                <Skeleton className="h-4 w-48 mb-6 rounded-md" />
                <div className="flex items-center justify-between pt-4 border-t border-white/[0.04]">
                  <Skeleton className="h-3 w-32 rounded-full" />
                </div>
              </div>
            ))}
          </div>
        ) : (
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">
          {filtered.map((voucher) => (
            <div
              key={voucher.id}
              className={`group relative overflow-hidden rounded-2xl border p-6 transition-all duration-200 ${
                voucher.isActive
                  ? "border-white/[0.06] bg-[#0C1B26] hover:border-[#E6FA50]/15"
                  : "border-white/[0.03] bg-[#0C1B26]/50 opacity-60"
              }`}
            >
              {/* Discount badge */}
              <div className="flex items-center justify-between mb-4">
                <div className={`flex items-center gap-2 rounded-full px-3 py-1 ${
                  voucher.type === "percentage"
                    ? "bg-[#E6FA50]/10 text-[#E6FA50]"
                    : "bg-[#50C8C8]/10 text-[#50C8C8]"
                }`}>
                  {voucher.type === "percentage"
                    ? <Percent className="h-3.5 w-3.5" />
                    : <DollarSign className="h-3.5 w-3.5" />
                  }
                  <span className="label">{formatDiscount(voucher)}</span>
                </div>
                {voucher.isActive && (
                  <span className="h-2 w-2 rounded-full bg-[#E6FA50] animate-pulse" />
                )}
              </div>

              {/* Code */}
              <div className="flex items-center gap-2 mb-3">
                <code className="heading-3 text-[#F7F7F7]">{voucher.code}</code>
                {voucher.isActive && (
                  <button
                    onClick={() => copyCode(voucher.code)}
                    className="flex h-6 w-6 items-center justify-center rounded-md bg-white/[0.04] text-[#F7F7F7]/25 transition-colors hover:bg-white/[0.08] hover:text-[#F7F7F7]/60"
                  >
                    <Copy className="h-3 w-3" />
                  </button>
                )}
              </div>

              {/* Details */}
              <div className="space-y-1.5">
                {voucher.minPurchase && (
                  <p className="caption text-[#F7F7F7]/25">
                    Min. spend Rp {(voucher.minPurchase / 1000).toFixed(0)}K
                  </p>
                )}
                {voucher.maxDiscount && (
                  <p className="caption text-[#F7F7F7]/25">
                    Max discount Rp {(voucher.maxDiscount / 1000).toFixed(0)}K
                  </p>
                )}
                <p className="caption flex items-center gap-1 text-[#F7F7F7]/25">
                  <Calendar className="h-3 w-3" />
                  Valid until {voucher.validUntil}
                </p>
              </div>

              {/* Usage bar */}
              <div className="mt-4">
                <div className="flex items-center justify-between mb-1">
                  <span className="caption text-[#F7F7F7]/25">Usage</span>
                  <span className="caption text-[#F7F7F7]/25">{voucher.usedCount}/{voucher.usageLimit}</span>
                </div>
                <div className="h-1.5 w-full rounded-full bg-white/[0.04]">
                  <div
                    className="h-full rounded-full bg-[#E6FA50]/40 transition-all"
                    style={{ width: `${(voucher.usedCount / voucher.usageLimit) * 100}%` }}
                  />
                </div>
              </div>

              {/* View details */}
              <button
                onClick={() => setSelectedVoucher(voucher)}
                className="label mt-4 w-full rounded-xl border border-white/[0.06] py-2 text-[#F7F7F7]/40 transition-colors hover:border-white/[0.12] hover:text-[#F7F7F7]/60"
              >
                View Details
              </button>
            </div>
          ))}
        </div>
        )}

        {filtered.length === 0 && !isError && (
          <div className="py-16 text-center">
            <EmptyState icon={Ticket} title={`No ${filter} vouchers found`} description={`There are no ${filter} vouchers available.`} actionLabel="Browse venues" actionHref="/venues" />
          </div>
        )}
      </section>

      {/* Detail Modal */}
      {selectedVoucher && (
        <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
          <div className="absolute inset-0 bg-[#06121A]/80 backdrop-blur-sm" onClick={() => setSelectedVoucher(null)} />
          <div className="relative w-full max-w-md rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6 shadow-2xl">
            <button
              onClick={() => setSelectedVoucher(null)}
              className="absolute right-4 top-4 flex h-8 w-8 items-center justify-center rounded-lg text-[#F7F7F7]/25 transition-colors hover:bg-white/[0.04] hover:text-[#F7F7F7]/60"
            >
              <X className="h-4 w-4" />
            </button>

            <div className={`inline-flex items-center gap-2 rounded-full px-3 py-1 mb-4 ${
              selectedVoucher.type === "percentage"
                ? "bg-[#E6FA50]/10 text-[#E6FA50]"
                : "bg-[#50C8C8]/10 text-[#50C8C8]"
            }`}>
              {selectedVoucher.type === "percentage"
                ? <Percent className="h-3.5 w-3.5" />
                : <DollarSign className="h-3.5 w-3.5" />
              }
              <span className="label">{formatDiscount(selectedVoucher)}</span>
            </div>

            <h2 className="heading-2 text-[#F7F7F7] mb-1">{selectedVoucher.code}</h2>
            <p className="caption text-[#F7F7F7]/25 mb-5">
              {selectedVoucher.type === "percentage" ? "Percentage discount" : "Fixed amount discount"}
            </p>

            <div className="space-y-3 mb-6">
              <DetailRow label="Discount" value={formatDiscount(selectedVoucher)} />
              {selectedVoucher.minPurchase && (
                <DetailRow label="Min. Spend" value={`Rp ${(selectedVoucher.minPurchase / 1000).toFixed(0)}K`} />
              )}
              {selectedVoucher.maxDiscount && (
                <DetailRow label="Max Discount" value={`Rp ${(selectedVoucher.maxDiscount / 1000).toFixed(0)}K`} />
              )}
              <DetailRow label="Valid From" value={selectedVoucher.validFrom} />
              <DetailRow label="Valid Until" value={selectedVoucher.validUntil} />
              <DetailRow label="Usage" value={`${selectedVoucher.usedCount} / ${selectedVoucher.usageLimit}`} />
              <DetailRow label="Status" value={selectedVoucher.isActive ? "Active" : "Expired"} />
            </div>

            {selectedVoucher.isActive && (
              <button
                onClick={() => { copyCode(selectedVoucher.code); setSelectedVoucher(null); }}
                className="label btn-lime w-full flex items-center justify-center gap-2 rounded-xl py-3"
              >
                <Copy className="h-4 w-4" /> Copy Code
              </button>
            )}
          </div>
        </div>
      )}

      {/* Toast */}
      {toast && (
        <div className="fixed bottom-6 left-1/2 z-50 -translate-x-1/2 rounded-xl border border-white/[0.06] bg-[#0C1B26] px-5 py-3 shadow-2xl">
          <p className="caption flex items-center gap-2 text-[#F7F7F7]/60">
            <CheckCircle2 className="h-3.5 w-3.5 text-[#E6FA50]" />
            {toast}
          </p>
        </div>
      )}
    </div>
  );
}

function DetailRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-center justify-between rounded-lg bg-white/[0.02] px-3 py-2.5">
      <span className="caption text-[#F7F7F7]/25">{label}</span>
      <span className="label text-[#F7F7F7]/60">{value}</span>
    </div>
  );
}

// apps/web/src/routes/(marketing)/vouchers/+page.svelte
<script lang="ts">
import {
  Calendar,
  CheckCircle2,
  Copy,
  DollarSign,
  Percent,
  Ticket,
  X,
} from "lucide-svelte";
import { onMount } from "svelte";
import { api } from "$lib/api/client";

let vouchers = $state<any[]>([]);
let isLoading = $state(true);
let filter = $state<"active" | "expired">("active");
let selectedVoucher = $state<any | null>(null);
let toast = $state<string | null>(null);

onMount(async () => {
  try {
    const res = await api.vouchers.get();
    if (res.data) {
      vouchers = res.data;
    }
  } catch (e) {
    console.warn("Vouchers fetch error:", e);
  } finally {
    isLoading = false;
  }
});

const active = $derived(vouchers.filter((v) => v.isActive));
const expired = $derived(vouchers.filter((v) => !v.isActive));
const filtered = $derived(filter === "active" ? active : expired);

function showToast(msg: string) {
  toast = msg;
  setTimeout(() => {
    toast = null;
  }, 2500);
}

function copyCode(code: string) {
  navigator.clipboard
    .writeText(code)
    .then(() => {
      showToast(`Copied "${code}" to clipboard`);
    })
    .catch(() => {
      showToast(`Code: ${code}`);
    });
}

function formatDiscount(voucher: any): string {
  if (voucher.type === "percentage" || voucher.type === "PERCENTAGE")
    return `${voucher.value}% OFF`;
  return `Rp ${(voucher.value / 1000).toFixed(0)}K OFF`;
}

function formatVoucherDate(dateVal: any): string {
  if (!dateVal) return "Dec 31, 2026";
  try {
    const d = new Date(dateVal);
    if (Number.isNaN(d.getTime())) return String(dateVal);
    return d.toLocaleDateString("en-US", {
      day: "numeric",
      month: "short",
      year: "numeric",
    });
  } catch (e) {
    return "Dec 31, 2026";
  }
}
</script>

<svelte:head>
  <title>Vouchers & Promos | PadelHive</title>
</svelte:head>

<div class="min-h-screen py-16 bg-[#06121A]">
  <!-- Header -->
  <section class="container pt-8 pb-4">
    <span class="caption font-semibold tracking-wider uppercase text-[#50C8C8] block mb-3">REWARDS</span>
    <h1 class="heading-1 text-3xl md:text-4xl font-bold text-[#F7F7F7]">
      Promo & <span class="text-[#E6FA50]">Vouchers</span>
    </h1>
    <p class="body mt-2 text-[#F7F7F7]/40">
      Use voucher codes to get discounts on your bookings.
    </p>
  </section>

  <!-- Tabs -->
  <section class="container max-w-[1200px] mt-6">
    <div class="inline-flex items-center gap-2 rounded-full border border-white/[0.06] bg-[#0C1B26] p-1.5 mb-6">
      <button
        type="button"
        onclick={() => (filter = "active")}
        class="label rounded-full px-5 py-2 text-sm font-semibold transition-all select-none cursor-pointer {filter === 'active'
          ? 'bg-[#E6FA50] text-[#06121A] font-bold shadow-sm'
          : 'text-[#F7F7F7]/40 hover:text-[#F7F7F7]/60'}"
      >
        Active ({active.length})
      </button>
      <button
        type="button"
        onclick={() => (filter = "expired")}
        class="label rounded-full px-5 py-2 text-sm font-semibold transition-all select-none cursor-pointer {filter === 'expired'
          ? 'bg-[#E6FA50] text-[#06121A] font-bold shadow-sm'
          : 'text-[#F7F7F7]/40 hover:text-[#F7F7F7]/60'}"
      >
        Expired ({expired.length})
      </button>
    </div>
    <div class="border-b border-white/[0.06] mb-8"></div>
  </section>

  <!-- Voucher Grid -->
  <section class="container">
    {#if isLoading}
      <div class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
        {#each Array.from({ length: 6 }) as _, i}
          <div
            class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6 space-y-4"
          >
            <div class="h-6 w-20 animate-pulse rounded-full bg-white/[0.04]"></div>
            <div class="h-6 w-32 animate-pulse rounded-md bg-white/[0.04]"></div>
            <div class="h-4 w-48 animate-pulse rounded-md bg-white/[0.04]"></div>
          </div>
        {/each}
      </div>
    {:else if filtered.length === 0}
      <div class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-12 text-center max-w-4xl mx-auto my-8">
        <div class="flex h-12 w-12 items-center justify-center rounded-2xl bg-white/[0.04] text-[#E6FA50] mx-auto mb-4">
          <Ticket class="h-6 w-6" />
        </div>
        <h2 class="heading-2 text-xl font-bold text-[#F7F7F7]">No {filter} vouchers found</h2>
        <p class="body mt-2 text-[#F7F7F7]/40">
          There are no {filter} vouchers available.
        </p>
        <a
          href="/venues"
          class="btn-lime label inline-flex items-center justify-center rounded-full px-6 py-2.5 font-semibold text-sm bg-[#E6FA50] text-[#06121A] hover:bg-[#E6FA50]/90 transition-all mt-6"
        >
          Browse venues
        </a>
      </div>
    {:else}
      <div class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
        {#each filtered as voucher (voucher.id)}
          <div
            class="group relative flex flex-col justify-between overflow-hidden rounded-2xl border p-6 transition-all duration-200 {voucher.isActive
              ? 'border-white/[0.06] bg-[#0C1B26] hover:border-white/[0.12]'
              : 'border-white/[0.03] bg-[#0C1B26]/50 opacity-60'}"
          >
            <div>
              <!-- Discount badge -->
              <div class="flex items-center justify-between mb-4">
                <div
                  class="flex items-center gap-1.5 rounded-full px-3.5 py-1 text-xs font-semibold {voucher.type ===
                    'percentage' || voucher.type === 'PERCENTAGE'
                    ? 'bg-[#E6FA50]/10 text-[#E6FA50]'
                    : 'bg-[#50C8C8]/10 text-[#50C8C8]'}"
                >
                  {#if voucher.type === "percentage" || voucher.type === "PERCENTAGE"}
                    <Percent class="h-3.5 w-3.5" />
                  {:else}
                    <DollarSign class="h-3.5 w-3.5" />
                  {/if}
                  <span>{formatDiscount(voucher)}</span>
                </div>
                {#if voucher.isActive}
                  <span
                    class="h-2.5 w-2.5 rounded-full bg-[#E6FA50] shadow-sm shadow-[#E6FA50]/40 animate-pulse"
                  ></span>
                {/if}
              </div>

              <!-- Code -->
              <div class="flex items-center gap-2 mb-4 mt-2">
                <code class="text-xl font-bold font-mono tracking-wider text-[#F7F7F7]">
                  {voucher.code}
                </code>
                {#if voucher.isActive}
                  <button
                    type="button"
                    onclick={() => copyCode(voucher.code)}
                    class="flex h-7 w-7 items-center justify-center rounded-lg border border-white/[0.08] bg-white/[0.03] text-[#F7F7F7]/40 transition-colors hover:bg-white/[0.08] hover:text-[#F7F7F7]"
                    aria-label="Copy voucher code"
                  >
                    <Copy class="h-3.5 w-3.5" />
                  </button>
                {/if}
              </div>

              <!-- Inner Details Box -->
              <div class="rounded-xl border border-white/[0.04] bg-white/[0.015] p-3.5 space-y-2">
                {#if voucher.minPurchase}
                  <div class="flex items-center justify-between text-xs">
                    <span class="text-[#F7F7F7]/40">Min. spend</span>
                    <span class="font-semibold text-[#F7F7F7]/80">Rp {(voucher.minPurchase / 1000).toFixed(0)}K</span>
                  </div>
                {/if}
                {#if voucher.maxDiscount}
                  <div class="flex items-center justify-between text-xs">
                    <span class="text-[#F7F7F7]/40">Max discount</span>
                    <span class="font-semibold text-[#F7F7F7]/80">Rp {(voucher.maxDiscount / 1000).toFixed(0)}K</span>
                  </div>
                {/if}
                <div class="flex items-center justify-between text-xs {voucher.minPurchase || voucher.maxDiscount ? 'border-t border-white/[0.04] pt-2 mt-1' : ''}">
                  <span class="inline-flex items-center gap-1.5 text-[#F7F7F7]/40">
                    <Calendar class="h-3.5 w-3.5 text-[#F7F7F7]/40" />
                    Valid until
                  </span>
                  <span class="font-semibold text-[#F7F7F7]/80">{formatVoucherDate(voucher.validUntil)}</span>
                </div>
              </div>

              <!-- Usage bar -->
              <div class="mt-4">
                <div class="flex items-center justify-between mb-1.5">
                  <span class="caption text-[#F7F7F7]/40 text-xs font-medium">Usage</span>
                  <span class="caption text-[#F7F7F7]/60 text-xs font-mono font-semibold">
                    {voucher.usedCount}/{voucher.usageLimit}
                  </span>
                </div>
                <div class="h-2 w-full rounded-full bg-white/[0.06] overflow-hidden">
                  <div
                    class="h-full rounded-full bg-[#E6FA50] transition-all duration-300"
                    style="width: {voucher.usageLimit > 0 ? (voucher.usedCount / voucher.usageLimit) * 100 : 0}%"
                  ></div>
                </div>
              </div>
            </div>

            <!-- View details -->
            <button
              type="button"
              onclick={() => (selectedVoucher = voucher)}
              class="label mt-5 flex h-10 w-full items-center justify-center rounded-xl border border-white/[0.08] bg-white/[0.02] text-xs font-semibold text-[#F7F7F7]/70 transition-all hover:border-[#E6FA50]/30 hover:bg-[#E6FA50]/5 hover:text-[#E6FA50]"
            >
              View Details
            </button>
          </div>
        {/each}
      </div>
    {/if}
  </section>

  <!-- Detail Modal -->
  {#if selectedVoucher}
    <div class="fixed inset-0 z-50 flex items-center justify-center p-4">
      <button
        type="button"
        class="absolute inset-0 bg-[#06121A]/80 backdrop-blur-sm border-0 w-full h-full cursor-default"
        onclick={() => (selectedVoucher = null)}
        aria-label="Close backdrop"
      ></button>
      <div
        class="relative w-full max-w-md rounded-2xl border border-white/[0.08] bg-[#0C1B26] p-6 shadow-2xl z-10"
      >
        <button
          type="button"
          onclick={() => (selectedVoucher = null)}
          class="absolute right-4 top-4 flex h-8 w-8 items-center justify-center rounded-lg text-[#F7F7F7]/40 transition-colors hover:bg-white/[0.04] hover:text-[#F7F7F7]"
        >
          <X class="h-4 w-4" />
        </button>

        <div
          class="inline-flex items-center gap-2 rounded-full px-3 py-1 mb-4 text-xs font-semibold {selectedVoucher.type ===
            'percentage' || selectedVoucher.type === 'PERCENTAGE'
            ? 'bg-[#E6FA50]/10 text-[#E6FA50]'
            : 'bg-[#50C8C8]/10 text-[#50C8C8]'}"
        >
          {#if selectedVoucher.type === "percentage" || selectedVoucher.type === "PERCENTAGE"}
            <Percent class="h-3.5 w-3.5" />
          {:else}
            <DollarSign class="h-3.5 w-3.5" />
          {/if}
          <span class="label">{formatDiscount(selectedVoucher)}</span>
        </div>

        <h2 class="heading-2 text-[#F7F7F7] text-xl font-bold mb-1">
          {selectedVoucher.code}
        </h2>
        <p class="caption text-[#F7F7F7]/40 text-xs mb-5">
          {selectedVoucher.type === "percentage" || selectedVoucher.type === "PERCENTAGE"
            ? "Percentage discount"
            : "Fixed amount discount"}
        </p>

        <div class="space-y-3 mb-6">
          <div class="flex items-center justify-between rounded-xl bg-white/[0.02] p-3 border border-white/[0.04]">
            <span class="caption text-[#F7F7F7]/40">Discount</span>
            <span class="label text-[#F7F7F7] font-semibold">{formatDiscount(selectedVoucher)}</span>
          </div>
          {#if selectedVoucher.minPurchase}
            <div class="flex items-center justify-between rounded-xl bg-white/[0.02] p-3 border border-white/[0.04]">
              <span class="caption text-[#F7F7F7]/40">Min. Spend</span>
              <span class="label text-[#F7F7F7] font-semibold">Rp {(selectedVoucher.minPurchase / 1000).toFixed(0)}K</span>
            </div>
          {/if}
          {#if selectedVoucher.maxDiscount}
            <div class="flex items-center justify-between rounded-xl bg-white/[0.02] p-3 border border-white/[0.04]">
              <span class="caption text-[#F7F7F7]/40">Max Discount</span>
              <span class="label text-[#F7F7F7] font-semibold">Rp {(selectedVoucher.maxDiscount / 1000).toFixed(0)}K</span>
            </div>
          {/if}
          <div class="flex items-center justify-between rounded-xl bg-white/[0.02] p-3 border border-white/[0.04]">
            <span class="caption text-[#F7F7F7]/40">Valid Until</span>
            <span class="label text-[#F7F7F7] font-semibold">{formatVoucherDate(selectedVoucher.validUntil)}</span>
          </div>
          <div class="flex items-center justify-between rounded-xl bg-white/[0.02] p-3 border border-white/[0.04]">
            <span class="caption text-[#F7F7F7]/40">Usage</span>
            <span class="label text-[#F7F7F7] font-semibold">{selectedVoucher.usedCount} / {selectedVoucher.usageLimit}</span>
          </div>
          <div class="flex items-center justify-between rounded-xl bg-white/[0.02] p-3 border border-white/[0.04]">
            <span class="caption text-[#F7F7F7]/40">Status</span>
            <span class="label font-semibold {selectedVoucher.isActive ? 'text-green-400' : 'text-red-400'}">{selectedVoucher.isActive ? "Active" : "Expired"}</span>
          </div>
        </div>

        {#if selectedVoucher.isActive}
          <button
            type="button"
            onclick={() => {
              copyCode(selectedVoucher.code);
              selectedVoucher = null;
            }}
            class="label btn-lime w-full flex items-center justify-center gap-2 rounded-full py-3 font-semibold text-[#06121A] bg-[#E6FA50] hover:bg-[#E6FA50]/90 transition-all"
          >
            <Copy class="h-4 w-4" /> Copy Code
          </button>
        {/if}
      </div>
    </div>
  {/if}

  <!-- Toast -->
  {#if toast}
    <div
      class="fixed bottom-6 left-1/2 z-50 -translate-x-1/2 rounded-xl border border-white/[0.08] bg-[#0C1B26] px-5 py-3 shadow-2xl shadow-black/40"
    >
      <p class="caption flex items-center gap-2 text-[#F7F7F7]/80 font-medium">
        <CheckCircle2 class="h-4 w-4 text-[#E6FA50]" />
        {toast}
      </p>
    </div>
  {/if}
</div>
