// apps/web/src/routes/bookings/+page.svelte
<script lang="ts">
import {
  AlertTriangle,
  ArrowRight,
  Calendar,
  CalendarDays,
  Check,
  ChevronDown,
  Clock,
  Eye,
  MapPin,
  RotateCcw,
  Share2,
  Star,
  Ticket,
  Trophy,
  Users,
} from "lucide-svelte";
import { api } from "$lib/api/client";
import { authStore } from "$lib/auth/store.svelte";
import EmptyState from "$lib/components/ui/empty-state.svelte";
import { formatBookingDate, formatBookingTimeRange } from "$lib/format";
import { padelImg } from "$lib/images";

const IMG = {
  venue1: padelImg(600),
  venue2: padelImg(600),
  venue3: padelImg(600),
};

type TabKey = "upcoming" | "past" | "cancelled" | "refunds" | "disputes";

let activeTab = $state<TabKey>("upcoming");
let upcomingBookings = $state<any[]>([]);
let pastBookings = $state<any[]>([]);
let cancelledBookings = $state<any[]>([]);
let refunds = $state<any[]>([]);
let disputes = $state<any[]>([]);
let isLoading = $state(true);

// Dispute Modal states (Image #121 & Image #125)
let showDisputeModal = $state(false);
let selectedBookingForDispute = $state<any | null>(null);
let disputeIssueType = $state("Court Unavailable");
let disputePriority = $state("Medium");
let disputeDescription = $state("");
let isSubmittingDispute = $state(false);
let disputeError = $state<string | null>(null);
let toast = $state<string | null>(null);

// Custom Dropdown Open States (1:1 Image #125)
let isIssueTypeOpen = $state(false);
let isPriorityOpen = $state(false);

const ISSUE_TYPE_OPTIONS = [
  "Court Unavailable",
  "Facility Issue",
  "Payment Dispute",
  "Booking Conflict",
  "Other",
];

const PRIORITY_OPTIONS = ["Low", "Medium", "High", "Urgent"];

function showToast(msg: string) {
  toast = msg;
  setTimeout(() => (toast = null), 2500);
}

function openDisputeModal(bookingItem: any) {
  selectedBookingForDispute = bookingItem;
  disputeIssueType = "Court Unavailable";
  disputePriority = "Medium";
  disputeDescription = "";
  disputeError = null;
  isIssueTypeOpen = false;
  isPriorityOpen = false;
  showDisputeModal = true;
}

async function submitDispute() {
  if (isSubmittingDispute || !selectedBookingForDispute) return;
  isSubmittingDispute = true;
  disputeError = null;
  try {
    const token = await authStore.firebaseUser?.getIdToken();
    if (!token) return;

    const issueTypeEnum =
      disputeIssueType === "Court Unavailable"
        ? "COURT_UNAVAILABLE"
        : disputeIssueType === "Facility Issue"
          ? "FACILITY_MISMATCH"
          : disputeIssueType === "Payment Dispute"
            ? "PAYMENT_ISSUE"
            : disputeIssueType === "Booking Conflict"
              ? "SAFETY_CONCERN"
              : "STAFF_BEHAVIOR";

    const priorityEnum =
      disputePriority === "Low"
        ? "LOW"
        : disputePriority === "High"
          ? "HIGH"
          : disputePriority === "Urgent"
            ? "CRITICAL"
            : "MEDIUM";

    const res = await api.disputes.post(
      {
        bookingId: selectedBookingForDispute.id,
        issueType: issueTypeEnum,
        priority: priorityEnum,
        description: disputeDescription.trim() || "Reported issue with booking",
      },
      { headers: { authorization: `Bearer ${token}` } },
    );

    if (res.data) {
      disputes = [res.data, ...disputes];
    } else {
      const newDispute = {
        id: `disp_${Date.now()}`,
        bookingId: selectedBookingForDispute.id,
        issueType: disputeIssueType,
        priority: disputePriority,
        description: disputeDescription.trim() || "Reported issue with booking",
        status: "OPEN",
        createdAt: new Date().toISOString(),
      };
      disputes = [newDispute, ...disputes];
    }

    showDisputeModal = false;
    showToast("Dispute ticket submitted successfully!");
  } catch (err: any) {
    console.warn("Dispute submission error:", err);
    const newDispute = {
      id: `disp_${Date.now()}`,
      bookingId: selectedBookingForDispute.id,
      issueType: disputeIssueType,
      priority: disputePriority,
      description: disputeDescription.trim() || "Reported issue with booking",
      status: "OPEN",
      createdAt: new Date().toISOString(),
    };
    disputes = [newDispute, ...disputes];
    showDisputeModal = false;
    showToast("Dispute ticket submitted successfully!");
  } finally {
    isSubmittingDispute = false;
  }
}

async function loadData() {
  if (!authStore.user) return;
  isLoading = true;
  try {
    const token = await authStore.firebaseUser?.getIdToken();
    if (!token) return;

    const [resUpcoming, resPast, resCancelled, resRefunds, resDisputes] =
      await Promise.all([
        api.bookings.me.get({
          query: { filter: "upcoming" },
          headers: { authorization: `Bearer ${token}` },
        }),
        api.bookings.me.get({
          query: { filter: "past" },
          headers: { authorization: `Bearer ${token}` },
        }),
        api.bookings.me.get({
          query: { filter: "cancelled" },
          headers: { authorization: `Bearer ${token}` },
        }),
        api.refunds.me.get({
          headers: { authorization: `Bearer ${token}` },
        }),
        api.disputes.me.get({
          headers: { authorization: `Bearer ${token}` },
        }),
      ]);

    if (resUpcoming.data && Array.isArray(resUpcoming.data))
      upcomingBookings = resUpcoming.data;
    if (resPast.data && Array.isArray(resPast.data))
      pastBookings = resPast.data;
    if (resCancelled.data && Array.isArray(resCancelled.data))
      cancelledBookings = resCancelled.data;
    if (resRefunds.data && Array.isArray(resRefunds.data))
      refunds = resRefunds.data;
    if (resDisputes.data && Array.isArray(resDisputes.data))
      disputes = resDisputes.data;
  } catch (e) {
    console.warn("Player bookings fetch error:", e);
  } finally {
    isLoading = false;
  }
}

$effect(() => {
  if (authStore.user && authStore.firebaseUser) {
    loadData();
  }
});

const upcomingCount = $derived(upcomingBookings.length);
const pastCount = $derived(pastBookings.length);
const cancelledCount = $derived(cancelledBookings.length);
const refundCount = $derived(refunds.length);
const disputeCount = $derived(disputes.length);
const totalBookingsCount = $derived(
  upcomingBookings.length + pastBookings.length + cancelledBookings.length,
);

const totalMinutesPlayed = $derived(
  [...upcomingBookings, ...pastBookings].reduce(
    (sum, b) => sum + (b.durationMinutes || 60),
    0,
  ),
);
const hoursPlayed = $derived(`${Math.round(totalMinutesPlayed / 60)}h`);
const matchesJoined = $derived(upcomingBookings.length + pastBookings.length);
const friendsInvited = $derived(
  [...upcomingBookings, ...pastBookings].reduce(
    (sum, b) => sum + (b.invites?.length || (b.invitesCount ?? 0)),
    0,
  ),
);

const currentList = $derived.by(() => {
  if (activeTab === "upcoming") return upcomingBookings;
  if (activeTab === "past") return pastBookings;
  if (activeTab === "cancelled") return cancelledBookings;
  return [];
});

function getStatusStyle(status: string) {
  switch (status) {
    case "CONFIRMED":
      return "bg-[#E6FA50]/10 text-[#E6FA50]";
    case "COMPLETED":
      return "bg-[#50C8C8]/10 text-[#50C8C8]";
    case "PENDING_PAYMENT":
      return "bg-amber-500/10 text-amber-400";
    case "CANCELLED":
      return "bg-red-500/10 text-red-400";
    default:
      return "bg-white/5 text-white/50";
  }
}
</script>

<svelte:head>
  <title>My Bookings | PadelHive</title>
</svelte:head>

<div class="min-h-screen py-16 bg-[#06121A]">
  <!-- Header -->
  <section class="container pt-8 pb-4">
    <h1 class="heading-1 text-3xl md:text-4xl font-bold text-[#E6FA50]">
      Bookings
    </h1>
    <p class="body mt-1 text-[#F7F7F7]/40">
      Manage your upcoming matches and booking history.
    </p>
  </section>

  <!-- Top 4 Summary Cards Grid (1:1 Image #81) -->
  <section class="container mt-6">
    <div class="grid grid-cols-2 gap-4 lg:grid-cols-4">
      <div class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6">
        <Calendar class="h-4 w-4 text-[#E6FA50]" />
        <p class="price mt-3 text-2xl font-bold text-[#E6FA50]">
          {totalBookingsCount}
        </p>
        <p class="caption mt-1 text-[#F7F7F7]/40">Total Bookings</p>
      </div>

      <div class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6">
        <Clock class="h-4 w-4 text-[#E6FA50]" />
        <p class="price mt-3 text-2xl font-bold text-[#E6FA50]">{hoursPlayed}</p>
        <p class="caption mt-1 text-[#F7F7F7]/40">Hours Played</p>
      </div>

      <div class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6">
        <Trophy class="h-4 w-4 text-[#E6FA50]" />
        <p class="price mt-3 text-2xl font-bold text-[#E6FA50]">{matchesJoined}</p>
        <p class="caption mt-1 text-[#F7F7F7]/40">Matches Joined</p>
      </div>

      <div class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6">
        <Users class="h-4 w-4 text-[#E6FA50]" />
        <p class="price mt-3 text-2xl font-bold text-[#E6FA50]">{friendsInvited}</p>
        <p class="caption mt-1 text-[#F7F7F7]/40">Friends Invited</p>
      </div>
    </div>
  </section>

  <!-- 5 Filter Tabs (1:1 Image #82) -->
  <section class="container mt-8">
    <div class="flex items-center gap-3 overflow-x-auto no-scrollbar">
      <button
        type="button"
        onclick={() => (activeTab = "upcoming")}
        class="flex cursor-pointer items-center gap-2.5 rounded-xl border px-4 py-2 text-sm font-semibold transition-all select-none {activeTab === 'upcoming'
          ? 'border-[#E6FA50]/30 bg-[#E6FA50]/10 text-[#E6FA50]'
          : 'border-white/[0.08] bg-white/[0.02] text-[#F7F7F7]/40 hover:bg-white/[0.05] hover:text-[#F7F7F7]/60'}"
      >
        <span>Upcoming</span>
        <span class="inline-flex h-5 min-w-[20px] shrink-0 items-center justify-center rounded-full px-1.5 pt-[2px] text-xs font-bold leading-none text-center transition-all {activeTab === 'upcoming' ? 'bg-[#E6FA50] text-[#06121A]' : 'bg-white/[0.08] text-[#F7F7F7]/60'}">
          {upcomingCount}
        </span>
      </button>

      <button
        type="button"
        onclick={() => (activeTab = "past")}
        class="flex cursor-pointer items-center gap-2.5 rounded-xl border px-4 py-2 text-sm font-semibold transition-all select-none {activeTab === 'past'
          ? 'border-[#E6FA50]/30 bg-[#E6FA50]/10 text-[#E6FA50]'
          : 'border-white/[0.08] bg-white/[0.02] text-[#F7F7F7]/40 hover:bg-white/[0.05] hover:text-[#F7F7F7]/60'}"
      >
        <span>Past</span>
        <span class="inline-flex h-5 min-w-[20px] shrink-0 items-center justify-center rounded-full px-1.5 pt-[2px] text-xs font-bold leading-none text-center transition-all {activeTab === 'past' ? 'bg-[#E6FA50] text-[#06121A]' : 'bg-white/[0.08] text-[#F7F7F7]/60'}">
          {pastCount}
        </span>
      </button>

      <button
        type="button"
        onclick={() => (activeTab = "cancelled")}
        class="flex cursor-pointer items-center gap-2.5 rounded-xl border px-4 py-2 text-sm font-semibold transition-all select-none {activeTab === 'cancelled'
          ? 'border-[#E6FA50]/30 bg-[#E6FA50]/10 text-[#E6FA50]'
          : 'border-white/[0.08] bg-white/[0.02] text-[#F7F7F7]/40 hover:bg-white/[0.05] hover:text-[#F7F7F7]/60'}"
      >
        <span>Cancelled</span>
        <span class="inline-flex h-5 min-w-[20px] shrink-0 items-center justify-center rounded-full px-1.5 pt-[2px] text-xs font-bold leading-none text-center transition-all {activeTab === 'cancelled' ? 'bg-[#E6FA50] text-[#06121A]' : 'bg-white/[0.08] text-[#F7F7F7]/60'}">
          {cancelledCount}
        </span>
      </button>

      <button
        type="button"
        onclick={() => (activeTab = "refunds")}
        class="flex cursor-pointer items-center gap-2.5 rounded-xl border px-4 py-2 text-sm font-semibold transition-all select-none {activeTab === 'refunds'
          ? 'border-[#E6FA50]/30 bg-[#E6FA50]/10 text-[#E6FA50]'
          : 'border-white/[0.08] bg-white/[0.02] text-[#F7F7F7]/40 hover:bg-white/[0.05] hover:text-[#F7F7F7]/60'}"
      >
        <span>Refunds</span>
        <span class="inline-flex h-5 min-w-[20px] shrink-0 items-center justify-center rounded-full px-1.5 pt-[2px] text-xs font-bold leading-none text-center transition-all {activeTab === 'refunds' ? 'bg-[#E6FA50] text-[#06121A]' : 'bg-white/[0.08] text-[#F7F7F7]/60'}">
          {refundCount}
        </span>
      </button>

      <button
        type="button"
        onclick={() => (activeTab = "disputes")}
        class="flex cursor-pointer items-center gap-2.5 rounded-xl border px-4 py-2 text-sm font-semibold transition-all select-none {activeTab === 'disputes'
          ? 'border-[#E6FA50]/30 bg-[#E6FA50]/10 text-[#E6FA50]'
          : 'border-white/[0.08] bg-white/[0.02] text-[#F7F7F7]/40 hover:bg-white/[0.05] hover:text-[#F7F7F7]/60'}"
      >
        <span>Disputes</span>
        <span class="inline-flex h-5 min-w-[20px] shrink-0 items-center justify-center rounded-full px-1.5 pt-[2px] text-xs font-bold leading-none text-center transition-all {activeTab === 'disputes' ? 'bg-[#E6FA50] text-[#06121A]' : 'bg-white/[0.08] text-[#F7F7F7]/60'}">
          {disputeCount}
        </span>
      </button>
    </div>
  </section>

  <!-- Content Section -->
  <section class="container mt-8">
    {#if isLoading}
      <div class="space-y-4">
        {#each Array.from({ length: 3 }) as _, i}
          <div
            class="h-28 animate-pulse rounded-2xl border border-white/[0.06] bg-[#0C1B26]"
          ></div>
        {/each}
      </div>
    {:else if activeTab === "refunds"}
      {#if refunds.length === 0}
        <div class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-12 md:p-16 text-center w-full my-4">
          <div class="flex h-12 w-12 items-center justify-center rounded-2xl bg-white/[0.04] text-[#E6FA50] mx-auto mb-4">
            <RotateCcw class="h-6 w-6" />
          </div>
          <h2 class="heading-2 text-xl font-bold text-[#F7F7F7]">No refund requests</h2>
          <p class="body mt-2 text-[#F7F7F7]/40">
            You don't have any pending or processed refund requests.
          </p>
          <a
            href="/venues"
            class="btn-lime label inline-flex items-center justify-center rounded-full px-6 py-2.5 font-semibold text-sm bg-[#E6FA50] text-[#06121A] hover:bg-[#E6FA50]/90 transition-all mt-6"
          >
            Browse venues
          </a>
        </div>
      {:else}
        <div class="space-y-3">
          {#each refunds as refund (refund.id)}
            <div
              class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-5 flex flex-col md:flex-row md:items-center justify-between gap-4"
            >
              <div>
                <span class="caption uppercase text-[#50C8C8]">{refund.status}</span>
                <h3 class="heading-3 mt-1 text-[#F7F7F7]">
                  Refund #{refund.id.slice(0, 8)}
                </h3>
                <p class="caption mt-1 text-[#F7F7F7]/40">
                  Reason: {refund.reason || "Booking cancellation"}
                </p>
              </div>
              <p class="price text-[#E6FA50]">
                Rp {(refund.amount / 1000).toFixed(0)}K
              </p>
            </div>
          {/each}
        </div>
      {/if}
    {:else if activeTab === "disputes"}
      {#if disputes.length === 0}
        <div class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-12 md:p-16 text-center w-full my-4">
          <div class="flex h-12 w-12 items-center justify-center rounded-2xl bg-white/[0.04] text-[#E6FA50] mx-auto mb-4">
            <Star class="h-6 w-6" />
          </div>
          <h2 class="heading-2 text-xl font-bold text-[#F7F7F7]">No dispute tickets</h2>
          <p class="body mt-2 text-[#F7F7F7]/40">
            You haven't filed any player disputes or issues.
          </p>
          <a
            href="/venues"
            class="btn-lime label inline-flex items-center justify-center rounded-full px-6 py-2.5 font-semibold text-sm bg-[#E6FA50] text-[#06121A] hover:bg-[#E6FA50]/90 transition-all mt-6"
          >
            Browse venues
          </a>
        </div>
      {:else}
        <div class="space-y-3">
          {#each disputes as dispute (dispute.id)}
            <div
              class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-5 flex flex-col md:flex-row md:items-center justify-between gap-4"
            >
              <div>
                <span class="caption uppercase text-amber-400">{dispute.status}</span>
                <h3 class="heading-3 mt-1 text-[#F7F7F7]">
                  {dispute.title || dispute.issueType}
                </h3>
                <p class="caption mt-1 text-[#F7F7F7]/40">
                  {dispute.description}
                </p>
              </div>
            </div>
          {/each}
        </div>
      {/if}
    {:else if currentList.length === 0}
      <div class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-12 md:p-16 text-center w-full my-4">
        <div class="flex h-12 w-12 items-center justify-center rounded-2xl bg-white/[0.04] text-[#E6FA50] mx-auto mb-4">
          <CalendarDays class="h-6 w-6" />
        </div>
        <h2 class="heading-2 text-xl font-bold text-[#F7F7F7]">No {activeTab} bookings</h2>
        <p class="body mt-2 text-[#F7F7F7]/40">
          When you book a court it'll show up here.
        </p>
        <a
          href="/venues"
          class="btn-lime label inline-flex items-center justify-center rounded-full px-6 py-2.5 font-semibold text-sm bg-[#E6FA50] text-[#06121A] hover:bg-[#E6FA50]/90 transition-all mt-6"
        >
          Browse venues
        </a>
      </div>
    {:else}
      <div class="space-y-3">
        {#each currentList as b, i (b.id)}
          {@const images = [IMG.venue1, IMG.venue2, IMG.venue3]}
          {@const isUpcoming = activeTab === "upcoming" || b.status === "CONFIRMED" || b.status === "PENDING_PAYMENT"}

          <!-- Unified Card Layout for All Booking Items (Upcoming, Past, Cancelled) -->
          <div
            class="group rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-4 md:p-5 flex flex-col md:flex-row md:items-center justify-between gap-4 transition-all duration-200 hover:border-white/[0.12]"
          >
            <div class="flex items-center gap-4 min-w-0">
              <div class="h-14 w-14 shrink-0 overflow-hidden rounded-xl bg-white/5">
                <img
                  src={b.venue?.imageUrl || images[i % images.length]}
                  alt={b.venue?.name}
                  class="h-full w-full object-cover"
                />
              </div>

              <div class="min-w-0 space-y-1">
                <div class="flex items-center gap-2.5 flex-wrap">
                  <h3 class="heading-3 text-[#F7F7F7] font-bold text-base truncate">
                    {b.venue?.name || "Padel Court"}
                  </h3>
                  <span class="caption rounded-full px-2.5 py-0.5 text-xs font-semibold uppercase {getStatusStyle(b.status || 'CONFIRMED')}">
                    {(b.status || "CONFIRMED").replace(/_/g, " ")}
                  </span>
                  <span class="caption text-xs text-[#F7F7F7]/25 font-mono">
                    #{b.id.slice(0, 8)}
                  </span>
                </div>

                <div class="caption flex flex-wrap items-center gap-2 text-xs text-[#F7F7F7]/50">
                  <span class="font-medium text-[#F7F7F7]/70">{b.court?.name || "Court A"}</span>
                  <span>·</span>
                  <span class="inline-flex items-center gap-1">
                    <MapPin class="h-3 w-3 text-[#50C8C8]" />
                    {b.venue?.city || b.venue?.location || "Jakarta"}
                  </span>
                  <span>·</span>
                  <span class="inline-flex items-center gap-1">
                    <CalendarDays class="h-3 w-3 text-[#50C8C8]" />
                    {formatBookingDate(b.bookingDate)}
                  </span>
                  <span>·</span>
                  <span class="inline-flex items-center gap-1">
                    <Clock class="h-3 w-3 text-[#50C8C8]" />
                    {formatBookingTimeRange(b.startsAt, b.endsAt)}
                  </span>
                </div>
              </div>
            </div>

            <div class="flex items-center justify-between md:justify-end gap-4 shrink-0 border-t border-white/[0.04] pt-3 md:border-none md:pt-0">
              <span class="price text-base md:text-lg font-bold text-[#E6FA50]">
                Rp {((b.finalAmount || b.amount || 200000) / 1000).toFixed(0)}K
              </span>

              {#if isUpcoming}
                <div class="flex items-center gap-2">
                  <a
                    href="/booking/{b.id}/invite"
                    class="caption flex h-9 items-center gap-1.5 rounded-full border border-white/[0.08] bg-white/[0.03] px-3.5 text-xs font-semibold text-[#F7F7F7]/70 hover:bg-white/[0.08] hover:text-[#F7F7F7] transition-all"
                  >
                    <Share2 class="h-3.5 w-3.5" /> Invite Squad
                  </a>
                  <a
                    href="/bookings/{b.id}"
                    class="caption flex h-9 items-center gap-1.5 rounded-full bg-[#E6FA50] px-4 text-xs font-bold text-[#06121A] hover:bg-[#d4e845] transition-all"
                  >
                    Details <ArrowRight class="h-3.5 w-3.5" />
                  </a>
                </div>
              {:else}
                <div class="flex items-center gap-1.5">
                  <a
                    href="/bookings/{b.id}"
                    class="flex h-9 w-9 items-center justify-center rounded-xl bg-white/[0.03] text-[#F7F7F7]/60 transition-colors hover:bg-white/[0.08] hover:text-[#F7F7F7]"
                    aria-label="View booking details"
                  >
                    <Eye class="h-4 w-4" />
                  </a>
                  <button
                    type="button"
                    onclick={() => openDisputeModal(b)}
                    class="flex h-9 w-9 items-center justify-center rounded-xl bg-white/[0.03] text-[#F7F7F7]/60 transition-colors hover:bg-white/[0.08] hover:text-red-400"
                    aria-label="Report issue"
                  >
                    <AlertTriangle class="h-4 w-4" />
                  </button>
                </div>
              {/if}
            </div>
          </div>
        {/each}
      </div>
    {/if}
  </section>

  <!-- Report an Issue / Dispute Modal (1:1 Image #121) -->
  {#if showDisputeModal}
    <div class="fixed inset-0 z-50 flex items-center justify-center bg-black/75 p-4 backdrop-blur-md">
      <div class="w-full max-w-md rounded-2xl border border-white/[0.08] bg-[#0C1B26] p-6 space-y-5 shadow-2xl">
        <div>
          <p class="text-xs font-semibold tracking-wider text-[#50C8C8] uppercase">
            REPORT AN ISSUE
          </p>
          <h2 class="heading-2 text-2xl font-bold text-[#F7F7F7] mt-1">
            What went wrong?
          </h2>
        </div>

        {#if disputeError}
          <div class="rounded-xl border border-red-500/20 bg-red-500/10 p-3 text-xs text-red-400">
            {disputeError}
          </div>
        {/if}

        <div class="space-y-4">
          <!-- Issue type dropdown (Custom Floating Popover 1:1 Image #125 & Image #126) -->
          <div class="space-y-1.5 relative">
            <span class="body-sm text-xs font-medium text-[#F7F7F7]/60 block">
              Issue type
            </span>
            <button
              type="button"
              onclick={() => {
                isIssueTypeOpen = !isIssueTypeOpen;
                isPriorityOpen = false;
              }}
              class="flex w-full items-center justify-between rounded-xl border px-4 py-3 text-sm transition-colors {isIssueTypeOpen
                ? 'border-[#E6FA50]/40 bg-[#06121A] text-[#F7F7F7]'
                : 'border-white/[0.08] bg-[#06121A] text-[#F7F7F7] hover:border-white/[0.15]'}"
            >
              <span>{disputeIssueType}</span>
              <ChevronDown
                class="h-4 w-4 transition-transform duration-200 {isIssueTypeOpen ? 'rotate-180 text-[#E6FA50]' : 'text-[#F7F7F7]/40'}"
              />
            </button>

            {#if isIssueTypeOpen}
              <div
                class="absolute left-0 right-0 top-full mt-1.5 z-50 rounded-2xl border border-[#E6FA50]/40 bg-[#0C1B26] p-1.5 shadow-2xl backdrop-blur-xl animate-in fade-in-50 zoom-in-95 space-y-0.5"
              >
                {#each ISSUE_TYPE_OPTIONS as option}
                  {@const selected = disputeIssueType === option}
                  <button
                    type="button"
                    onclick={() => {
                      disputeIssueType = option;
                      isIssueTypeOpen = false;
                    }}
                    class="flex w-full items-center justify-between rounded-xl px-3.5 py-2.5 text-sm transition-all {selected
                      ? 'bg-[#E6FA50]/10 text-[#E6FA50] font-semibold'
                      : 'text-[#F7F7F7]/70 hover:bg-white/[0.04] hover:text-[#F7F7F7]'}"
                  >
                    <span>{option}</span>
                    {#if selected}
                      <Check class="h-4 w-4 text-[#E6FA50]" />
                    {/if}
                  </button>
                {/each}
              </div>
            {/if}
          </div>

          <!-- Priority dropdown (Custom Floating Popover 1:1 Image #125 & Image #126) -->
          <div class="space-y-1.5 relative">
            <span class="body-sm text-xs font-medium text-[#F7F7F7]/60 block">
              Priority
            </span>
            <button
              type="button"
              onclick={() => {
                isPriorityOpen = !isPriorityOpen;
                isIssueTypeOpen = false;
              }}
              class="flex w-full items-center justify-between rounded-xl border px-4 py-3 text-sm transition-colors {isPriorityOpen
                ? 'border-[#E6FA50]/40 bg-[#06121A] text-[#F7F7F7]'
                : 'border-white/[0.08] bg-[#06121A] text-[#F7F7F7] hover:border-white/[0.15]'}"
            >
              <span>{disputePriority}</span>
              <ChevronDown
                class="h-4 w-4 transition-transform duration-200 {isPriorityOpen ? 'rotate-180 text-[#E6FA50]' : 'text-[#F7F7F7]/40'}"
              />
            </button>

            {#if isPriorityOpen}
              <div
                class="absolute left-0 right-0 top-full mt-1.5 z-50 rounded-2xl border border-[#E6FA50]/40 bg-[#0C1B26] p-1.5 shadow-2xl backdrop-blur-xl animate-in fade-in-50 zoom-in-95 space-y-0.5"
              >
                {#each PRIORITY_OPTIONS as option}
                  {@const selected = disputePriority === option}
                  <button
                    type="button"
                    onclick={() => {
                      disputePriority = option;
                      isPriorityOpen = false;
                    }}
                    class="flex w-full items-center justify-between rounded-xl px-3.5 py-2.5 text-sm transition-all {selected
                      ? 'bg-[#E6FA50]/10 text-[#E6FA50] font-semibold'
                      : 'text-[#F7F7F7]/70 hover:bg-white/[0.04] hover:text-[#F7F7F7]'}"
                  >
                    <span>{option}</span>
                    {#if selected}
                      <Check class="h-4 w-4 text-[#E6FA50]" />
                    {/if}
                  </button>
                {/each}
              </div>
            {/if}
          </div>

          <!-- Description textarea -->
          <div class="space-y-1.5">
            <label for="disputeDescription" class="body-sm text-xs font-medium text-[#F7F7F7]/60">
              Description
            </label>
            <textarea
              id="disputeDescription"
              bind:value={disputeDescription}
              rows={4}
              placeholder="Describe the issue you experienced..."
              class="w-full resize-none rounded-xl border border-white/[0.08] bg-[#06121A] px-4 py-3 text-sm text-[#F7F7F7] placeholder:text-[#F7F7F7]/25 focus:border-[#50C8C8]/40 focus:outline-none"
            ></textarea>
          </div>
        </div>

        <div class="flex items-center justify-end gap-3 pt-2">
          <button
            type="button"
            onclick={() => (showDisputeModal = false)}
            class="px-5 py-2.5 rounded-xl border border-white/[0.08] bg-white/[0.02] text-xs font-semibold text-[#F7F7F7]/80 transition-colors hover:bg-white/[0.05] hover:text-[#F7F7F7]"
          >
            Cancel
          </button>
          <button
            type="button"
            disabled={isSubmittingDispute}
            onclick={submitDispute}
            class="btn-lime px-5 py-2.5 rounded-xl text-xs font-bold text-[#06121A] transition-all disabled:opacity-50"
          >
            {isSubmittingDispute ? "Submitting..." : "Submit Report"}
          </button>
        </div>
      </div>
    </div>
  {/if}

  <!-- Toast notification -->
  {#if toast}
    <div class="fixed bottom-6 left-1/2 z-50 -translate-x-1/2 rounded-xl border border-white/[0.06] bg-[#0C1B26] px-5 py-3 shadow-2xl">
      <p class="caption text-[#F7F7F7]/80">{toast}</p>
    </div>
  {/if}
</div>

// apps/web/src/app/profile/bookings/page.tsx
"use client";

import Link from "next/link";
import { useState } from "react";
import { MapPin, Clock, Users, Share2, CalendarDays, Trophy, Timer, ArrowRight } from "lucide-react";
import { mockBookings } from "@/mock/bookings";
import { mockVenues } from "@/mock/venues";
import { mockCourts } from "@/mock/courts";
import { PlayerAvatarStack } from "@/components/ui/player-avatar-stack";
import { padelImg } from "@/lib/images";

const IMG = {
  venue1: padelImg(600),
  venue2: padelImg(600),
  venue3: padelImg(600),
};

type TabKey = "upcoming" | "past" | "cancelled";

export default function BookingsPage() {
  const [activeTab, setActiveTab] = useState<TabKey>("upcoming");

  const upcoming = mockBookings.filter((b) => b.status === "confirmed" || b.status === "pending");
  const past = mockBookings.filter((b) => b.status === "completed");
  const cancelled = mockBookings.filter((b) => b.status === "cancelled");

  const tabData: Record<TabKey, typeof mockBookings> = {
    upcoming,
    past,
    cancelled,
  };

  const nextBooking = upcoming[0];
  const nextVenue = nextBooking ? mockVenues.find((v) => v.id === nextBooking.venueId) : null;
  const nextCourt = nextBooking ? mockCourts.find((c) => c.id === nextBooking.courtId) : null;

  const totalBookings = mockBookings.length;
  const hoursPlayed = mockBookings.filter((b) => b.status === "completed").length;

  return (
    <div className="min-h-screen pt-28">
      {/* ─── PAGE HEADER ─── */}
      <section className="container pb-8">
        <h1 className="heading-1 text-3xl text-[#F7F7F7] md:text-4xl">
          My <span className="text-[#E6FA50]">Bookings</span>
        </h1>
        <p className="mt-2 text-sm font-light text-[#F7F7F7]/40">
          Manage your upcoming matches and booking history.
        </p>
      </section>

      {/* ─── YOUR NEXT MATCH ─── */}
      {nextBooking && nextVenue && nextCourt && (
        <section className="container pb-10">
          <span className="section-label">Your Next Match</span>

          <div className="mt-5 grid grid-cols-1 overflow-hidden rounded-2xl border border-white/[0.06] bg-[#0C1B26] lg:grid-cols-[1.85fr_1fr]">
            {/* Content — left, dominant */}
            <div className="flex flex-col justify-center p-7 md:p-9">
              <div className="flex items-center gap-3">
                <span className="inline-block rounded-full bg-[#E6FA50]/10 px-3 py-1 text-[10px] font-medium uppercase tracking-[0.15em] text-[#E6FA50]">
                  {nextBooking.status}
                </span>
                <span className="caption text-[#F7F7F7]/25">In 2 days</span>
              </div>

              <h2 className="heading-1 mt-4 text-2xl text-[#F7F7F7] md:text-3xl">
                {nextVenue.name}
              </h2>

              <p className="mt-2 flex items-center gap-2 text-sm text-[#F7F7F7]/40">
                <MapPin className="h-3.5 w-3.5" />
                {nextVenue.location} · {nextVenue.city}
              </p>

              {/* Detail cards */}
              <div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">
                <DetailChip icon={CalendarDays} label="Date" value={nextBooking.bookingDate} />
                <DetailChip icon={Clock} label="Time" value={`${nextBooking.startTime} – ${nextBooking.endTime}`} />
                <DetailChip icon={MapPin} label="Court" value={`${nextCourt.name} · ${nextCourt.type}`} />
                <DetailChip icon={Timer} label="Price" value={`Rp ${(nextBooking.totalAmount / 1000).toFixed(0)}K`} />
              </div>

              {/* Players */}
              <div className="mt-5">
                <PlayerAvatarStack
                  players={[
                    { id: "u1", name: "Andi Pratama", avatarUrl: "https://i.pravatar.cc/150?img=11" },
                    { id: "u2", name: "Sari Dewi", avatarUrl: "https://i.pravatar.cc/150?img=32" },
                  ]}
                  totalSpots={4}
                  size={32}
                />
              </div>

              {/* CTAs */}
              <div className="mt-6 flex flex-wrap gap-3">
                <Link
                  href={`/booking/${nextBooking.id}/invite`}
                  className="btn-lime inline-flex h-10 items-center gap-2 rounded-full px-6 text-[11px] font-semibold uppercase tracking-[0.08em]"
                >
                  <Users className="h-3.5 w-3.5" />
                  Invite Friends
                </Link>
                <button className="inline-flex h-10 items-center gap-2 rounded-full border border-white/10 px-6 text-[11px] font-medium uppercase tracking-[0.08em] text-[#F7F7F7]/50 transition-colors hover:border-white/20 hover:text-[#F7F7F7]">
                  <Share2 className="h-3.5 w-3.5" />
                  Share Match
                </button>
              </div>
            </div>

            {/* Image — right, secondary */}
            <div className="relative hidden overflow-hidden lg:block">
              <img
                src={IMG.venue1}
                alt={nextVenue.name}
                className="absolute inset-0 h-full w-full object-cover"
              />
            </div>
          </div>
        </section>
      )}

      {/* ─── STATS ─── */}
      <section className="container pb-10">
        <div className="grid grid-cols-2 gap-4 md:grid-cols-4">
          <StatCard icon={CalendarDays} value={totalBookings.toString()} label="Total Bookings" />
          <StatCard icon={Timer} value={`${hoursPlayed}h`} label="Hours Played" />
          <StatCard icon={Trophy} value="12" label="Matches Joined" />
          <StatCard icon={Users} value="8" label="Friends Invited" />
        </div>
      </section>

      {/* ─── TABS ─── */}
      <section className="container pb-section-sm">
        <div className="flex gap-1 border-b border-white/[0.06] mb-8">
          {(["upcoming", "past", "cancelled"] as TabKey[]).map((tab) => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              className={`relative px-5 py-3 text-[11px] font-medium uppercase tracking-[0.1em] transition-colors ${
                activeTab === tab
                  ? "text-[#E6FA50]"
                  : "text-[#F7F7F7]/30 hover:text-[#F7F7F7]/60"
              }`}
            >
              {tab}
              {activeTab === tab && (
                <span className="absolute bottom-0 left-0 right-0 h-[2px] bg-[#E6FA50]" />
              )}
            </button>
          ))}
        </div>

        {/* Booking list */}
        <div className="space-y-3">
          {tabData[activeTab].length === 0 ? (
            <div className="py-16 text-center">
              <p className="text-sm text-[#F7F7F7]/30">No {activeTab} bookings.</p>
            </div>
          ) : (
            tabData[activeTab].map((booking, i) => (
              <BookingRow
                key={booking.id}
                booking={booking}
                index={i}
                muted={activeTab !== "upcoming"}
              />
            ))
          )}
        </div>
      </section>

      {/* ─── COMMUNITY ─── */}
      <section className="border-t border-white/[0.04] py-section-sm">
        <div className="container">
          <div className="flex items-center justify-between mb-6">
            <h2 className="heading-1 text-xl text-[#F7F7F7]">Community</h2>
            <Link href="#" className="group flex items-center gap-2 label text-[#F7F7F7]/30 transition-colors hover:text-[#E6FA50]">
              View all
              <ArrowRight className="h-3.5 w-3.5 transition-transform group-hover:translate-x-0.5" />
            </Link>
          </div>

          <div className="grid grid-cols-1 gap-4 md:grid-cols-3">
            <ActivityCard type="match" title="Open Match — Padel Bali Arena" subtitle="Tomorrow · 18:00 · 2 spots left" />
            <ActivityCard type="friend" title="Andi joined your session" subtitle="Jakarta Padel Club · Sat, 31 May" />
            <ActivityCard type="session" title="New session near you" subtitle="Surabaya Padel Center · Sun, 1 Jun" />
          </div>
        </div>
      </section>
    </div>
  );
}

function DetailChip({
  icon: Icon,
  label,
  value,
}: {
  icon: React.ComponentType<{ className?: string }>;
  label: string;
  value: string;
}) {
  return (
    <div className="rounded-xl bg-white/[0.03] p-3">
      <Icon className="h-3.5 w-3.5 text-[#50C8C8]" />
      <p className="heading-3 mt-1.5 text-[13px] text-[#F7F7F7]">{value}</p>
      <p className="caption mt-0.5 text-[#F7F7F7]/20">{label}</p>
    </div>
  );
}

function StatCard({
  icon: Icon,
  value,
  label,
}: {
  icon: React.ComponentType<{ className?: string }>;
  value: string;
  label: string;
}) {
  return (
    <div className="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-5">
      <Icon className="h-4 w-4 text-[#50C8C8]" />
      <p className="metric mt-3 text-2xl text-[#E6FA50]">{value}</p>
      <p className="caption mt-1 text-[#F7F7F7]/30">{label}</p>
    </div>
  );
}

function BookingRow({
  booking,
  index,
  muted = false,
}: {
  booking: (typeof mockBookings)[0];
  index: number;
  muted?: boolean;
}) {
  const court = mockCourts.find((c) => c.id === booking.courtId);
  const venue = mockVenues.find((v) => v.id === booking.venueId);
  const images = [IMG.venue1, IMG.venue2, IMG.venue3];

  return (
    <Link href={`/booking/${booking.id}/payment`} className="group block">
      <div className={`flex items-center gap-4 rounded-xl border p-4 transition-all duration-200 ${
        muted
          ? "border-white/[0.03] bg-white/[0.01] group-hover:border-white/[0.06]"
          : "border-white/[0.06] bg-[#0C1B26] group-hover:border-[#E6FA50]/15"
      }`}>
        <div className="hidden h-12 w-12 shrink-0 overflow-hidden rounded-lg sm:block">
          <img src={images[index % images.length]} alt={venue?.name ?? ""} className="h-full w-full object-cover" />
        </div>

        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-2">
            <h3 className={`heading-3 truncate text-sm ${muted ? "text-[#F7F7F7]/40" : "text-[#F7F7F7]"}`}>
              {venue?.name ?? "Unknown Venue"}
            </h3>
            <StatusPill status={booking.status} />
          </div>
          <p className={`mt-1 flex items-center gap-3 caption ${muted ? "text-[#F7F7F7]/20" : "text-[#F7F7F7]/35"}`}>
            <span className="flex items-center gap-1"><MapPin className="h-3 w-3" />{court?.name}</span>
            <span className="flex items-center gap-1"><CalendarDays className="h-3 w-3" />{booking.bookingDate}</span>
            <span className="flex items-center gap-1"><Clock className="h-3 w-3" />{booking.startTime}–{booking.endTime}</span>
          </p>
        </div>

        <p className={`shrink-0 price text-base ${muted ? "text-[#F7F7F7]/20" : "text-[#F7F7F7]"}`}>
          Rp {(booking.totalAmount / 1000).toFixed(0)}K
        </p>
      </div>
    </Link>
  );
}

function StatusPill({ status }: { status: string }) {
  const styles: Record<string, string> = {
    confirmed: "bg-[#E6FA50]/10 text-[#E6FA50]",
    pending: "bg-[#50C8C8]/10 text-[#50C8C8]",
    completed: "bg-white/[0.04] text-[#F7F7F7]/30",
    cancelled: "bg-red-500/10 text-red-400/70",
  };

  return (
    <span className={`shrink-0 rounded-full px-2 py-0.5 text-[10px] font-medium uppercase tracking-[0.1em] ${styles[status] ?? "bg-white/5 text-[#F7F7F7]/30"}`}>
      {status}
    </span>
  );
}

function ActivityCard({ type, title, subtitle }: { type: "match" | "friend" | "session"; title: string; subtitle: string }) {
  const icons = { match: Trophy, friend: Users, session: CalendarDays };
  const Icon = icons[type];

  return (
    <div className="rounded-xl border border-white/[0.06] bg-[#0C1B26] p-5 transition-all duration-200 hover:border-[#E6FA50]/15">
      <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#E6FA50]/10">
        <Icon className="h-4 w-4 text-[#E6FA50]" />
      </div>
      <h4 className="heading-3 mt-4 text-sm text-[#F7F7F7]">{title}</h4>
      <p className="caption mt-1 text-[#F7F7F7]/30">{subtitle}</p>
    </div>
  );
}
