// apps/web/src/routes/(marketing)/venues/[id]/book/+page.svelte
<script lang="ts">
import {
  AlertCircle,
  ArrowLeft,
  Calendar,
  ChevronLeft,
  ChevronRight,
  Clock,
  Info,
  Loader2,
  MapPin,
  ShieldCheck,
  Tag,
  Ticket,
  Users,
  X,
} from "lucide-svelte";
import { goto } from "$app/navigation";
import { page } from "$app/state";
import { api } from "$lib/api/client";
import { authStore } from "$lib/auth/store.svelte";
import EmptyState from "$lib/components/ui/empty-state.svelte";
import { formatBookingDate, formatBookingTimeRange } from "$lib/format";

const venueId = $derived((page.params.id as string) || "");

let venue = $state<any | null>(null);
let courts = $state<any[]>([]);

// Selection states
let selectedDate = $state(new Date().toISOString().split("T")[0]);
let selectedCourtId = $state("");
let selectedSlot = $state<any | null>(null);

let availability = $state<any | null>(null);
let isLoadingVenue = $state(true);
let isLoadingAvailability = $state(false);
let isSubmitting = $state(false);

// Date pagination state (7 days per page, no scrollbar)
let datePage = $state(0);

// Protection & Voucher states
let isRefundProtection = $state(true);
let voucherCode = $state("");
let voucherDiscount = $state(0);
let voucherError = $state<string | null>(null);
let isValidatingVoucher = $state(false);
let error = $state<string | null>(null);

// 14 days ahead
const dateOptions = $derived.by(() => {
  const list: { iso: string; day: string; dateNum: number; full: string }[] =
    [];
  const today = new Date();
  for (let i = 0; i < 14; i++) {
    const d = new Date(today);
    d.setDate(today.getDate() + i);
    const iso = d.toISOString().split("T")[0];
    const day = d.toLocaleDateString("en-US", { weekday: "short" });
    const dateNum = d.getDate();
    list.push({ iso, day, dateNum, full: formatBookingDate(d) });
  }
  return list;
});

// Currently visible 7 dates for the active page
const visibleDateOptions = $derived.by(() => {
  const start = datePage * 7;
  return dateOptions.slice(start, start + 7);
});

function prevDatePage() {
  if (datePage > 0) datePage--;
}

function nextDatePage() {
  if ((datePage + 1) * 7 < dateOptions.length) datePage++;
}

async function loadData() {
  if (!venueId) return;
  isLoadingVenue = true;
  try {
    const [vRes, cRes] = await Promise.all([
      api.venues({ id: venueId }).get(),
      api.venues({ id: venueId }).courts.get(),
    ]);

    if (vRes.data) venue = vRes.data;
    if (cRes.data && cRes.data.length > 0) {
      courts = cRes.data;
      if (!selectedCourtId) {
        selectedCourtId = courts[0].id;
      }
    }
  } catch (e) {
    console.warn("Load error:", e);
  } finally {
    isLoadingVenue = false;
  }
}

async function loadAvailability() {
  if (!venueId || !selectedDate) return;
  isLoadingAvailability = true;
  try {
    const res = await api.venues({ id: venueId }).availability.get({
      query: { date: selectedDate, courtId: selectedCourtId || undefined },
    });
    if (res.data) {
      availability = res.data;
    }
  } catch (e) {
    console.warn("Availability fetch error:", e);
  } finally {
    isLoadingAvailability = false;
  }
}

// Reactive auth tracking to support hard reload
$effect(() => {
  if (authStore.isInitialized) {
    loadData();
  }
});

$effect(() => {
  if (venueId && selectedDate) {
    loadAvailability();
  }
});

const activeCourtSlots = $derived.by(() => {
  if (!availability?.courts) return [];
  const matched = availability.courts.find(
    (c: any) => c.id === selectedCourtId,
  );
  return matched ? matched.slots : (availability.courts[0]?.slots ?? []);
});

const selectedCourt = $derived(
  courts.find((c) => c.id === selectedCourtId) ?? courts[0],
);

// Calculations
const courtRentalPrice = $derived(selectedSlot ? selectedSlot.price : 0);
const platformFee = $derived(
  selectedSlot ? Math.round(selectedSlot.price * 0.05) : 0,
);
const refundProtectionFee = $derived(isRefundProtection ? 15000 : 0);
const totalDue = $derived(
  Math.max(
    0,
    courtRentalPrice + platformFee + refundProtectionFee - voucherDiscount,
  ),
);

async function handleApplyVoucher() {
  if (!voucherCode.trim()) return;
  isValidatingVoucher = true;
  voucherError = null;
  try {
    const amount = selectedSlot ? selectedSlot.price : 200000;
    const res = await api.vouchers.validate.post({
      code: voucherCode.trim(),
      amount,
    });
    if (res.data) {
      voucherDiscount = res.data.discount;
    }
  } catch (err: any) {
    voucherError = err.message || "Invalid voucher code";
    voucherDiscount = 0;
  } finally {
    isValidatingVoucher = false;
  }
}

async function handleCreateBooking(e: SubmitEvent) {
  e.preventDefault();
  if (!authStore.user) {
    goto(`/auth/login?next=/venues/${venueId}/book`);
    return;
  }
  if (!selectedCourtId || !selectedDate || !selectedSlot) {
    error = "Please select a court, date, and time slot.";
    return;
  }

  isSubmitting = true;
  error = null;

  try {
    const token = await authStore.firebaseUser?.getIdToken();
    if (!token) return;

    const startsAt = selectedSlot.startsAt;
    const [h, m] = startsAt.split(":").map(Number);
    const endsAt = `${String(h + 1).padStart(2, "0")}:${String(m).padStart(2, "0")}`;

    const res = await api.bookings.post(
      {
        venueId,
        courtId: selectedCourtId,
        bookingDate: selectedDate,
        startsAt,
        endsAt,
        voucherCode: voucherCode || undefined,
      },
      { headers: { authorization: `Bearer ${token}` } },
    );

    if (res.data) {
      goto(`/booking/${res.data.id}/payment`);
    }
  } catch (err: any) {
    error = err.message || "Booking creation failed";
  } finally {
    isSubmitting = false;
  }
}
</script>

<svelte:head>
  <title>Book Court | {venue?.name ?? "PadelHive"}</title>
</svelte:head>

<div class="min-h-screen pt-20 pb-24 bg-[#06121A]">
  {#if isLoadingVenue}
    <div class="container py-12 space-y-6">
      <div class="h-8 w-48 animate-pulse rounded-md bg-white/[0.04]"></div>
      <div class="h-[400px] animate-pulse rounded-2xl bg-white/[0.04]"></div>
    </div>
  {:else if !venue}
    <div class="container py-16 text-center">
      <EmptyState
        icon={MapPin}
        title="Venue not found"
        description="This venue is unavailable or no longer listed."
        actionLabel="Back to venues"
        actionHref="/venues"
      />
    </div>
  {:else}
    <div class="container pt-6">
      <!-- Back Navigation Link (Linear Icon Box Style) -->
      <a
        href="/venues/{venue.id}"
        class="group inline-flex items-center gap-3 text-xs font-medium text-[#F7F7F7]/60 transition-colors hover:text-[#F7F7F7]"
      >
        <div
          class="flex h-7 w-7 items-center justify-center rounded-lg border border-white/[0.08] bg-white/[0.03] text-[#F7F7F7]/40 transition-all duration-200 group-hover:border-[#E6FA50]/40 group-hover:bg-[#E6FA50]/10 group-hover:text-[#E6FA50]"
        >
          <ArrowLeft class="h-3.5 w-3.5" />
        </div>
        <span>Back to {venue.name}</span>
      </a>

      <!-- Page Title & Subhead -->
      <div class="mt-4 mb-8">
        <h1 class="heading-1 text-[#F7F7F7]">
          Book a <span class="text-[#E6FA50]">Court</span>
        </h1>
        <p class="body mt-1 flex items-center gap-2 text-[#F7F7F7]/40">
          <MapPin class="h-3.5 w-3.5 text-[#50C8C8]" />
          <span>{venue.name} · {venue.city || "Bali"}</span>
        </p>
      </div>

      {#if error}
        <div class="mb-6 rounded-xl border border-red-500/20 bg-red-500/10 p-4 flex items-center gap-3">
          <AlertCircle class="h-5 w-5 shrink-0 text-red-400" />
          <p class="body text-red-100/90">{error}</p>
        </div>
      {/if}

      <form onsubmit={handleCreateBooking} class="grid grid-cols-1 gap-8 lg:grid-cols-[1fr_360px]">
        <!-- Left Column: Selection Steps 1, 2, 3 -->
        <div class="space-y-8 min-w-0">
          <!-- Step 1: SELECT COURT -->
          <div class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6 space-y-4 shadow-xl">
            <div class="flex items-center gap-3">
              <div class="flex h-6 w-6 items-center justify-center rounded-full bg-[#50C8C8]/15 text-xs font-bold text-[#50C8C8]">
                1
              </div>
              <h2 class="text-xs font-semibold tracking-wider text-[#50C8C8] uppercase">
                SELECT COURT
              </h2>
            </div>

            <div class="grid grid-cols-1 sm:grid-cols-2 gap-3 pt-1">
              {#each courts as c}
                <button
                  type="button"
                  onclick={() => {
                    selectedCourtId = c.id;
                    selectedSlot = null;
                  }}
                  class="flex flex-col items-start rounded-xl border p-4 transition-all text-left {selectedCourtId ===
                  c.id
                    ? 'border-[#E6FA50] bg-[#E6FA50]/10 shadow-sm'
                    : 'border-white/[0.06] bg-white/[0.015] hover:border-white/[0.12]'}"
                >
                  <div class="flex items-center justify-between w-full">
                    <span class="heading-3 text-[#F7F7F7]">{c.name}</span>
                    <span class="caption rounded px-2 py-0.5 uppercase font-medium bg-white/[0.06] text-[#F7F7F7]/60">
                      {c.type}
                    </span>
                  </div>
                  <span class="caption mt-2 text-[#50C8C8] font-semibold">
                    From Rp {((c.weekdayOffPeak ?? 200000) / 1000).toFixed(0)}K/hr
                  </span>
                </button>
              {/each}
            </div>
          </div>

          <!-- Step 2: SELECT DATE (1:1 Pager Grid from Image #108 - No Scrollbar) -->
          <div class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6 space-y-4 shadow-xl">
            <div class="flex items-center justify-between">
              <div class="flex items-center gap-3">
                <div class="flex h-6 w-6 items-center justify-center rounded-full bg-[#50C8C8]/15 text-xs font-bold text-[#50C8C8]">
                  2
                </div>
                <h2 class="text-xs font-semibold tracking-wider text-[#50C8C8] uppercase flex items-center gap-2">
                  <Calendar class="h-4 w-4" />
                  SELECT DATE
                </h2>
              </div>

              <!-- Pager Navigation Buttons (< >) -->
              <div class="flex items-center gap-1.5">
                <button
                  type="button"
                  onclick={prevDatePage}
                  disabled={datePage === 0}
                  aria-label="Previous dates"
                  class="flex h-8 w-8 items-center justify-center rounded-lg border border-white/[0.08] bg-white/[0.03] text-[#F7F7F7]/60 transition-colors hover:border-white/[0.2] hover:text-[#F7F7F7] disabled:opacity-20 disabled:cursor-not-allowed"
                >
                  <ChevronLeft class="h-4 w-4" />
                </button>
                <button
                  type="button"
                  onclick={nextDatePage}
                  disabled={(datePage + 1) * 7 >= dateOptions.length}
                  aria-label="Next dates"
                  class="flex h-8 w-8 items-center justify-center rounded-lg border border-white/[0.08] bg-white/[0.03] text-[#F7F7F7]/60 transition-colors hover:border-white/[0.2] hover:text-[#F7F7F7] disabled:opacity-20 disabled:cursor-not-allowed"
                >
                  <ChevronRight class="h-4 w-4" />
                </button>
              </div>
            </div>

            <!-- 7-Column Date Grid (No Scrollbar) -->
            <div class="grid grid-cols-7 gap-2 pt-1">
              {#each visibleDateOptions as item}
                <button
                  type="button"
                  onclick={() => {
                    selectedDate = item.iso;
                    selectedSlot = null;
                  }}
                  class="flex flex-col items-center justify-center rounded-xl border py-3 px-1 transition-all {selectedDate ===
                  item.iso
                    ? 'border-[#E6FA50] bg-[#E6FA50]/15 text-[#E6FA50] shadow-sm'
                    : 'border-white/[0.06] bg-white/[0.015] text-[#F7F7F7]/60 hover:border-white/[0.12] hover:text-[#F7F7F7]'}"
                >
                  <span class="metric text-lg sm:text-xl font-bold">{item.dateNum}</span>
                  <div class="flex items-center gap-1 caption uppercase font-medium mt-1 text-[11px]">
                    <span>{item.day}</span>
                    {#if item.iso === new Date().toISOString().split("T")[0]}
                      <span class="text-[#50C8C8] font-bold">Today</span>
                    {/if}
                  </div>
                </button>
              {/each}
            </div>
          </div>

          <!-- Step 3: SELECT TIME -->
          <div class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6 space-y-4 shadow-xl">
            <div class="flex items-center gap-3">
              <div class="flex h-6 w-6 items-center justify-center rounded-full bg-[#50C8C8]/15 text-xs font-bold text-[#50C8C8]">
                3
              </div>
              <h2 class="text-xs font-semibold tracking-wider text-[#50C8C8] uppercase flex items-center gap-2">
                <Clock class="h-4 w-4" />
                SELECT TIME
              </h2>
            </div>
            <p class="body-sm text-[#F7F7F7]/40">
              Each slot is 1 hour. Tap a slot to select your playing time.
            </p>

            {#if isLoadingAvailability}
              <div class="grid grid-cols-3 gap-2.5 sm:grid-cols-6 pt-1">
                {#each Array.from({ length: 12 }) as _}
                  <div class="h-16 animate-pulse rounded-xl bg-white/[0.04]"></div>
                {/each}
              </div>
            {:else if activeCourtSlots.length === 0}
              <p class="body-sm text-[#F7F7F7]/40 py-4">
                No slots available on this date. Please pick another date or court.
              </p>
            {:else}
              <div class="grid grid-cols-3 gap-2.5 sm:grid-cols-6 pt-1">
                {#each activeCourtSlots as slot}
                  {@const isBooked = !slot.available || slot.booked || slot.isBooked}
                  <button
                    type="button"
                    disabled={isBooked}
                    onclick={() => {
                      if (!isBooked) {
                        selectedSlot = slot;
                      }
                    }}
                    class="flex flex-col items-center justify-center rounded-xl border p-3 transition-all {isBooked
                      ? 'border-transparent bg-white/[0.02] text-[#F7F7F7]/20 line-through cursor-not-allowed opacity-40 pointer-events-none'
                      : selectedSlot?.startsAt === slot.startsAt
                        ? 'border-[#E6FA50] bg-[#E6FA50]/20 text-[#E6FA50] font-bold shadow-sm'
                        : slot.isPeak
                          ? 'border-[#E6FA50]/20 bg-[#E6FA50]/5 text-[#E6FA50]/80 hover:border-[#E6FA50]/40'
                          : 'border-white/[0.06] bg-white/[0.015] text-[#F7F7F7]/80 hover:border-[#50C8C8]/40 hover:text-[#50C8C8]'}"
                  >
                    <span class="label font-bold">{slot.startsAt}</span>
                    <span class="caption mt-0.5 text-[#F7F7F7]/40">
                      Rp {(slot.price / 1000).toFixed(0)}K
                    </span>
                  </button>
                {/each}
              </div>

              <!-- Legend -->
              <div class="mt-6 flex flex-wrap items-center justify-between gap-4 pt-4 border-t border-white/[0.04]">
                <div class="flex items-center gap-5">
                  <div class="flex items-center gap-2">
                    <div class="h-2.5 w-2.5 rounded-sm border border-white/[0.08] bg-[#0C1B26]"></div>
                    <span class="caption text-[#F7F7F7]/40">Available</span>
                  </div>
                  <div class="flex items-center gap-2">
                    <div class="h-2.5 w-2.5 rounded-sm border border-[#E6FA50]/30 bg-[#E6FA50]/10"></div>
                    <span class="caption text-[#F7F7F7]/40">Peak Hour</span>
                  </div>
                  <div class="flex items-center gap-2">
                    <div class="h-2.5 w-2.5 rounded-sm bg-white/[0.02]"></div>
                    <span class="caption text-[#F7F7F7]/40">Booked</span>
                  </div>
                </div>
              </div>
            {/if}
          </div>
        </div>

        <!-- Right Column: Booking Summary (Sticky) -->
        <div class="lg:relative">
          <div class="lg:sticky lg:top-24 space-y-4">
            <div class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6 space-y-5 shadow-2xl">
              <p class="section-label">BOOKING SUMMARY</p>

              <div class="space-y-3 border-y border-white/[0.06] py-4 text-xs">
                <div class="flex justify-between items-center">
                  <span class="text-[#F7F7F7]/40">Venue</span>
                  <span class="heading-3 text-[#F7F7F7]">{venue.name}</span>
                </div>

                <div class="flex justify-between items-center">
                  <span class="text-[#F7F7F7]/40">Court</span>
                  <span class="heading-3 text-[#F7F7F7]">{selectedCourt?.name ?? "Court A"}</span>
                </div>

                <div class="flex justify-between items-center">
                  <span class="text-[#F7F7F7]/40">Date</span>
                  <span class="heading-3 text-[#F7F7F7]">
                    {selectedDate ? formatBookingDate(new Date(selectedDate)) : "Mon, Aug 31, 2026"}
                  </span>
                </div>

                <div class="flex justify-between items-center">
                  <span class="text-[#F7F7F7]/40">Time (WIB)</span>
                  <span class="heading-3 {selectedSlot ? 'text-[#E6FA50]' : 'text-[#F7F7F7]/40'}">
                    {selectedSlot ? `${selectedSlot.startsAt} – ${String(Number(selectedSlot.startsAt.split(':')[0]) + 1).padStart(2, '0')}:00` : "Not selected"}
                  </span>
                </div>

                <div class="flex justify-between items-center">
                  <span class="text-[#F7F7F7]/40">Duration</span>
                  <span class="heading-3 text-[#F7F7F7]">
                    {selectedSlot ? "60 min" : "—"}
                  </span>
                </div>

                <div class="space-y-2 pt-3 border-t border-white/[0.04]">
                  <div class="flex justify-between items-center">
                    <span class="text-[#F7F7F7]/40">Court rental</span>
                    <span class="heading-3 text-[#F7F7F7]">
                      {selectedSlot ? `Rp ${(courtRentalPrice / 1000).toFixed(0)}K` : "—"}
                    </span>
                  </div>

                  <div class="flex justify-between items-center">
                    <span class="text-[#F7F7F7]/40">Platform fee (5%)</span>
                    <span class="heading-3 text-[#F7F7F7]">
                      {selectedSlot ? `Rp ${(platformFee / 1000).toFixed(0)}K` : "—"}
                    </span>
                  </div>

                  {#if isRefundProtection}
                    <div class="flex justify-between items-center">
                      <span class="text-[#F7F7F7]/40">Refund Protection</span>
                      <span class="heading-3 text-[#F7F7F7]">Rp 15K</span>
                    </div>
                  {/if}

                  {#if voucherDiscount > 0}
                    <div class="flex justify-between items-center text-emerald-400">
                      <span>Voucher discount</span>
                      <span class="heading-3">-Rp {(voucherDiscount / 1000).toFixed(0)}K</span>
                    </div>
                  {/if}
                </div>

                <div class="flex justify-between items-baseline pt-3 border-t border-white/[0.06]">
                  <span class="heading-2 text-[#F7F7F7]">Total</span>
                  <span class="metric text-[#E6FA50]">
                    {selectedSlot ? `Rp ${(totalDue / 1000).toFixed(0)}K` : "—"}
                  </span>
                </div>
              </div>

              <!-- Add Refund Protection Checkbox Box -->
              <label class="flex items-start gap-3 rounded-xl border border-white/[0.06] bg-white/[0.015] p-3.5 cursor-pointer hover:border-white/[0.12] transition-colors">
                <input
                  type="checkbox"
                  bind:checked={isRefundProtection}
                  class="mt-0.5 h-4 w-4 rounded border-white/20 accent-[#E6FA50]"
                />
                <div>
                  <p class="body-sm font-semibold text-[#F7F7F7]">Add Refund Protection</p>
                  <p class="caption text-[#F7F7F7]/40 mt-0.5 leading-relaxed">
                    Get 100% refund eligibility up to 2 hours before playing for Rp 15.000 flat.
                  </p>
                </div>
              </label>

              <!-- Voucher Code Section -->
              <div class="space-y-2">
                <p class="section-label">VOUCHER</p>
                <div class="flex gap-2">
                  <input
                    type="text"
                    bind:value={voucherCode}
                    placeholder="ENTER CODE"
                    class="body-sm flex-1 rounded-xl border border-white/[0.08] bg-white/[0.02] px-3.5 py-2 uppercase text-[#F7F7F7] placeholder:text-[#F7F7F7]/25 focus:border-[#50C8C8]/40 focus:outline-none"
                  />
                  <button
                    type="button"
                    onclick={handleApplyVoucher}
                    disabled={isValidatingVoucher || !voucherCode.trim()}
                    class="btn-outline-white label h-9 px-4 rounded-xl text-xs font-semibold disabled:opacity-40"
                  >
                    {isValidatingVoucher ? "..." : "Apply"}
                  </button>
                </div>
                {#if voucherError}
                  <p class="caption text-red-400 mt-1">{voucherError}</p>
                {:else if voucherDiscount > 0}
                  <p class="caption text-emerald-400 mt-1">
                    Voucher applied! -Rp {(voucherDiscount / 1000).toFixed(0)}K
                  </p>
                {/if}
              </div>

              {#if !selectedSlot}
                <div class="rounded-xl border border-white/[0.06] bg-white/[0.015] p-3 text-center">
                  <p class="caption text-[#F7F7F7]/40">
                    Select at least one available time slot to continue.
                  </p>
                </div>
              {/if}

              <!-- Submit CTA Button -->
              <button
                type="submit"
                disabled={!selectedSlot || isSubmitting}
                class="btn-lime label flex h-12 w-full items-center justify-center gap-2 rounded-full font-bold text-[#06121A] disabled:opacity-50 disabled:cursor-not-allowed"
              >
                {#if isSubmitting}
                  <Loader2 class="h-4 w-4 animate-spin" />
                  <span>Creating Reservation...</span>
                {:else}
                  <span>Continue to Invite & Pay</span>
                {/if}
              </button>

              <div class="space-y-2 caption text-[#F7F7F7]/40 text-center pt-1">
                <div class="flex items-center justify-center gap-2">
                  <Info class="h-3.5 w-3.5 text-[#50C8C8]" />
                  <span>Free cancellation up to 24 hours before booking</span>
                </div>
                <div class="flex items-center justify-center gap-2 text-[#F7F7F7]/30">
                  <Users class="h-3.5 w-3.5" />
                  <span>You can invite friends after booking</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </form>
    </div>
  {/if}
</div>

// apps/web/src/app/venues/[id]/book/page.tsx
"use client";

import { useEffect, useState, useMemo } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import {
  ArrowLeft,
  Calendar,
  Clock,
  MapPin,
  ChevronLeft,
  ChevronRight,
  Users,
  Info,
} from "lucide-react";
import { mockVenues } from "@/mock/venues";
import { mockCourts } from "@/mock/courts";
import { ApiRequestError, createBooking, getVenue, getVenueCourts } from "@/lib/api";
import { getIdToken } from "@/lib/auth-client";
import { Court, Venue } from "@/types";

const DAYS_AHEAD = 14;

type BookingSubmitError =
  | "invalid-selection"
  | "overlap"
  | "auth-required"
  | "backend-unavailable"
  | "generic";

function generateDates() {
  const dates = [];
  const today = new Date();
  for (let i = 0; i < DAYS_AHEAD; i++) {
    const d = new Date(today);
    d.setDate(today.getDate() + i);
    dates.push(d);
  }
  return dates;
}

function generateTimeSlots(open: string, close: string, seed: number) {
  const slots = [];
  const startHour = parseInt(open.split(":")[0]);
  const endHour = parseInt(close.split(":")[0]);
  for (let h = startHour; h < endHour; h++) {
    const time = `${h.toString().padStart(2, "0")}:00`;
    const isPeak = (h >= 9 && h <= 11) || (h >= 16 && h <= 21);
    const hash = ((h + 1) * 2654435761 + seed) >>> 0;
    const isBooked = (hash % 100) < 35;
    slots.push({ time, isPeak, isBooked });
  }
  return slots;
}

function isWeekend(date: Date) {
  return date.getDay() === 0 || date.getDay() === 6;
}

function formatBookingDate(date: Date): string {
  return date.toISOString().split("T")[0];
}

function areConsecutiveSlots(slots: string[]): boolean {
  if (slots.length === 0) return false;

  const hours = slots
    .map((slot) => parseInt(slot.split(":")[0], 10))
    .sort((a, b) => a - b);

  return hours.every((hour, index) => index === 0 || hour === hours[index - 1] + 1);
}

export default function BookingFlowPage({
  params,
}: {
  params: { id: string };
}) {
  const router = useRouter();
  const fallbackVenue = mockVenues.find((v) => v.id === params.id) ?? mockVenues[0];
  const [venue, setVenue] = useState<Venue>(fallbackVenue);
  const [courts, setCourts] = useState<Court[]>(mockCourts.filter((c) => c.venueId === fallbackVenue.id));
  const [isLoadingApiData, setIsLoadingApiData] = useState(true);
  const [isUsingFallback, setIsUsingFallback] = useState(false);
  const [apiError, setApiError] = useState<string | null>(null);

  useEffect(() => {
    let cancelled = false;

    async function loadBookingDisplayData() {
      setIsLoadingApiData(true);
      setIsUsingFallback(false);
      setApiError(null);

      try {
        const [apiVenue, apiCourts] = await Promise.all([getVenue(params.id), getVenueCourts(params.id)]);
        if (cancelled) return;
        setVenue(apiVenue);
        setCourts(apiCourts.length > 0 ? apiCourts : mockCourts.filter((c) => c.venueId === fallbackVenue.id));
        setIsUsingFallback(apiCourts.length === 0);
      } catch {
        if (cancelled) return;
        setVenue(fallbackVenue);
        setCourts(mockCourts.filter((c) => c.venueId === fallbackVenue.id));
        setApiError("Could not reach the live court API.");
        setIsUsingFallback(true);
      } finally {
        if (!cancelled) setIsLoadingApiData(false);
      }
    }

    loadBookingDisplayData();

    return () => {
      cancelled = true;
    };
  }, [fallbackVenue, params.id]);

  const dates = useMemo(() => generateDates(), []);

  const [selectedDate, setSelectedDate] = useState<Date>(dates[0]);
  const [selectedCourt, setSelectedCourt] = useState(courts[0]);
  const [selectedSlots, setSelectedSlots] = useState<string[]>([]);

  useEffect(() => {
    if (!courts.some((court) => court.id === selectedCourt.id) && courts[0]) {
      setSelectedCourt(courts[0]);
      setSelectedSlots([]);
    }
  }, [courts, selectedCourt.id]);
  const [dateScrollStart, setDateScrollStart] = useState(0);
  const [confirmState, setConfirmState] = useState<"idle" | "submitting" | "success" | "error">("idle");
  const [submitError, setSubmitError] = useState<BookingSubmitError | null>(null);

  const timeSlots = useMemo(() => {
    const dateSeed = selectedDate.getFullYear() * 10000 + (selectedDate.getMonth() + 1) * 100 + selectedDate.getDate();
    const courtSeed = selectedCourt.id.charCodeAt(selectedCourt.id.length - 1);
    return generateTimeSlots(
      venue.operatingHours.open,
      venue.operatingHours.close,
      dateSeed + courtSeed
    );
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [venue.id, selectedDate.toDateString(), selectedCourt.id]);

  const weekend = isWeekend(selectedDate);

  function getSlotPrice(isPeak: boolean) {
    if (weekend) {
      return isPeak
        ? selectedCourt.pricing.weekendPeak
        : selectedCourt.pricing.weekendOffPeak;
    }
    return isPeak
      ? selectedCourt.pricing.weekdayPeak
      : selectedCourt.pricing.weekdayOffPeak;
  }

  function toggleSlot(time: string) {
    if (confirmState === "submitting") return;
    setSelectedSlots((prev) =>
      prev.includes(time) ? prev.filter((t) => t !== time) : [...prev, time]
    );
    setConfirmState("idle");
    setSubmitError(null);
  }

  const totalPrice = useMemo(() => {
    return selectedSlots.reduce((sum, time) => {
      const slot = timeSlots.find((s) => s.time === time);
      if (!slot) return sum;
      return sum + getSlotPrice(slot.isPeak);
    }, 0);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [selectedSlots, selectedCourt, selectedDate]);

  const duration = selectedSlots.length;

  const sortedSlots = [...selectedSlots].sort();
  const startTime = sortedSlots[0] ?? "--:--";
  const endTime = sortedSlots.length
    ? `${(parseInt(sortedSlots[sortedSlots.length - 1].split(":")[0]) + 1).toString().padStart(2, "0")}:00`
    : "--:--";

  async function handleConfirm() {
    if (confirmState === "submitting") return;

    const selectedUnavailableSlot = selectedSlots.some((time) => {
      const slot = timeSlots.find((candidate) => candidate.time === time);
      return !slot || slot.isBooked;
    });

    if (
      !venue.id ||
      !selectedCourt?.id ||
      selectedSlots.length === 0 ||
      selectedUnavailableSlot ||
      !areConsecutiveSlots(selectedSlots)
    ) {
      setConfirmState("error");
      setSubmitError("invalid-selection");
      return;
    }

    const authToken = await getIdToken();
    if (!authToken) {
      setConfirmState("error");
      setSubmitError("auth-required");
      router.push(`/auth/login?next=${encodeURIComponent(`/venues/${venue.id}/book`)}`);
      return;
    }

    setConfirmState("submitting");
    setSubmitError(null);

    try {
      const booking = await createBooking(
        {
          venueId: venue.id,
          courtId: selectedCourt.id,
          bookingDate: formatBookingDate(selectedDate),
          startsAt: startTime,
          endsAt: endTime,
        },
        authToken
      );

      const query = new URLSearchParams({
        venue: booking.venue.name,
        court: booking.court.name,
        date: formatBookingDate(selectedDate),
        start: startTime,
        end: endTime,
        amount: booking.courtAmount.toString(),
        venueId: booking.venue.id,
      });

      setConfirmState("success");
      router.push(`/booking/${booking.id}/invite?${query.toString()}`);
    } catch (error) {
      setConfirmState("error");

      if (error instanceof ApiRequestError) {
        if (error.status === 409) {
          setSubmitError("overlap");
          return;
        }

        if (error.status === 401 || error.status === 403) {
          setSubmitError("auth-required");
          return;
        }

        if (error.status && error.status >= 500) {
          setSubmitError("backend-unavailable");
          return;
        }

        setSubmitError("generic");
        return;
      }

      setSubmitError("backend-unavailable");
    }
  }

  const submitErrorMessage = (() => {
    switch (submitError) {
      case "invalid-selection":
        return "Select one available consecutive time range before continuing.";
      case "overlap":
        return "This court is no longer available for the selected time. Choose another slot.";
      case "auth-required":
        return "Sign in before creating a booking.";
      case "backend-unavailable":
        return "Booking service is unavailable. Please try again when the backend is running.";
      case "generic":
        return "Could not create this booking. Please review your selection and retry.";
      default:
        return null;
    }
  })();

  return (
    <div className="min-h-screen pt-20">
      <div className="container max-w-4xl py-8">
        {(isLoadingApiData || isUsingFallback || apiError) && (
          <div className={`mb-5 rounded-xl border px-4 py-3 text-sm ${apiError && !isLoadingApiData ? "border-red-500/20 bg-red-500/10 text-red-200/80" : "border-white/[0.06] bg-white/[0.03] text-[#F7F7F7]/40"}`}>
            {isLoadingApiData ? "Loading live court data..." : apiError ? `${apiError} Showing demo court data.` : "Live API unavailable. Showing demo court data."}
          </div>
        )}
        {courts.length === 0 && (
          <div className="mb-5 rounded-xl border border-red-500/20 bg-red-500/10 px-4 py-3 text-sm text-red-200/80">
            No courts are available for this venue yet.
          </div>
        )}
        {/* Back */}
        <Link
          href={`/venues/${venue.id}`}
          className="inline-flex items-center gap-2 text-sm text-[#F7F7F7]/40 hover:text-[#F7F7F7]/70 transition-colors"
        >
          <ArrowLeft className="h-4 w-4" />
          Back to venue
        </Link>

        {/* Header */}
        <div className="mt-6">
          <h1 className="heading-1 text-2xl text-[#F7F7F7] md:text-3xl">
            Book a Court
          </h1>
          <p className="mt-2 flex items-center gap-2 text-sm text-[#F7F7F7]/40">
            <MapPin className="h-3.5 w-3.5" />
            {venue.name} · {venue.city}
          </p>
        </div>

        <div className="mt-8 grid grid-cols-1 gap-8 lg:grid-cols-[1fr_340px]">
          {/* Left — Selection */}
          <div className="space-y-8">
            {/* Court Selector */}
            <div>
              <h2 className="heading-3 text-sm text-[#F7F7F7]/60 uppercase tracking-wider">
                Select Court
              </h2>
              <div className="mt-3 flex flex-wrap gap-3">
                {courts.map((court) => (
                  <button
                    key={court.id}
                    onClick={() => {
                      setSelectedCourt(court);
                      setSelectedSlots([]);
                      setSubmitError(null);
                      setConfirmState("idle");
                    }}
                    className={`rounded-xl border px-5 py-3 transition-all ${
                      selectedCourt.id === court.id
                        ? "border-[#E6FA50]/40 bg-[#E6FA50]/10 text-[#E6FA50]"
                        : "border-white/[0.06] bg-[#0C1B26] text-[#F7F7F7]/50 hover:border-white/[0.12]"
                    }`}
                  >
                    <p className="text-sm font-medium">{court.name}</p>
                    <p className="mt-0.5 text-[10px] opacity-60">
                      {court.type}
                    </p>
                  </button>
                ))}
              </div>
            </div>

            {/* Date Selector */}
            <div>
              <h2 className="heading-3 text-sm text-[#F7F7F7]/60 uppercase tracking-wider">
                <Calendar className="mr-2 inline h-3.5 w-3.5" />
                Select Date
              </h2>
              <div className="mt-3 flex items-center gap-2">
                <button
                  onClick={() =>
                    setDateScrollStart(Math.max(0, dateScrollStart - 4))
                  }
                  disabled={dateScrollStart === 0}
                  className="hidden sm:block rounded-lg border border-white/[0.06] p-2 text-[#F7F7F7]/30 hover:text-[#F7F7F7]/60 disabled:opacity-20 disabled:cursor-not-allowed"
                >
                  <ChevronLeft className="h-4 w-4" />
                </button>
                <div className="grid flex-1 grid-cols-4 gap-2 sm:grid-cols-7">
                  {dates
                    .slice(dateScrollStart, dateScrollStart + 7)
                    .map((date, idx) => {
                      const isSelected =
                        date.toDateString() === selectedDate.toDateString();
                      const isToday =
                        date.toDateString() === new Date().toDateString();
                      const wknd = isWeekend(date);
                      const hiddenOnMobile = idx >= 4 ? "hidden sm:flex" : "flex";
                      return (
                        <button
                          key={date.toISOString()}
                          onClick={() => {
                            setSelectedDate(date);
                            setSelectedSlots([]);
                            setSubmitError(null);
                            setConfirmState("idle");
                          }}
                          className={`${hiddenOnMobile} flex-col items-center rounded-xl border py-3 transition-all ${
                            isSelected
                              ? "border-[#E6FA50]/40 bg-[#E6FA50]/10"
                              : "border-white/[0.06] bg-[#0C1B26] hover:border-white/[0.12]"
                          }`}
                        >
                          <span
                            className={`text-[10px] uppercase ${
                              isSelected
                                ? "text-[#E6FA50]/70"
                                : wknd
                                  ? "text-[#50C8C8]/50"
                                  : "text-[#F7F7F7]/25"
                            }`}
                          >
                            {date.toLocaleDateString("en-US", {
                              weekday: "short",
                            })}
                          </span>
                          <span
                            className={`mt-1 text-lg font-medium ${
                              isSelected
                                ? "text-[#E6FA50]"
                                : "text-[#F7F7F7]/60"
                            }`}
                          >
                            {date.getDate()}
                          </span>
                          {isToday && (
                            <span className="mt-0.5 text-[9px] text-[#50C8C8]">
                              Today
                            </span>
                          )}
                        </button>
                      );
                    })}
                </div>
                <button
                  onClick={() =>
                    setDateScrollStart(
                      Math.min(DAYS_AHEAD - 7, dateScrollStart + 4)
                    )
                  }
                  disabled={dateScrollStart >= DAYS_AHEAD - 7}
                  className="hidden sm:block rounded-lg border border-white/[0.06] p-2 text-[#F7F7F7]/30 hover:text-[#F7F7F7]/60 disabled:opacity-20 disabled:cursor-not-allowed"
                >
                  <ChevronRight className="h-4 w-4" />
                </button>
              </div>
              {/* Mobile pagination */}
              <div className="mt-2 flex items-center justify-between sm:hidden">
                <button
                  onClick={() =>
                    setDateScrollStart(Math.max(0, dateScrollStart - 4))
                  }
                  disabled={dateScrollStart === 0}
                  className="flex items-center gap-1 text-[11px] text-[#F7F7F7]/30 disabled:opacity-20 disabled:cursor-not-allowed"
                >
                  <ChevronLeft className="h-3.5 w-3.5" />
                  Previous
                </button>
                <button
                  onClick={() =>
                    setDateScrollStart(
                      Math.min(DAYS_AHEAD - 7, dateScrollStart + 4)
                    )
                  }
                  disabled={dateScrollStart >= DAYS_AHEAD - 7}
                  className="flex items-center gap-1 text-[11px] text-[#F7F7F7]/30 disabled:opacity-20 disabled:cursor-not-allowed"
                >
                  Next
                  <ChevronRight className="h-3.5 w-3.5" />
                </button>
              </div>
            </div>

            {/* Time Slot Selector */}
            <div>
              <h2 className="heading-3 text-sm text-[#F7F7F7]/60 uppercase tracking-wider">
                <Clock className="mr-2 inline h-3.5 w-3.5" />
                Select Time
              </h2>
              <p className="mt-1 text-[11px] text-[#F7F7F7]/25">
                Select one or more consecutive hours. Peak hours are highlighted.
              </p>
              <div className="mt-4 grid grid-cols-4 gap-2 sm:grid-cols-6 md:grid-cols-8">
                {timeSlots.map((slot) => {
                  const isSelected = selectedSlots.includes(slot.time);
                  const price = getSlotPrice(slot.isPeak);
                  return (
                    <button
                      key={slot.time}
                      disabled={slot.isBooked}
                      onClick={() => toggleSlot(slot.time)}
                      className={`relative rounded-xl border py-3 text-center transition-all ${
                        slot.isBooked
                          ? "border-transparent bg-white/[0.02] text-[#F7F7F7]/10 cursor-not-allowed"
                          : isSelected
                            ? "border-[#E6FA50] bg-[#E6FA50]/15 text-[#E6FA50] shadow-[0_0_12px_rgba(230,250,80,0.1)]"
                            : slot.isPeak
                              ? "border-[#E6FA50]/15 bg-[#E6FA50]/[0.03] text-[#F7F7F7]/50 hover:border-[#E6FA50]/30"
                              : "border-white/[0.06] bg-[#0C1B26] text-[#F7F7F7]/50 hover:border-white/[0.15]"
                      }`}
                    >
                      <span className="text-xs font-medium">{slot.time}</span>
                      <span
                        className={`mt-0.5 block text-[9px] ${
                          isSelected
                            ? "text-[#E6FA50]/70"
                            : slot.isBooked
                              ? "text-[#F7F7F7]/10"
                              : "text-[#F7F7F7]/25"
                        }`}
                      >
                        {slot.isBooked
                          ? "Booked"
                          : `${(price / 1000).toFixed(0)}K`}
                      </span>
                    </button>
                  );
                })}
              </div>
              <div className="mt-3 flex items-center gap-4">
                <div className="flex items-center gap-1.5">
                  <div className="h-2.5 w-2.5 rounded-sm border border-white/[0.06] bg-[#0C1B26]" />
                  <span className="text-[10px] text-[#F7F7F7]/30">
                    Off-Peak
                  </span>
                </div>
                <div className="flex items-center gap-1.5">
                  <div className="h-2.5 w-2.5 rounded-sm border border-[#E6FA50]/15 bg-[#E6FA50]/[0.03]" />
                  <span className="text-[10px] text-[#F7F7F7]/30">Peak</span>
                </div>
                <div className="flex items-center gap-1.5">
                  <div className="h-2.5 w-2.5 rounded-sm bg-white/[0.02]" />
                  <span className="text-[10px] text-[#F7F7F7]/30">Booked</span>
                </div>
                <div className="flex items-center gap-1.5">
                  <div className="h-2.5 w-2.5 rounded-sm border border-[#E6FA50] bg-[#E6FA50]/15" />
                  <span className="text-[10px] text-[#F7F7F7]/30">
                    Selected
                  </span>
                </div>
              </div>
            </div>
          </div>

          {/* Right — Booking Summary */}
          <div className="lg:relative">
            <div className="lg:sticky lg:top-28">
              <div className="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6">
                <h3 className="heading-3 text-sm text-[#F7F7F7]/60 uppercase tracking-wider">
                  Booking Summary
                </h3>

                <div className="mt-5 space-y-4">
                  <div className="flex items-center justify-between">
                    <span className="text-sm text-[#F7F7F7]/40">Venue</span>
                    <span className="text-sm font-medium text-[#F7F7F7]/80">
                      {venue.name}
                    </span>
                  </div>
                  <div className="flex items-center justify-between">
                    <span className="text-sm text-[#F7F7F7]/40">Court</span>
                    <span className="text-sm font-medium text-[#F7F7F7]/80">
                      {selectedCourt.name}
                    </span>
                  </div>
                  <div className="flex items-center justify-between">
                    <span className="text-sm text-[#F7F7F7]/40">Date</span>
                    <span className="text-sm font-medium text-[#F7F7F7]/80">
                      {selectedDate.toLocaleDateString("en-US", {
                        weekday: "short",
                        month: "short",
                        day: "numeric",
                      })}
                    </span>
                  </div>
                  <div className="flex items-center justify-between">
                    <span className="text-sm text-[#F7F7F7]/40">Time</span>
                    <span className="text-sm font-medium text-[#F7F7F7]/80">
                      {selectedSlots.length > 0
                        ? `${startTime} – ${endTime}`
                        : "Not selected"}
                    </span>
                  </div>
                  <div className="flex items-center justify-between">
                    <span className="text-sm text-[#F7F7F7]/40">Duration</span>
                    <span className="text-sm font-medium text-[#F7F7F7]/80">
                      {duration > 0 ? `${duration} hour${duration > 1 ? "s" : ""}` : "—"}
                    </span>
                  </div>
                </div>

                <div className="mt-5 border-t border-white/[0.06] pt-4">
                  <div className="flex items-center justify-between">
                    <span className="text-sm text-[#F7F7F7]/40">
                      Court rental
                    </span>
                    <span className="text-sm text-[#F7F7F7]/60">
                      {totalPrice > 0
                        ? `Rp ${totalPrice.toLocaleString("id-ID")}`
                        : "—"}
                    </span>
                  </div>
                  <div className="mt-2 flex items-center justify-between">
                    <span className="text-sm text-[#F7F7F7]/40">
                      Platform fee
                    </span>
                    <span className="text-sm text-[#F7F7F7]/60">
                      {totalPrice > 0
                        ? `Rp ${(totalPrice * 0.05).toLocaleString("id-ID")}`
                        : "—"}
                    </span>
                  </div>
                </div>

                <div className="mt-4 border-t border-white/[0.06] pt-4">
                  <div className="flex items-center justify-between">
                    <span className="text-sm font-medium text-[#F7F7F7]/70">
                      Total
                    </span>
                    <span className="price text-xl text-[#F7F7F7]">
                      {totalPrice > 0
                        ? `Rp ${(totalPrice * 1.05).toLocaleString("id-ID")}`
                        : "—"}
                    </span>
                  </div>
                </div>

                {selectedSlots.length === 0 && (
                  <div className="mt-5 rounded-xl border border-white/[0.06] bg-white/[0.02] p-3">
                    <p className="text-[11px] leading-relaxed text-[#F7F7F7]/35">
                      Select at least one available time slot to continue.
                    </p>
                  </div>
                )}
                {submitErrorMessage && (
                  <div className="mt-5 rounded-xl border border-red-500/20 bg-red-500/10 p-3">
                    <p className="text-[11px] leading-relaxed text-red-200/80">
                      {submitErrorMessage}
                    </p>
                  </div>
                )}
                {confirmState === "success" && (
                  <div className="mt-5 rounded-xl border border-[#E6FA50]/20 bg-[#E6FA50]/10 p-3">
                    <p className="text-[11px] leading-relaxed text-[#E6FA50]">
                      Booking created. Taking you to invite friends.
                    </p>
                  </div>
                )}

                <button
                  onClick={handleConfirm}
                  disabled={courts.length === 0 || selectedSlots.length === 0 || confirmState === "submitting"}
                  className="btn-lime mt-6 flex h-12 w-full items-center justify-center rounded-full text-[11px] font-semibold uppercase tracking-[0.08em] disabled:cursor-not-allowed disabled:opacity-30"
                >
                  {confirmState === "submitting" ? "Creating Booking..." : "Continue to Invite & Pay"}
                </button>

                <div className="mt-4 flex items-start gap-2 rounded-lg bg-white/[0.02] p-3">
                  <Info className="mt-0.5 h-3.5 w-3.5 shrink-0 text-[#F7F7F7]/20" />
                  <p className="text-[11px] leading-relaxed text-[#F7F7F7]/25">
                    Free cancellation up to 24 hours before your booking. After
                    that, standard refund policy applies.
                  </p>
                </div>

                <div className="mt-3 flex items-center justify-center gap-2 text-[11px] text-[#F7F7F7]/25">
                  <Users className="h-3 w-3" />
                  <span>You can invite friends after booking</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
