// apps/web/src/lib/components/ui/error-state.svelte
<script lang="ts">
import { AlertTriangle, RefreshCw } from "lucide-svelte";

interface Props {
  title?: string;
  description?: string;
  onRetry?: () => void;
  isRetrying?: boolean;
  class?: string;
}

let {
  title = "Something went wrong",
  description = "We couldn't load the data. Please try again.",
  onRetry,
  isRetrying = false,
  class: className = "",
}: Props = $props();
</script>

<div
  class="flex flex-col items-center justify-center rounded-2xl border border-red-500/20 bg-red-500/5 p-8 text-center {className}"
>
  <div class="mb-4 flex h-12 w-12 items-center justify-center rounded-full bg-red-500/10 text-red-400">
    <AlertTriangle class="h-6 w-6" />
  </div>
  <h3 class="text-lg font-semibold text-[#F7F7F7]">{title}</h3>
  <p class="mt-1.5 max-w-sm text-sm text-white/60">{description}</p>
  {#if onRetry}
    <button
      type="button"
      onclick={onRetry}
      disabled={isRetrying}
      class="mt-5 inline-flex items-center gap-2 rounded-xl border border-white/20 bg-transparent px-4 py-2 text-sm font-medium text-white transition-all hover:bg-white/5 active:scale-95 disabled:opacity-50"
    >
      <RefreshCw class="h-4 w-4 {isRetrying ? 'animate-spin' : ''}" />
      {isRetrying ? "Retrying..." : "Try again"}
    </button>
  {/if}
</div>

// apps/web/src/components/ui/error-state.tsx
"use client";

import { AlertTriangle, RotateCw } from "lucide-react";

export function ErrorState({
  title = "Couldn't load data",
  description = "We couldn't reach the server. Check your connection and try again.",
  onRetry,
  isRetrying = false,
  className = "",
}: {
  title?: string;
  description?: string;
  onRetry?: () => void;
  isRetrying?: boolean;
  className?: string;
}) {
  return (
    <div className={`mx-auto flex max-w-md flex-col items-center rounded-2xl border border-white/[0.06] bg-[#0C1B26] px-6 py-16 text-center md:py-20 ${className}`}>
      <div className="flex h-14 w-14 items-center justify-center rounded-full bg-[#E6FA50]/10">
        <AlertTriangle className="h-6 w-6 text-[#E6FA50]" />
      </div>
      <h2 className="heading-3 mt-6 text-lg text-[#F7F7F7]">{title}</h2>
      <p className="mt-2 max-w-sm text-sm font-light text-[#F7F7F7]/40">{description}</p>
      {onRetry && (
        <button
          type="button"
          onClick={onRetry}
          disabled={isRetrying}
          className="btn-lime mt-6 inline-flex h-10 items-center justify-center gap-2 rounded-xl px-6 text-[11px] font-semibold uppercase tracking-[0.08em] disabled:opacity-60"
        >
          <RotateCw className={`h-3.5 w-3.5 ${isRetrying ? "animate-spin" : ""}`} />
          {isRetrying ? "Retrying..." : "Try again"}
        </button>
      )}
    </div>
  );
}
