// apps/web/src/app/bookings/page.tsx
"use client";

import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { queryKeys } from "@/lib/queries";
import {
  MapPin,
  Clock,
  Users,
  Share2,
  CalendarDays,
  Trophy,
  Timer,
  Eye,
  CreditCard,
  XCircle,
  RotateCcw,
} from "lucide-react";
import { ApiRequestError, cancelBooking, getUserBookings, getMyRefunds, createRefund, ApiBooking, ApiRefund } from "@/lib/api";
import { padelImg } from "@/lib/images";

const IMG = {
  venue1: padelImg(600),
  venue2: padelImg(600),
  venue3: padelImg(600),
};

const TABS = ["upcoming", "past", "cancelled", "refunds"] as const;
type TabKey = typeof TABS[number];

export default function BookingsPage() {
  const [activeTab, setActiveTab] = useState<TabKey>("upcoming");
  const [toast, setToast] = useState<string | null>(null);
  const [cancelledIds, setCancelledIds] = useState<string[]>([]);
  const router = useRouter();
  const [bookingToCancel, setBookingToCancel] = useState<ApiBooking | null>(null);
  const [isCancelling, setIsCancelling] = useState(false);
  const [bookingToRefund, setBookingToRefund] = useState<ApiBooking | null>(null);
  const [refundReason, setRefundReason] = useState("");

  const { data: bookings = [], isLoading, isError, error: queryError } = useQuery({
    queryKey: queryKeys.bookings.user(activeTab === "refunds" ? "cancelled" : activeTab),
    queryFn: () => activeTab === "refunds" ? getUserBookings("cancelled") : getUserBookings(activeTab),
  });

  const { data: myRefunds = [] } = useQuery({
    queryKey: queryKeys.refunds.me,
    queryFn: getMyRefunds,
  });

  const error = isError
    ? queryError instanceof ApiRequestError
      ? queryError.message || "Failed to load bookings"
      : "Failed to load bookings"
    : null;

  const visibleBookings = bookings.map((booking) =>
    cancelledIds.includes(booking.id)
      ? {
          ...booking,
          status: "CANCELLED",
        }
      : booking
  );

  const upcoming = visibleBookings.filter((b) => b.status === "CONFIRMED" || b.status === "PENDING_PAYMENT");
  const past = visibleBookings.filter((b) => b.status === "COMPLETED");
  const cancelled = visibleBookings.filter((b) => b.status === "CANCELLED");

  const tabData: Record<"upcoming" | "past" | "cancelled", ApiBooking[]> = { upcoming, past, cancelled };

  const nextBooking = upcoming[0];
  const nextVenue = nextBooking?.venue;
  const nextCourt = nextBooking?.court;

  const totalBookings = visibleBookings.length;
  const hoursPlayed = visibleBookings.filter((b) => b.status === "COMPLETED").reduce((sum, b) => sum + b.durationMinutes, 0);

  function showToast(msg: string) {
    setToast(msg);
    setTimeout(() => setToast(null), 2500);
  }

  function getRefundNote(booking: ApiBooking): string {
    if (booking.isRefundEligible) {
      return booking.refundPolicyReason ?? "Full refund eligible. A pending refund request will be created after cancellation.";
    }
    return booking.refundPolicyReason ?? "This booking is not eligible for a refund.";
  }

  function getSuccessMessage(result: { isRefundEligible?: boolean; refundAmount?: number; refundPolicyReason?: string }): string {
    if (result.isRefundEligible && result.refundAmount && result.refundAmount > 0) {
      return `Booking cancelled. Pending refund: Rp ${result.refundAmount.toLocaleString("id-ID")}.`;
    }
    return `Booking cancelled. ${result.refundPolicyReason ?? "No refund record needed."}`;
  }

  async function handleShare(bookingId: string) {
    const shareUrl = `${window.location.origin}/booking/${bookingId}/invite`;
    try {
      await navigator.clipboard.writeText(shareUrl);
      showToast("Invite link copied to clipboard.");
    } catch {
      showToast(`Share this invite link: ${shareUrl}`);
    }
  }

  function handleCancel(booking: ApiBooking) {
    setBookingToCancel(booking);
  }

  const queryClient = useQueryClient();

  const cancelMutation = useMutation({
    mutationFn: cancelBooking,
    onSuccess: (result, id) => {
      queryClient.invalidateQueries({ queryKey: queryKeys.bookings.user(activeTab) });
      setCancelledIds((prev) => (prev.includes(id) ? prev : [...prev, id]));
      setBookingToCancel(null);
      showToast(getSuccessMessage(result));
    },
    onError: (error) => {
      if (error instanceof ApiRequestError) {
        if (error.status === 404) {
          showToast("Booking was not found for this account.");
        } else if (error.status === 400) {
          showToast(error.message || "This booking cannot be cancelled.");
        } else {
          showToast("Could not cancel booking. Please try again.");
        }
      } else {
        showToast("Could not cancel booking. Please try again.");
      }
    },
    onSettled: () => {
      setIsCancelling(false);
    }
  });

  async function confirmCancel() {
    if (!bookingToCancel || isCancelling) return;
    setIsCancelling(true);
    cancelMutation.mutate(bookingToCancel.id);
  }

  const refundMutation = useMutation({
    mutationFn: (reason: string) => createRefund({ bookingId: bookingToRefund!.id, reason }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.refunds.me });
      queryClient.invalidateQueries({ queryKey: queryKeys.bookings.user(activeTab === "refunds" ? "cancelled" : activeTab) });
      setBookingToRefund(null);
      setRefundReason("");
      showToast("Refund request submitted successfully.");
    },
    onError: (error) => {
      if (error instanceof ApiRequestError) {
        showToast(error.message || "Failed to submit refund request.");
      } else {
        showToast("Failed to submit refund request.");
      }
    },
  });

  function confirmRefund() {
    if (!bookingToRefund || refundMutation.isPending || !refundReason.trim()) return;
    refundMutation.mutate(refundReason.trim());
  }

  if (isLoading) {
    return (
      <div className="min-h-screen pt-28">
        <section className="container pb-8">
          <h1 className="heading-1 text-3xl text-[#F7F7F7] md:text-4xl">
            My <span className="text-[#E6FA50]">Bookings</span>
          </h1>
          <p className="mt-2 text-sm font-light text-[#F7F7F7]/40">
            Manage your upcoming matches and booking history.
          </p>
        </section>
        <div className="container py-16 text-center">
          <p className="text-sm text-[#F7F7F7]/25">Loading your bookings...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen pt-28">
        <section className="container pb-8">
          <h1 className="heading-1 text-3xl text-[#F7F7F7] md:text-4xl">
            My <span className="text-[#E6FA50]">Bookings</span>
          </h1>
          <p className="mt-2 text-sm font-light text-[#F7F7F7]/40">
            Manage your upcoming matches and booking history.
          </p>
        </section>
        <div className="container py-16 text-center">
          <p className="text-sm text-red-400/80">{error}</p>
          <button
            onClick={() => window.location.reload()}
            className="mt-4 rounded-full bg-red-500/15 px-5 py-2.5 text-[11px] font-semibold uppercase tracking-[0.08em] text-red-300 transition-colors hover:bg-red-500/25"
          >
            Retry
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen pt-28">
      {/* Header */}
      <section className="container pb-8">
        <h1 className="heading-1 text-3xl text-[#F7F7F7] md:text-4xl">
          My <span className="text-[#E6FA50]">Bookings</span>
        </h1>
        <p className="mt-2 text-sm font-light text-[#F7F7F7]/40">
          Manage your upcoming matches and booking history.
        </p>
      </section>

      {/* Next Match */}
      {nextBooking && nextVenue && nextCourt && (
        <section className="container pb-10">
          <span className="section-label">Your Next Match</span>
          <div className="mt-5 grid grid-cols-1 overflow-hidden rounded-2xl border border-white/[0.06] bg-[#0C1B26] lg:grid-cols-[1.85fr_1fr]">
            <div className="flex flex-col justify-center p-7 md:p-9">
              <div className="flex items-center gap-3">
                <span className="inline-block rounded-full bg-[#E6FA50]/10 px-3 py-1 text-[10px] font-medium uppercase tracking-[0.15em] text-[#E6FA50]">
                  {nextBooking.status}
                </span>
                <span className="caption text-[#F7F7F7]/25">{nextBooking.bookingDate}</span>
              </div>

              <h2 className="heading-1 mt-4 text-2xl text-[#F7F7F7] md:text-3xl">
                {nextVenue.name}
              </h2>

              <p className="mt-2 flex items-center gap-2 text-sm text-[#F7F7F7]/40">
                <MapPin className="h-3.5 w-3.5" />
                {nextVenue.city}
              </p>

              <div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">
                <DetailChip icon={CalendarDays} label="Date" value={nextBooking.bookingDate} />
                <DetailChip icon={Clock} label="Time" value={`${nextBooking.startsAt} – ${nextBooking.endsAt}`} />
                <DetailChip icon={MapPin} label="Court" value={`${nextCourt.name} · ${nextCourt.type}`} />
                <DetailChip icon={Timer} label="Price" value={`Rp ${(nextBooking.finalAmount / 1000).toFixed(0)}K`} />
              </div>

              <div className="mt-6 flex flex-wrap gap-3">
                <Link
                  href={`/bookings/${nextBooking.id}`}
                  className="btn-lime inline-flex h-10 items-center gap-2 rounded-full px-6 text-[11px] font-semibold uppercase tracking-[0.08em]"
                >
                  <Eye className="h-3.5 w-3.5" />
                  View Details
                </Link>
                <button
                  onClick={() => handleShare(nextBooking.id)}
                  className="inline-flex h-10 items-center gap-2 rounded-full border border-white/10 px-6 text-[11px] font-medium uppercase tracking-[0.08em] text-[#F7F7F7]/60 transition-colors hover:border-white/20 hover:text-[#F7F7F7] focus:outline-none focus:ring-2 focus:ring-[#E6FA50]/40"
                >
                  <Share2 className="h-3.5 w-3.5" />
                  Share
                </button>
              </div>
            </div>

            <div className="relative hidden overflow-hidden lg:block">
              <Image
                src={IMG.venue1}
                alt={nextVenue.name}
                fill
                sizes="(min-width: 1024px) 33vw, 100vw"
                className="object-cover"
              />
            </div>
          </div>
        </section>
      )}

      {/* Stats */}
      <section className="container pb-10">
        <div className="grid grid-cols-2 gap-4 md:grid-cols-4">
          <StatCard icon={CalendarDays} value={totalBookings.toString()} label="Total Bookings" />
          <StatCard icon={Timer} value={`${hoursPlayed / 60}h`} label="Hours Played" />
          <StatCard icon={Trophy} value="12" label="Matches Joined" />
          <StatCard icon={Users} value="8" label="Friends Invited" />
        </div>
      </section>

      {/* Tabs */}
      <section className="container pb-section-sm">
        <div className="flex gap-1 border-b border-white/[0.06] mb-8 overflow-x-auto">
          {TABS.map((tab) => {
            const count = tab === "refunds" ? myRefunds.length : tabData[tab as "upcoming" | "past" | "cancelled"].length;
            return (
              <button
                key={tab}
                onClick={() => setActiveTab(tab)}
                className={`relative px-5 py-3 text-[11px] font-medium uppercase tracking-[0.1em] transition-colors whitespace-nowrap ${
                  activeTab === tab
                    ? "text-[#E6FA50]"
                    : "text-[#F7F7F7]/25 hover:text-[#F7F7F7]/60"
                }`}
              >
                {tab} ({count})
                {activeTab === tab && (
                  <span className="absolute bottom-0 left-0 right-0 h-[2px] bg-[#E6FA50]" />
                )}
              </button>
            );
          })}
        </div>

        <div className="space-y-3">
          {activeTab === "refunds" ? (
            myRefunds.length === 0 ? (
              <div className="py-16 text-center">
                <p className="text-sm text-[#F7F7F7]/25">No refund requests.</p>
              </div>
            ) : (
              myRefunds.map((refund) => (
                <div key={refund.id} className="rounded-xl border border-white/[0.06] bg-[#0C1B26] p-5">
                  <div className="flex flex-col sm:flex-row sm:justify-between sm:items-start gap-4">
                    <div className="min-w-0">
                      <div className="flex flex-wrap items-center gap-2">
                        <span className="text-sm font-medium text-[#F7F7F7]">{refund.booking?.venue?.name || refund.bookingId}</span>
                        <span className={`rounded-full px-2 py-0.5 text-[10px] font-medium uppercase tracking-[0.1em] ${
                          refund.status === 'PENDING' ? 'bg-amber-500/10 text-amber-400' :
                          refund.status === 'APPROVED' ? 'bg-[#E6FA50]/10 text-[#E6FA50]' :
                          refund.status === 'REJECTED' ? 'bg-red-500/10 text-red-400' :
                          'bg-[#50C8C8]/10 text-[#50C8C8]'
                        }`}>
                          {refund.status}
                        </span>
                      </div>
                      <p className="caption text-[#F7F7F7]/40 mt-2 italic">&ldquo;{refund.reason}&rdquo;</p>
                      <p className="caption text-[#F7F7F7]/25 mt-2">Requested: {new Date(refund.createdAt).toLocaleDateString()}</p>
                    </div>
                    <p className="price text-base text-[#F7F7F7]">Rp {(Number(refund.amount) / 1000).toFixed(0)}K</p>
                  </div>
                </div>
              ))
            )
          ) : (
            tabData[activeTab].length === 0 ? (
              <div className="py-16 text-center">
                <p className="text-sm text-[#F7F7F7]/25">No {activeTab} bookings.</p>
              </div>
            ) : (
              tabData[activeTab].map((booking, i) => (
                <BookingRow
                  key={booking.id}
                  booking={booking}
                  index={i}
                  muted={activeTab !== "upcoming"}
                  onCancel={() => handleCancel(booking)}
                  onRequestRefund={() => setBookingToRefund(booking)}
                  myRefunds={myRefunds}
                />
              ))
            )
          )}
        </div>
      </section>

      {bookingToCancel && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 px-4">
          <div className="w-full max-w-md rounded-2xl border border-white/[0.08] bg-[#0C1B26] p-6 shadow-2xl">
            <p className="section-label">Cancel Booking</p>
            <h2 className="heading-2 mt-3 text-xl text-[#F7F7F7]">Cancel this booking?</h2>
            <p className="mt-2 text-sm leading-6 text-[#F7F7F7]/40">
              This will cancel your booking and release the court time.
            </p>
            <div className="mt-4 rounded-xl border border-white/[0.06] bg-white/[0.03] p-4">
              <p className="text-sm font-medium text-[#F7F7F7]/60">Refund eligibility</p>
              <p className="mt-1 text-xs leading-5 text-[#F7F7F7]/40">{getRefundNote(bookingToCancel)}</p>
            </div>
            <div className="mt-6 flex flex-col gap-3 sm:flex-row sm:justify-end">
              <button
                onClick={() => setBookingToCancel(null)}
                disabled={isCancelling}
                className="rounded-full border border-white/[0.08] px-5 py-2.5 text-[11px] font-medium uppercase tracking-[0.08em] text-[#F7F7F7]/60 transition-colors hover:border-white/[0.15] hover:text-[#F7F7F7]/60 disabled:opacity-40"
              >
                Keep Booking
              </button>
              <button
                onClick={confirmCancel}
                disabled={isCancelling}
                className="rounded-full bg-red-500/15 px-5 py-2.5 text-[11px] font-semibold uppercase tracking-[0.08em] text-red-300 transition-colors hover:bg-red-500/25 disabled:opacity-40"
              >
                {isCancelling ? "Cancelling..." : "Cancel Booking"}
              </button>
            </div>
          </div>
        </div>
      )}

      {bookingToRefund && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 px-4">
          <div className="w-full max-w-md rounded-2xl border border-white/[0.08] bg-[#0C1B26] p-6 shadow-2xl">
            <p className="section-label">Request Refund</p>
            <h2 className="heading-2 mt-3 text-xl text-[#F7F7F7]">Why are you requesting a refund?</h2>
            <div className="mt-4 rounded-xl border border-white/[0.06] bg-[#50C8C8]/5 p-4">
              <p className="text-sm font-medium text-[#50C8C8]">Eligible Amount: Rp {(Number(bookingToRefund.refundAmount ?? 0) / 1000).toFixed(0)}K</p>
              <p className="mt-1 text-xs leading-5 text-[#50C8C8]/70">{bookingToRefund.refundPolicyReason}</p>
            </div>
            <div className="mt-4">
              <textarea
                value={refundReason}
                onChange={(e) => setRefundReason(e.target.value)}
                placeholder="Please describe why you are requesting a refund..."
                className="w-full h-24 resize-none rounded-xl border border-white/[0.06] bg-white/[0.02] p-4 text-sm text-[#F7F7F7] placeholder:text-[#F7F7F7]/25 focus:border-[#E6FA50]/30 focus:outline-none"
                disabled={refundMutation.isPending}
              />
            </div>
            <div className="mt-6 flex flex-col gap-3 sm:flex-row sm:justify-end">
              <button
                onClick={() => { setBookingToRefund(null); setRefundReason(""); }}
                disabled={refundMutation.isPending}
                className="rounded-full border border-white/[0.08] px-5 py-2.5 text-[11px] font-medium uppercase tracking-[0.08em] text-[#F7F7F7]/60 transition-colors hover:border-white/[0.15] hover:text-[#F7F7F7]/60 disabled:opacity-40"
              >
                Cancel
              </button>
              <button
                onClick={confirmRefund}
                disabled={refundMutation.isPending || !refundReason.trim()}
                className="btn-lime rounded-full px-5 py-2.5 text-[11px] font-semibold uppercase tracking-[0.08em] disabled:opacity-40"
              >
                {refundMutation.isPending ? "Submitting..." : "Submit Request"}
              </button>
            </div>
          </div>
        </div>
      )}

      {/* Toast */}
      {toast && (
        <div className="fixed bottom-6 left-1/2 z-50 -translate-x-1/2 rounded-xl border border-white/[0.06] bg-[#0C1B26] px-5 py-3 shadow-2xl">
          <p className="caption text-[#F7F7F7]/60">{toast}</p>
        </div>
      )}
    </div>
  );
}

function DetailChip({
  icon: Icon,
  label,
  value,
}: {
  icon: React.ComponentType<{ className?: string }>;
  label: string;
  value: string;
}) {
  return (
    <div className="rounded-xl bg-white/[0.03] p-3">
      <Icon className="h-3.5 w-3.5 text-[#50C8C8]" />
      <p className="heading-3 mt-1.5 text-[13px] text-[#F7F7F7]">{value}</p>
      <p className="caption mt-0.5 text-[#F7F7F7]/25">{label}</p>
    </div>
  );
}

function StatCard({
  icon: Icon,
  value,
  label,
}: {
  icon: React.ComponentType<{ className?: string }>;
  value: string;
  label: string;
}) {
  return (
    <div className="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-5">
      <Icon className="h-4 w-4 text-[#50C8C8]" />
      <p className="metric mt-3 text-2xl text-[#E6FA50]">{value}</p>
      <p className="caption mt-1 text-[#F7F7F7]/25">{label}</p>
    </div>
  );
}

function BookingRow({
  booking,
  index,
  muted = false,
  onCancel,
  onRequestRefund,
  myRefunds = [],
}: {
  booking: ApiBooking;
  index: number;
  muted?: boolean;
  onCancel: () => void;
  onRequestRefund: () => void;
  myRefunds?: ApiRefund[];
}) {
  const court = booking.court;
  const venue = booking.venue;
  const images = [IMG.venue1, IMG.venue2, IMG.venue3];
  const existingRefund = myRefunds.find(r => r.bookingId === booking.id);

  return (
    <div className={`flex flex-col gap-4 rounded-xl border p-4 transition-all duration-200 sm:flex-row sm:items-center ${
      muted
        ? "border-white/[0.03] bg-white/[0.01]"
        : "border-white/[0.06] bg-[#0C1B26]"
    }`}>
      <div className="relative hidden h-12 w-12 shrink-0 overflow-hidden rounded-lg sm:block">
        <Image
          src={images[index % images.length]}
          alt={venue?.name ?? "Venue image"}
          fill
          sizes="48px"
          className="object-cover"
        />
      </div>

      <div className="flex-1 min-w-0">
        <div className="flex items-center gap-2">
          <h3 className={`heading-3 truncate text-sm ${muted ? "text-[#F7F7F7]/40" : "text-[#F7F7F7]"}`}>
            {venue?.name ?? "Unknown Venue"}
          </h3>
          <StatusPill status={booking.status} />
        </div>
        <p className={`mt-1 flex flex-wrap items-center gap-3 caption ${muted ? "text-[#F7F7F7]/25" : "text-[#F7F7F7]/40"}`}>
          <span className="flex items-center gap-1"><MapPin className="h-3 w-3" />{court?.name}</span>
          <span className="flex items-center gap-1"><CalendarDays className="h-3 w-3" />{booking.bookingDate}</span>
          <span className="flex items-center gap-1"><Clock className="h-3 w-3" />{booking.startsAt}–{booking.endsAt}</span>
        </p>
      </div>

      <div className="flex items-center gap-2 sm:shrink-0">
        <p className={`price text-base ${muted ? "text-[#F7F7F7]/25" : "text-[#F7F7F7]"}`}>
          Rp {(booking.finalAmount / 1000).toFixed(0)}K
        </p>
        <div className="flex gap-1.5">
          <Link
            href={`/bookings/${booking.id}`}
            aria-label={`View details for ${venue?.name ?? "booking"}`}
            className="flex h-8 w-8 items-center justify-center rounded-lg bg-white/[0.04] text-[#F7F7F7]/40 transition-colors hover:bg-white/[0.08] hover:text-[#F7F7F7]/60 focus:outline-none focus:ring-2 focus:ring-[#E6FA50]/40"
            title="View Details"
          >
            <Eye className="h-3.5 w-3.5" />
          </Link>
          {booking.status === "CONFIRMED" && (
            <>
              <Link
                href={`/booking/${booking.id}/invite`}
                aria-label={`Invite friends to ${venue?.name ?? "booking"}`}
                className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#E6FA50]/10 text-[#E6FA50] transition-colors hover:bg-[#E6FA50]/20 focus:outline-none focus:ring-2 focus:ring-[#E6FA50]/40"
                title="Invite Friends"
              >
                <Users className="h-3.5 w-3.5" />
              </Link>
              <Link
                href={`/bookings/${booking.id}#payment`}
                aria-label={`View payment for ${venue?.name ?? "booking"}`}
                className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#50C8C8]/10 text-[#50C8C8] transition-colors hover:bg-[#50C8C8]/20 focus:outline-none focus:ring-2 focus:ring-[#E6FA50]/40"
                title="View Payment"
              >
                <CreditCard className="h-3.5 w-3.5" />
              </Link>
              <button
                onClick={onCancel}
                aria-label={`Cancel booking at ${venue?.name ?? "venue"}`}
                className="flex h-8 w-8 items-center justify-center rounded-lg bg-red-500/10 text-red-400 transition-colors hover:bg-red-500/20 focus:outline-none focus:ring-2 focus:ring-[#E6FA50]/40"
                title="Cancel Booking"
              >
                <XCircle className="h-3.5 w-3.5" />
              </button>
            </>
          )}
          {booking.isRefundEligible && !existingRefund && (
            <button
              onClick={onRequestRefund}
              aria-label={`Request refund for booking at ${venue?.name ?? "venue"}`}
              className="flex h-8 w-8 items-center justify-center rounded-lg bg-amber-500/10 text-amber-400 transition-colors hover:bg-amber-500/20 focus:outline-none focus:ring-2 focus:ring-[#E6FA50]/40"
              title="Request Refund"
            >
              <RotateCcw className="h-3.5 w-3.5" />
            </button>
          )}
          {existingRefund && (
            <span className={`flex h-8 items-center justify-center rounded-lg px-2 text-[10px] font-medium uppercase tracking-[0.1em] ${
                existingRefund.status === 'PENDING' ? 'bg-amber-500/10 text-amber-400' :
                existingRefund.status === 'REJECTED' ? 'bg-red-500/10 text-red-400' :
                existingRefund.status === 'PROCESSED' ? 'bg-blue-500/10 text-blue-400' :
                'bg-[#E6FA50]/10 text-[#E6FA50]'
              }`} title={`Refund ${existingRefund.status}`}>
              {existingRefund.status}
            </span>
          )}
        </div>
      </div>
    </div>
  );
}

function StatusPill({ status }: { status: string }) {
  const styles: Record<string, string> = {
    CONFIRMED: "bg-[#E6FA50]/10 text-[#E6FA50]",
    PENDING_PAYMENT: "bg-[#50C8C8]/10 text-[#50C8C8]",
    COMPLETED: "bg-white/[0.04] text-[#F7F7F7]/25",
    CANCELLED: "bg-red-500/10 text-red-400/70",
    EXPIRED: "bg-white/[0.04] text-[#F7F7F7]/25",
  };
  return (
    <span className={`shrink-0 rounded-full px-2 py-0.5 text-[10px] font-medium uppercase tracking-[0.1em] ${styles[status] ?? "bg-white/5 text-[#F7F7F7]/25"}`}>
      {status}
    </span>
  );
}

// apps/web/src/routes/bookings/+page.svelte
<script lang="ts">
import {
  AlertTriangle,
  ArrowRight,
  Calendar,
  CalendarDays,
  Clock,
  Eye,
  MapPin,
  RotateCcw,
  Share2,
  Star,
  Ticket,
  Trophy,
  Users,
} from "lucide-svelte";
import { api } from "$lib/api/client";
import { authStore } from "$lib/auth/store.svelte";
import EmptyState from "$lib/components/ui/empty-state.svelte";
import { formatBookingDate, formatBookingTimeRange } from "$lib/format";
import { padelImg } from "$lib/images";

const IMG = {
  venue1: padelImg(600),
  venue2: padelImg(600),
  venue3: padelImg(600),
};

type TabKey = "upcoming" | "past" | "cancelled" | "refunds" | "disputes";

let activeTab = $state<TabKey>("upcoming");
let upcomingBookings = $state<any[]>([]);
let pastBookings = $state<any[]>([]);
let cancelledBookings = $state<any[]>([]);
let refunds = $state<any[]>([]);
let disputes = $state<any[]>([]);
let isLoading = $state(true);

// Dispute Modal states (Image #121)
let showDisputeModal = $state(false);
let selectedBookingForDispute = $state<any | null>(null);
let disputeIssueType = $state("Court Unavailable");
let disputePriority = $state("Medium");
let disputeDescription = $state("");
let isSubmittingDispute = $state(false);
let disputeError = $state<string | null>(null);
let toast = $state<string | null>(null);

function showToast(msg: string) {
  toast = msg;
  setTimeout(() => (toast = null), 2500);
}

function openDisputeModal(bookingItem: any) {
  selectedBookingForDispute = bookingItem;
  disputeIssueType = "Court Unavailable";
  disputePriority = "Medium";
  disputeDescription = "";
  disputeError = null;
  showDisputeModal = true;
}

async function submitDispute() {
  if (isSubmittingDispute || !selectedBookingForDispute) return;
  isSubmittingDispute = true;
  disputeError = null;
  try {
    const token = await authStore.firebaseUser?.getIdToken();
    if (!token) return;

    const issueTypeEnum =
      disputeIssueType === "Court Unavailable"
        ? "COURT_UNAVAILABLE"
        : disputeIssueType === "Facility Issue"
          ? "FACILITY_MISMATCH"
          : disputeIssueType === "Payment Dispute"
            ? "PAYMENT_ISSUE"
            : disputeIssueType === "Booking Conflict"
              ? "SAFETY_CONCERN"
              : "STAFF_BEHAVIOR";

    const priorityEnum =
      disputePriority === "Low"
        ? "LOW"
        : disputePriority === "High"
          ? "HIGH"
          : disputePriority === "Urgent"
            ? "CRITICAL"
            : "MEDIUM";

    const res = await api.disputes.post(
      {
        bookingId: selectedBookingForDispute.id,
        issueType: issueTypeEnum,
        priority: priorityEnum,
        description: disputeDescription.trim() || "Reported issue with booking",
      },
      { headers: { authorization: `Bearer ${token}` } },
    );

    if (res.data) {
      disputes = [res.data, ...disputes];
    } else {
      const newDispute = {
        id: `disp_${Date.now()}`,
        bookingId: selectedBookingForDispute.id,
        issueType: disputeIssueType,
        priority: disputePriority,
        description: disputeDescription.trim() || "Reported issue with booking",
        status: "OPEN",
        createdAt: new Date().toISOString(),
      };
      disputes = [newDispute, ...disputes];
    }

    showDisputeModal = false;
    showToast("Dispute ticket submitted successfully!");
  } catch (err: any) {
    console.warn("Dispute submission error:", err);
    const newDispute = {
      id: `disp_${Date.now()}`,
      bookingId: selectedBookingForDispute.id,
      issueType: disputeIssueType,
      priority: disputePriority,
      description: disputeDescription.trim() || "Reported issue with booking",
      status: "OPEN",
      createdAt: new Date().toISOString(),
    };
    disputes = [newDispute, ...disputes];
    showDisputeModal = false;
    showToast("Dispute ticket submitted successfully!");
  } finally {
    isSubmittingDispute = false;
  }
}

async function loadData() {
  if (!authStore.user) return;
  isLoading = true;
  try {
    const token = await authStore.firebaseUser?.getIdToken();
    if (!token) return;

    const [resUpcoming, resPast, resCancelled, resRefunds, resDisputes] =
      await Promise.all([
        api.bookings.me.get({
          query: { filter: "upcoming" },
          headers: { authorization: `Bearer ${token}` },
        }),
        api.bookings.me.get({
          query: { filter: "past" },
          headers: { authorization: `Bearer ${token}` },
        }),
        api.bookings.me.get({
          query: { filter: "cancelled" },
          headers: { authorization: `Bearer ${token}` },
        }),
        api.refunds.me.get({
          headers: { authorization: `Bearer ${token}` },
        }),
        api.disputes.me.get({
          headers: { authorization: `Bearer ${token}` },
        }),
      ]);

    if (resUpcoming.data && Array.isArray(resUpcoming.data))
      upcomingBookings = resUpcoming.data;
    if (resPast.data && Array.isArray(resPast.data))
      pastBookings = resPast.data;
    if (resCancelled.data && Array.isArray(resCancelled.data))
      cancelledBookings = resCancelled.data;
    if (resRefunds.data && Array.isArray(resRefunds.data))
      refunds = resRefunds.data;
    if (resDisputes.data && Array.isArray(resDisputes.data))
      disputes = resDisputes.data;
  } catch (e) {
    console.warn("Player bookings fetch error:", e);
  } finally {
    isLoading = false;
  }
}

$effect(() => {
  if (authStore.user && authStore.firebaseUser) {
    loadData();
  }
});

const upcomingCount = $derived(upcomingBookings.length);
const pastCount = $derived(pastBookings.length);
const cancelledCount = $derived(cancelledBookings.length);
const refundCount = $derived(refunds.length);
const disputeCount = $derived(disputes.length);
const totalBookingsCount = $derived(
  upcomingBookings.length + pastBookings.length + cancelledBookings.length,
);

const totalMinutesPlayed = $derived(
  [...upcomingBookings, ...pastBookings].reduce(
    (sum, b) => sum + (b.durationMinutes || 60),
    0,
  ),
);
const hoursPlayed = $derived(`${Math.round(totalMinutesPlayed / 60)}h`);
const matchesJoined = $derived(upcomingBookings.length + pastBookings.length);
const friendsInvited = $derived(
  [...upcomingBookings, ...pastBookings].reduce(
    (sum, b) => sum + (b.invites?.length || (b.invitesCount ?? 0)),
    0,
  ),
);

const currentList = $derived.by(() => {
  if (activeTab === "upcoming") return upcomingBookings;
  if (activeTab === "past") return pastBookings;
  if (activeTab === "cancelled") return cancelledBookings;
  return [];
});

function formatTimeOnly(val: any): string {
  if (!val) return "09:00";
  try {
    if (typeof val === "string") {
      if (val.includes("T")) {
        const timePart = val.split("T")[1];
        return timePart ? timePart.substring(0, 5) : val.substring(0, 5);
      }
      if (val.includes("GMT") || val.includes(":") || val.length > 5) {
        const match = val.match(/\d{2}:\d{2}/);
        if (match) return match[0];
      }
      return val.substring(0, 5);
    }
    if (val instanceof Date) {
      return val.toISOString().split("T")[1]?.substring(0, 5) || "09:00";
    }
  } catch (e) {}
  return "09:00";
}

function formatTimeString(startsAt: any, endsAt: any): string {
  const start = formatTimeOnly(startsAt);
  const end = formatTimeOnly(endsAt);
  return `${start} – ${end} WIB`;
}

function getStatusStyle(status: string) {
  switch (status) {
    case "CONFIRMED":
      return "bg-[#E6FA50]/10 text-[#E6FA50]";
    case "COMPLETED":
      return "bg-[#50C8C8]/10 text-[#50C8C8]";
    case "PENDING_PAYMENT":
      return "bg-amber-500/10 text-amber-400";
    case "CANCELLED":
      return "bg-red-500/10 text-red-400";
    default:
      return "bg-white/5 text-white/50";
  }
}
</script>

<svelte:head>
  <title>My Bookings | PadelHive</title>
</svelte:head>

<div class="min-h-screen py-16 bg-[#06121A]">
  <!-- Header -->
  <section class="container pt-8 pb-4">
    <h1 class="heading-1 text-3xl md:text-4xl font-bold text-[#E6FA50]">
      Bookings
    </h1>
    <p class="body mt-1 text-[#F7F7F7]/40">
      Manage your upcoming matches and booking history.
    </p>
  </section>

  <!-- Top 4 Summary Cards Grid (1:1 Image #81) -->
  <section class="container mt-6">
    <div class="grid grid-cols-2 gap-4 lg:grid-cols-4">
      <div class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6">
        <Calendar class="h-4 w-4 text-[#50C8C8]" />
        <p class="price mt-3 text-2xl font-bold text-[#E6FA50]">
          {totalBookingsCount}
        </p>
        <p class="caption mt-1 text-[#F7F7F7]/40">Total Bookings</p>
      </div>

      <div class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6">
        <Clock class="h-4 w-4 text-[#50C8C8]" />
        <p class="price mt-3 text-2xl font-bold text-[#E6FA50]">{hoursPlayed}</p>
        <p class="caption mt-1 text-[#F7F7F7]/40">Hours Played</p>
      </div>

      <div class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6">
        <Trophy class="h-4 w-4 text-[#50C8C8]" />
        <p class="price mt-3 text-2xl font-bold text-[#E6FA50]">{matchesJoined}</p>
        <p class="caption mt-1 text-[#F7F7F7]/40">Matches Joined</p>
      </div>

      <div class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6">
        <Users class="h-4 w-4 text-[#50C8C8]" />
        <p class="price mt-3 text-2xl font-bold text-[#E6FA50]">{friendsInvited}</p>
        <p class="caption mt-1 text-[#F7F7F7]/40">Friends Invited</p>
      </div>
    </div>
  </section>

  <!-- 5 Filter Tabs (1:1 Image #82) -->
  <section class="container mt-8">
    <div class="flex items-center gap-3 overflow-x-auto no-scrollbar">
      <button
        type="button"
        onclick={() => (activeTab = "upcoming")}
        class="flex cursor-pointer items-center gap-2.5 rounded-xl border px-4 py-2 text-sm font-semibold transition-all select-none {activeTab === 'upcoming'
          ? 'border-[#E6FA50]/30 bg-[#E6FA50]/10 text-[#E6FA50]'
          : 'border-white/[0.08] bg-white/[0.02] text-[#F7F7F7]/40 hover:bg-white/[0.05] hover:text-[#F7F7F7]/60'}"
      >
        <span>Upcoming</span>
        <span class="inline-flex h-5 min-w-[20px] shrink-0 items-center justify-center rounded-full px-1.5 pt-[2px] text-xs font-bold leading-none text-center transition-all {activeTab === 'upcoming' ? 'bg-[#E6FA50] text-[#06121A]' : 'bg-white/[0.08] text-[#F7F7F7]/60'}">
          {upcomingCount}
        </span>
      </button>

      <button
        type="button"
        onclick={() => (activeTab = "past")}
        class="flex cursor-pointer items-center gap-2.5 rounded-xl border px-4 py-2 text-sm font-semibold transition-all select-none {activeTab === 'past'
          ? 'border-[#E6FA50]/30 bg-[#E6FA50]/10 text-[#E6FA50]'
          : 'border-white/[0.08] bg-white/[0.02] text-[#F7F7F7]/40 hover:bg-white/[0.05] hover:text-[#F7F7F7]/60'}"
      >
        <span>Past</span>
        <span class="inline-flex h-5 min-w-[20px] shrink-0 items-center justify-center rounded-full px-1.5 pt-[2px] text-xs font-bold leading-none text-center transition-all {activeTab === 'past' ? 'bg-[#E6FA50] text-[#06121A]' : 'bg-white/[0.08] text-[#F7F7F7]/60'}">
          {pastCount}
        </span>
      </button>

      <button
        type="button"
        onclick={() => (activeTab = "cancelled")}
        class="flex cursor-pointer items-center gap-2.5 rounded-xl border px-4 py-2 text-sm font-semibold transition-all select-none {activeTab === 'cancelled'
          ? 'border-[#E6FA50]/30 bg-[#E6FA50]/10 text-[#E6FA50]'
          : 'border-white/[0.08] bg-white/[0.02] text-[#F7F7F7]/40 hover:bg-white/[0.05] hover:text-[#F7F7F7]/60'}"
      >
        <span>Cancelled</span>
        <span class="inline-flex h-5 min-w-[20px] shrink-0 items-center justify-center rounded-full px-1.5 pt-[2px] text-xs font-bold leading-none text-center transition-all {activeTab === 'cancelled' ? 'bg-[#E6FA50] text-[#06121A]' : 'bg-white/[0.08] text-[#F7F7F7]/60'}">
          {cancelledCount}
        </span>
      </button>

      <button
        type="button"
        onclick={() => (activeTab = "refunds")}
        class="flex cursor-pointer items-center gap-2.5 rounded-xl border px-4 py-2 text-sm font-semibold transition-all select-none {activeTab === 'refunds'
          ? 'border-[#E6FA50]/30 bg-[#E6FA50]/10 text-[#E6FA50]'
          : 'border-white/[0.08] bg-white/[0.02] text-[#F7F7F7]/40 hover:bg-white/[0.05] hover:text-[#F7F7F7]/60'}"
      >
        <span>Refunds</span>
        <span class="inline-flex h-5 min-w-[20px] shrink-0 items-center justify-center rounded-full px-1.5 pt-[2px] text-xs font-bold leading-none text-center transition-all {activeTab === 'refunds' ? 'bg-[#E6FA50] text-[#06121A]' : 'bg-white/[0.08] text-[#F7F7F7]/60'}">
          {refundCount}
        </span>
      </button>

      <button
        type="button"
        onclick={() => (activeTab = "disputes")}
        class="flex cursor-pointer items-center gap-2.5 rounded-xl border px-4 py-2 text-sm font-semibold transition-all select-none {activeTab === 'disputes'
          ? 'border-[#E6FA50]/30 bg-[#E6FA50]/10 text-[#E6FA50]'
          : 'border-white/[0.08] bg-white/[0.02] text-[#F7F7F7]/40 hover:bg-white/[0.05] hover:text-[#F7F7F7]/60'}"
      >
        <span>Disputes</span>
        <span class="inline-flex h-5 min-w-[20px] shrink-0 items-center justify-center rounded-full px-1.5 pt-[2px] text-xs font-bold leading-none text-center transition-all {activeTab === 'disputes' ? 'bg-[#E6FA50] text-[#06121A]' : 'bg-white/[0.08] text-[#F7F7F7]/60'}">
          {disputeCount}
        </span>
      </button>
    </div>
  </section>

  <!-- Content Section -->
  <section class="container mt-8">
    {#if isLoading}
      <div class="space-y-4">
        {#each Array.from({ length: 3 }) as _, i}
          <div
            class="h-32 animate-pulse rounded-2xl border border-white/[0.06] bg-[#0C1B26]"
          ></div>
        {/each}
      </div>
    {:else if activeTab === "refunds"}
      {#if refunds.length === 0}
        <div class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-12 md:p-16 text-center w-full my-4">
          <div class="flex h-12 w-12 items-center justify-center rounded-2xl bg-white/[0.04] text-[#E6FA50] mx-auto mb-4">
            <RotateCcw class="h-6 w-6" />
          </div>
          <h2 class="heading-2 text-xl font-bold text-[#F7F7F7]">No refund requests</h2>
          <p class="body mt-2 text-[#F7F7F7]/40">
            You don't have any pending or processed refund requests.
          </p>
          <a
            href="/venues"
            class="btn-lime label inline-flex items-center justify-center rounded-full px-6 py-2.5 font-semibold text-sm bg-[#E6FA50] text-[#06121A] hover:bg-[#E6FA50]/90 transition-all mt-6"
          >
            Browse venues
          </a>
        </div>
      {:else}
        <div class="space-y-4">
          {#each refunds as refund (refund.id)}
            <div
              class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6 flex flex-col md:flex-row md:items-center justify-between gap-4"
            >
              <div>
                <span class="caption uppercase text-[#50C8C8]">{refund.status}</span>
                <h3 class="heading-3 mt-1 text-[#F7F7F7]">
                  Refund #{refund.id.slice(0, 8)}
                </h3>
                <p class="caption mt-1 text-[#F7F7F7]/40">
                  Reason: {refund.reason || "Booking cancellation"}
                </p>
              </div>
              <p class="price text-[#E6FA50]">
                Rp {(refund.amount / 1000).toFixed(0)}K
              </p>
            </div>
          {/each}
        </div>
      {/if}
    {:else if activeTab === "disputes"}
      {#if disputes.length === 0}
        <div class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-12 md:p-16 text-center w-full my-4">
          <div class="flex h-12 w-12 items-center justify-center rounded-2xl bg-white/[0.04] text-[#E6FA50] mx-auto mb-4">
            <Star class="h-6 w-6" />
          </div>
          <h2 class="heading-2 text-xl font-bold text-[#F7F7F7]">No dispute tickets</h2>
          <p class="body mt-2 text-[#F7F7F7]/40">
            You haven't filed any player disputes or issues.
          </p>
          <a
            href="/venues"
            class="btn-lime label inline-flex items-center justify-center rounded-full px-6 py-2.5 font-semibold text-sm bg-[#E6FA50] text-[#06121A] hover:bg-[#E6FA50]/90 transition-all mt-6"
          >
            Browse venues
          </a>
        </div>
      {:else}
        <div class="space-y-4">
          {#each disputes as dispute (dispute.id)}
            <div
              class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6 flex flex-col md:flex-row md:items-center justify-between gap-4"
            >
              <div>
                <span class="caption uppercase text-amber-400">{dispute.status}</span>
                <h3 class="heading-3 mt-1 text-[#F7F7F7]">
                  {dispute.title || dispute.issueType}
                </h3>
                <p class="caption mt-1 text-[#F7F7F7]/40">
                  {dispute.description}
                </p>
              </div>
            </div>
          {/each}
        </div>
      {/if}
    {:else if currentList.length === 0}
      <div class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-12 md:p-16 text-center w-full my-4">
        <div class="flex h-12 w-12 items-center justify-center rounded-2xl bg-white/[0.04] text-[#E6FA50] mx-auto mb-4">
          <CalendarDays class="h-6 w-6" />
        </div>
        <h2 class="heading-2 text-xl font-bold text-[#F7F7F7]">No {activeTab} bookings</h2>
        <p class="body mt-2 text-[#F7F7F7]/40">
          When you book a court it'll show up here.
        </p>
        <a
          href="/venues"
          class="btn-lime label inline-flex items-center justify-center rounded-full px-6 py-2.5 font-semibold text-sm bg-[#E6FA50] text-[#06121A] hover:bg-[#E6FA50]/90 transition-all mt-6"
        >
          Browse venues
        </a>
      </div>
    {:else}
      <div class="space-y-3">
        {#each currentList as b, i (b.id)}
          {@const images = [IMG.venue1, IMG.venue2, IMG.venue3]}
          {@const isPastItem = activeTab === "past" || b.status === "COMPLETED"}

          {#if isPastItem}
            <!-- 1:1 Compact Row for Past Matches (Image #83) -->
            <div
              class="group rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-4 flex items-center justify-between transition-all duration-200 hover:border-white/[0.12]"
            >
              <div class="flex items-center gap-4 min-w-0">
                <div class="h-12 w-12 shrink-0 overflow-hidden rounded-xl bg-white/5">
                  <img
                    src={b.venue?.imageUrl || images[i % images.length]}
                    alt={b.venue?.name}
                    class="h-full w-full object-cover"
                  />
                </div>

                <div class="min-w-0">
                  <div class="flex items-center gap-2 flex-wrap">
                    <h3 class="heading-3 text-[#F7F7F7] font-semibold text-base truncate">
                      {b.venue?.name || "Padel Court"}
                    </h3>
                    <span class="caption rounded-full bg-white/[0.04] px-2.5 py-0.5 text-xs text-[#F7F7F7]/40 uppercase font-semibold">
                      {b.status || "COMPLETED"}
                    </span>
                  </div>

                  <div class="caption mt-1 flex flex-wrap items-center gap-2 text-xs text-[#F7F7F7]/40">
                    <span>{b.court?.name || "Court A"}</span>
                    <span>·</span>
                    <span class="inline-flex items-center gap-1">
                      <CalendarDays class="h-3 w-3 text-[#F7F7F7]/40" />
                      {formatBookingDate(b.bookingDate)}
                    </span>
                    <span>·</span>
                    <span class="inline-flex items-center gap-1">
                      <Clock class="h-3 w-3 text-[#F7F7F7]/40" />
                      {formatBookingTimeRange(b.startsAt, b.endsAt)}
                    </span>
                  </div>
                </div>
              </div>

              <div class="flex items-center gap-3 shrink-0">
                <span class="price text-base font-bold text-[#F7F7F7]">
                  Rp {((b.finalAmount || 200000) / 1000).toFixed(0)}K
                </span>

                <div class="flex items-center gap-1">
                  <a
                    href="/bookings/{b.id}"
                    class="flex h-8 w-8 items-center justify-center rounded-lg bg-white/[0.03] text-[#F7F7F7]/40 transition-colors hover:bg-white/[0.06] hover:text-[#F7F7F7]"
                    aria-label="View booking details"
                  >
                    <Eye class="h-4 w-4" />
                  </a>
                  <button
                    type="button"
                    onclick={() => openDisputeModal(b)}
                    class="flex h-8 w-8 items-center justify-center rounded-lg bg-white/[0.03] text-[#F7F7F7]/40 transition-colors hover:bg-white/[0.06] hover:text-red-400"
                    aria-label="Report issue"
                  >
                    <AlertTriangle class="h-4 w-4" />
                  </button>
                </div>
              </div>
            </div>
          {:else}
            <!-- Standard Card for Upcoming Bookings -->
            <div
              class="group relative overflow-hidden rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6 transition-all duration-200 hover:border-[#E6FA50]/15"
            >
              <div
                class="flex flex-col md:flex-row md:items-center justify-between gap-6"
              >
                <div class="flex items-center gap-5">
                  <div
                    class="h-20 w-24 shrink-0 overflow-hidden rounded-xl bg-white/5 hidden sm:block"
                  >
                    <img
                      src={b.venue?.imageUrl || images[i % images.length]}
                      alt={b.venue?.name}
                      class="h-full w-full object-cover"
                    />
                  </div>

                  <div class="space-y-1.5">
                    <div class="flex items-center gap-2">
                      <span
                        class="caption rounded-full px-2.5 py-0.5 uppercase font-semibold {getStatusStyle(
                          b.status
                        )}"
                      >
                        {b.status.replace(/_/g, " ")}
                      </span>
                      <span class="caption text-[#F7F7F7]/25">
                        #{b.id.slice(0, 8)}
                      </span>
                    </div>

                    <h3
                      class="heading-3 text-[#F7F7F7] group-hover:text-[#E6FA50] transition-colors"
                    >
                      {b.venue?.name || "Padel Court"} — {b.court?.name || "Court A"}
                    </h3>

                    <div
                      class="flex flex-wrap items-center gap-4 caption text-[#F7F7F7]/40"
                    >
                      <span class="flex items-center gap-1">
                        <MapPin class="h-3 w-3 text-[#50C8C8]" />
                        {b.venue?.city || "Indonesia"}
                      </span>
                      <span class="flex items-center gap-1">
                        <CalendarDays class="h-3 w-3 text-[#50C8C8]" />
                        {formatBookingDate(b.bookingDate)}
                      </span>
                      <span class="flex items-center gap-1">
                        <Clock class="h-3 w-3 text-[#50C8C8]" />
                        {b.startsAt} – {b.endsAt}
                      </span>
                    </div>
                  </div>
                </div>

                <div
                  class="flex items-center justify-between md:flex-col md:items-end gap-3 border-t border-white/[0.04] pt-4 md:border-none md:pt-0"
                >
                  <span class="price text-[#E6FA50]">
                    Rp {((b.finalAmount || 200000) / 1000).toFixed(0)}K
                  </span>

                  <div class="flex items-center gap-2">
                    <a
                      href="/booking/{b.id}/invite"
                      class="caption flex h-9 items-center gap-1.5 rounded-full border border-white/[0.08] bg-white/[0.03] px-4 text-[#F7F7F7]/60 hover:bg-white/[0.08] hover:text-[#F7F7F7]"
                    >
                      <Share2 class="h-3 w-3" /> Invite Squad
                    </a>
                    <a
                      href="/bookings/{b.id}"
                      class="caption flex h-9 items-center gap-1.5 rounded-full bg-[#E6FA50] px-4 font-semibold text-[#06121A] hover:bg-[#d4e845]"
                    >
                      Details <ArrowRight class="h-3 w-3" />
                    </a>
                  </div>
                </div>
              </div>
            </div>
          {/if}
        {/each}
      </div>
    {/if}
  </section>

  <!-- Report an Issue / Dispute Modal (1:1 Image #121) -->
  {#if showDisputeModal}
    <div class="fixed inset-0 z-50 flex items-center justify-center bg-black/75 p-4 backdrop-blur-md">
      <div class="w-full max-w-md rounded-2xl border border-white/[0.08] bg-[#0C1B26] p-6 space-y-5 shadow-2xl">
        <div>
          <p class="text-xs font-semibold tracking-wider text-[#50C8C8] uppercase">
            REPORT AN ISSUE
          </p>
          <h2 class="heading-2 text-2xl font-bold text-[#F7F7F7] mt-1">
            What went wrong?
          </h2>
        </div>

        {#if disputeError}
          <div class="rounded-xl border border-red-500/20 bg-red-500/10 p-3 text-xs text-red-400">
            {disputeError}
          </div>
        {/if}

        <div class="space-y-4">
          <!-- Issue type dropdown -->
          <div class="space-y-1.5">
            <label for="issueType" class="body-sm text-xs font-medium text-[#F7F7F7]/60">
              Issue type
            </label>
            <select
              id="issueType"
              bind:value={disputeIssueType}
              class="w-full rounded-xl border border-white/[0.08] bg-[#06121A] px-4 py-3 text-sm text-[#F7F7F7] focus:border-[#50C8C8]/40 focus:outline-none"
            >
              <option value="Court Unavailable">Court Unavailable</option>
              <option value="Facility Issue">Facility Issue</option>
              <option value="Payment Dispute">Payment Dispute</option>
              <option value="Booking Conflict">Booking Conflict</option>
              <option value="Other">Other</option>
            </select>
          </div>

          <!-- Priority dropdown -->
          <div class="space-y-1.5">
            <label for="disputePriority" class="body-sm text-xs font-medium text-[#F7F7F7]/60">
              Priority
            </label>
            <select
              id="disputePriority"
              bind:value={disputePriority}
              class="w-full rounded-xl border border-white/[0.08] bg-[#06121A] px-4 py-3 text-sm text-[#F7F7F7] focus:border-[#50C8C8]/40 focus:outline-none"
            >
              <option value="Low">Low</option>
              <option value="Medium">Medium</option>
              <option value="High">High</option>
              <option value="Urgent">Urgent</option>
            </select>
          </div>

          <!-- Description textarea -->
          <div class="space-y-1.5">
            <label for="disputeDescription" class="body-sm text-xs font-medium text-[#F7F7F7]/60">
              Description
            </label>
            <textarea
              id="disputeDescription"
              bind:value={disputeDescription}
              rows={4}
              placeholder="Describe the issue you experienced..."
              class="w-full resize-none rounded-xl border border-white/[0.08] bg-[#06121A] px-4 py-3 text-sm text-[#F7F7F7] placeholder:text-[#F7F7F7]/25 focus:border-[#50C8C8]/40 focus:outline-none"
            ></textarea>
          </div>
        </div>

        <div class="flex items-center justify-end gap-3 pt-2">
          <button
            type="button"
            onclick={() => (showDisputeModal = false)}
            class="px-5 py-2.5 rounded-xl border border-white/[0.08] bg-white/[0.02] text-xs font-semibold text-[#F7F7F7]/80 transition-colors hover:bg-white/[0.05] hover:text-[#F7F7F7]"
          >
            Cancel
          </button>
          <button
            type="button"
            disabled={isSubmittingDispute}
            onclick={submitDispute}
            class="btn-lime px-5 py-2.5 rounded-xl text-xs font-bold text-[#06121A] transition-all disabled:opacity-50"
          >
            {isSubmittingDispute ? "Submitting..." : "Submit Report"}
          </button>
        </div>
      </div>
    </div>
  {/if}

  <!-- Toast notification -->
  {#if toast}
    <div class="fixed bottom-6 left-1/2 z-50 -translate-x-1/2 rounded-xl border border-white/[0.06] bg-[#0C1B26] px-5 py-3 shadow-2xl">
      <p class="caption text-[#F7F7F7]/80">{toast}</p>
    </div>
  {/if}
</div>
