// apps/web/src/routes/notifications/+page.svelte
<script lang="ts">
import { Bell, CheckCheck, Loader2 } from "lucide-svelte";
import { onMount } from "svelte";
import { api } from "$lib/api/client";
import { authStore } from "$lib/auth/store.svelte";
import Button from "$lib/components/ui/button.svelte";
import Card from "$lib/components/ui/card.svelte";
import Skeleton from "$lib/components/ui/skeleton.svelte";

let notifications = $state<any[]>([]);
let isLoading = $state(true);
let isMarkingAll = $state(false);

async function loadNotifications() {
  isLoading = true;
  try {
    const token = await authStore.firebaseUser?.getIdToken();
    if (!token) return;

    const res = await api.notifications.get({
      headers: { authorization: `Bearer ${token}` },
    });
    if (res.data) {
      notifications = res.data;
    }
  } catch (e) {
    console.warn("Notifications load error:", e);
  } finally {
    isLoading = false;
  }
}

async function markAllRead() {
  isMarkingAll = true;
  try {
    const token = await authStore.firebaseUser?.getIdToken();
    if (!token) return;

    await api.notifications["read-all"].patch(undefined, {
      headers: { authorization: `Bearer ${token}` },
    });
    await loadNotifications();
  } catch (e) {
    console.warn("Mark all read error:", e);
  } finally {
    isMarkingAll = false;
  }
}

async function markRead(id: string) {
  try {
    const token = await authStore.firebaseUser?.getIdToken();
    if (!token) return;

    await api.notifications({ id }).read.patch(undefined, {
      headers: { authorization: `Bearer ${token}` },
    });
    notifications = notifications.map((n) =>
      n.id === id ? { ...n, isRead: true } : n,
    );
  } catch (e) {
    console.warn("Mark read error:", e);
  }
}

onMount(() => {
  loadNotifications();
});
</script>

<svelte:head>
  <title>Notifications - Padelhive</title>
</svelte:head>

<div class="py-12 bg-[#06121A]">
  <div class="container max-w-2xl space-y-6">
    <div class="flex items-center justify-between">
      <div>
        <h1 class="text-3xl font-extrabold text-white">Notifications</h1>
        <p class="mt-1 text-xs text-white/60">Updates on your bookings, payments, and invites</p>
      </div>

      <Button
        variant="secondary"
        size="sm"
        disabled={isMarkingAll || notifications.length === 0}
        onclick={markAllRead}
      >
        {#if isMarkingAll}
          <Loader2 class="h-3.5 w-3.5 animate-spin" />
        {:else}
          <CheckCheck class="h-3.5 w-3.5" />
        {/if}
        Mark All Read
      </Button>
    </div>

    {#if isLoading}
      <div class="space-y-3">
        {#each [1, 2, 3] as _}
          <Card class="p-4 space-y-2">
            <Skeleton class="h-5 w-1/3" />
            <Skeleton class="h-4 w-2/3" />
          </Card>
        {/each}
      </div>
    {:else if notifications.length === 0}
      <Card class="flex flex-col items-center justify-center p-12 text-center">
        <Bell class="mb-3 h-10 w-10 text-white/30" />
        <h3 class="text-lg font-semibold text-white">No Notifications</h3>
        <p class="mt-1 text-xs text-white/50">You're all caught up! Updates will appear here.</p>
      </Card>
    {:else}
      <div class="space-y-3">
        {#each notifications as n (n.id)}
          <div
            class="flex items-start justify-between rounded-xl border p-4 transition-colors {n.isRead ? 'border-white/[0.04] bg-[#0C1B26]' : 'border-[#E6FA50]/20 bg-[#0F2432]'}"
          >
            <div class="space-y-1">
              <h4 class="text-sm font-bold text-white">{n.title}</h4>
              <p class="text-xs text-white/70">{n.body}</p>
              {#if n.linkUrl}
                <a href={n.linkUrl} class="mt-2 inline-block text-xs font-semibold text-[#E6FA50] hover:underline">
                  View Details →
                </a>
              {/if}
            </div>

            {#if !n.isRead}
              <button
                type="button"
                onclick={() => markRead(n.id)}
                class="text-[10px] font-semibold text-[#E6FA50] hover:underline"
              >
                Mark Read
              </button>
            {/if}
          </div>
        {/each}
      </div>
    {/if}
  </div>
</div>

// apps/web/src/app/(app)/notifications/page.tsx
"use client";

import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { queryKeys } from "@/lib/queries";
import {
  getNotifications,
  getUnreadNotificationCount,
  markNotificationRead,
  markAllNotificationsRead,
} from "@/lib/api";
import { useRouter } from "next/navigation";
import { Bell } from "lucide-react";
import { ErrorBanner, EmptyState } from "@/components/ui/error-state";
import { formatRelativeTime } from "@/lib/format";
import { NotificationIcon } from "@/components/shared/notification-icon";

export default function NotificationsPage() {
  const router = useRouter();
  const queryClient = useQueryClient();

  const { data: unreadCount = 0 } = useQuery({
    queryKey: queryKeys.notifications.unreadCount(),
    queryFn: getUnreadNotificationCount,
  });

  const { data: notifications = [], isLoading, isError, error: queryError, refetch, isFetching } = useQuery({
    queryKey: queryKeys.notifications.list(),
    queryFn: getNotifications,
  });

  const markReadMutation = useMutation({
    mutationFn: markNotificationRead,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.notifications.list() });
      queryClient.invalidateQueries({ queryKey: queryKeys.notifications.unreadCount() });
    },
  });

  const markAllReadMutation = useMutation({
    mutationFn: markAllNotificationsRead,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.notifications.list() });
      queryClient.invalidateQueries({ queryKey: queryKeys.notifications.unreadCount() });
    },
  });

  const handleItemClick = (id: string, isRead: boolean, linkUrl: string | null) => {
    if (!isRead) {
      markReadMutation.mutate(id);
    }
    if (linkUrl) {
      router.push(linkUrl);
    }
  };

  const handleMarkAllRead = () => {
    if (unreadCount > 0) {
      markAllReadMutation.mutate();
    }
  };

  if (isLoading) {
    return (
      <div className="min-h-screen pt-28">
        <section className="container pb-8">
          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
            <div>
              <h1 className="heading-1 text-[#F7F7F7]">
                <span className="text-[#E6FA50]">Notifications</span>
              </h1>
              <p className="body-lg mt-2 text-[#F7F7F7]/40">
                Stay updated with your latest alerts.
              </p>
            </div>
            <button disabled className="label rounded-full border border-white/[0.08] px-5 py-2.5 text-[#F7F7F7]/60 opacity-40">
              Mark all as read
            </button>
          </div>
        </section>
        <section className="container pb-10">
          <div className="space-y-3">
            {[...Array(5)].map((_, i) => (
              <div key={i} className="h-24 w-full animate-pulse rounded-2xl border border-white/[0.06] bg-[#0C1B26]" />
            ))}
          </div>
        </section>
      </div>
    );
  }

  if (isError) {
    return (
      <div className="min-h-screen pt-28">
        <section className="container pb-8">
          <h1 className="heading-1 text-[#F7F7F7]">
            <span className="text-[#E6FA50]">Notifications</span>
          </h1>
          <p className="body-lg mt-2 text-[#F7F7F7]/40">
            Stay updated with your latest alerts.
          </p>
        </section>
        <section className="container pb-section-sm">
          <ErrorBanner
            title="Couldn't load notifications"
            error={queryError}
            onRetry={() => refetch()}
            isRetrying={isFetching}
          />
        </section>
      </div>
    );
  }

  return (
    <div className="min-h-screen pt-28">
      <section className="container pb-8">
        <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
          <div>
            <h1 className="heading-1 text-[#F7F7F7]">
              <span className="text-[#E6FA50]">Notifications</span>
            </h1>
            <p className="body-lg mt-2 text-[#F7F7F7]/40">
              Stay updated with your latest alerts.
            </p>
          </div>
          <button
            onClick={handleMarkAllRead}
            disabled={unreadCount === 0 || markAllReadMutation.isPending}
            className="label rounded-full border border-white/[0.08] px-5 py-2.5 text-[#F7F7F7]/60 transition-colors hover:border-white/[0.15] hover:text-[#F7F7F7]/80 disabled:opacity-40"
          >
            Mark all as read
          </button>
        </div>
      </section>

      <section className="container pb-section-sm">
        <div className="space-y-3">
          {notifications.length === 0 ? (
            <EmptyState
              icon={Bell}
              title="You're all caught up"
              description="No new notifications to show."
            />
          ) : (
            notifications.map((n) => (
              <button
                key={n.id}
                onClick={() => handleItemClick(n.id, n.isRead, n.linkUrl)}
                className={`w-full flex items-start gap-4 rounded-xl border p-4 text-left transition-colors ${
                  !n.isRead ? "border-white/[0.06] bg-[#0C1B26]" : "border-white/[0.03] bg-white/[0.01]"
                } hover:bg-white/[0.03]`}
              >
                <div className="relative shrink-0">
                  <NotificationIcon type={n.type} />
                  {!n.isRead && (
                    <span className="absolute -top-0.5 -right-0.5 h-2 w-2 rounded-full bg-[#E6FA50]" />
                  )}
                </div>
                <div className="flex-1 min-w-0">
                  <p className={`label ${!n.isRead ? "text-[#F7F7F7]" : "text-[#F7F7F7]/60"}`}>{n.title}</p>
                  <p className={`caption mt-1 ${!n.isRead ? "text-[#F7F7F7]/60" : "text-[#F7F7F7]/40"}`}>
                    {n.body}
                  </p>
                  <p className="caption mt-1.5 text-[#F7F7F7]/25">
                    {formatRelativeTime(n.createdAt)}
                  </p>
                </div>
              </button>
            ))
          )}
        </div>
      </section>
    </div>
  );
}
