// apps/web/src/app/dashboard/venues/page.tsx
"use client";

import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import {
  Building2,
  CheckCircle2,
  Clock,
  Edit3,
  Eye,
  Loader2,
  type LucideIcon,
  MapPin,
  MoreVertical,
  Plus,
  Star,
  X,
  XCircle,
} from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import { EmptyState, ErrorBanner } from "@/components/ui/error-state";
import {
  createVenue,
  getApiErrorMessage,
  getVenuesManage,
  type UpdateVenueInput,
  updateVenue,
  uploadVenueImage,
  type VenueInput,
} from "@/lib/api";
import { queryKeys } from "@/lib/queries";
import type { Venue } from "@/types";

const STATUS_CONFIG: Record<
  string,
  { label: string; icon: LucideIcon; color: string; bg: string }
> = {
  APPROVED: {
    label: "Approved",
    icon: CheckCircle2,
    color: "text-green-400",
    bg: "bg-green-400/10",
  },
  PENDING: {
    label: "Pending Review",
    icon: Clock,
    color: "text-yellow-400",
    bg: "bg-yellow-400/10",
  },
  REJECTED: {
    label: "Rejected",
    icon: XCircle,
    color: "text-red-400",
    bg: "bg-red-400/10",
  },
  SUSPENDED: {
    label: "Suspended",
    icon: XCircle,
    color: "text-orange-400",
    bg: "bg-orange-400/10",
  },
};

export default function VenueManagementPage() {
  const queryClient = useQueryClient();
  const [showAddModal, setShowAddModal] = useState(false);
  const [editVenue, setEditVenue] = useState<Venue | null>(null);
  const [toast, setToast] = useState<string | null>(null);

  const {
    data: venues = [],
    isLoading,
    isError,
    error,
    refetch,
    isFetching,
  } = useQuery({
    queryKey: queryKeys.venues.manage(),
    queryFn: getVenuesManage,
  });

  const createMutation = useMutation({
    mutationFn: createVenue,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.venues.manage() });
      setShowAddModal(false);
      showToast("Venue submitted for approval.");
    },
    onError: (err) => {
      showToast(getApiErrorMessage(err));
    },
  });

  const updateMutation = useMutation({
    mutationFn: ({ id, data }: { id: string; data: UpdateVenueInput }) =>
      updateVenue(id, data),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: queryKeys.venues.manage() });
      setEditVenue(null);
      showToast("Venue updated.");
    },
    onError: (err) => {
      showToast(getApiErrorMessage(err));
    },
  });

  function showToast(msg: string) {
    setToast(msg);
    setTimeout(() => setToast(null), 3000);
  }

  return (
    <div className="py-8">
      <section className="container">
        {/* Header */}
        <div className="flex flex-col items-start justify-between gap-4 sm:flex-row sm:items-end">
          <div>
            <h1 className="heading-1 text-[#F7F7F7]">Venues</h1>
            <p className="body mt-1 text-[#F7F7F7]/40">
              Manage your padel venues
            </p>
          </div>
          <button
            onClick={() => setShowAddModal(true)}
            className="label btn-lime flex h-11 w-full items-center justify-center gap-2 rounded-full px-5 sm:h-10 sm:w-auto"
          >
            <Plus className="h-4 w-4" />
            Add Venue
          </button>
        </div>

        {/* Venue List */}
        <div className="mt-8 space-y-4">
          {isLoading ? (
            [...Array(2)].map((_, i) => (
              <div
                key={i}
                className="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6"
              >
                <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-3">
                      <div className="h-6 w-48 animate-pulse rounded-md bg-white/[0.04]" />
                    </div>
                    <div className="mt-2 h-4 w-64 animate-pulse rounded-md bg-white/[0.04]" />
                    <div className="mt-4 flex flex-wrap items-center gap-4">
                      <div className="h-4 w-16 animate-pulse rounded-md bg-white/[0.04]" />
                      <div className="h-4 w-20 animate-pulse rounded-md bg-white/[0.04]" />
                      <div className="h-4 w-32 animate-pulse rounded-md bg-white/[0.04]" />
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    <div className="h-8 w-24 animate-pulse rounded-full bg-white/[0.04]" />
                    {[...Array(3)].map((_, j) => (
                      <div
                        key={j}
                        className="h-9 w-9 animate-pulse rounded-lg bg-white/[0.04]"
                      />
                    ))}
                  </div>
                </div>
                <div className="mt-4 flex flex-wrap gap-2 border-t border-white/[0.04] pt-4">
                  {[...Array(4)].map((_, j) => (
                    <div
                      key={j}
                      className="h-6 w-16 animate-pulse rounded-full bg-white/[0.04]"
                    />
                  ))}
                </div>
              </div>
            ))
          ) : isError ? (
            <ErrorBanner
              title="Couldn't load venues"
              error={error}
              onRetry={() => refetch()}
              isRetrying={isFetching}
            />
          ) : venues.length === 0 ? (
            <EmptyState
              icon={Building2}
              title="No venues yet"
              description="Add your first venue to start managing courts and bookings."
              actionLabel="Add Venue"
              onAction={() => setShowAddModal(true)}
            />
          ) : (
            venues.map((venue) => (
              <VenueCard
                key={venue.id}
                venue={venue}
                onEdit={(v) => setEditVenue(v)}
                showToast={showToast}
              />
            ))
          )}
        </div>

        {/* Modals */}
        {showAddModal && (
          <VenueFormModal
            mode="add"
            onClose={() => setShowAddModal(false)}
            onSubmit={(data) => createMutation.mutate(data as VenueInput)}
            isPending={createMutation.isPending}
          />
        )}
        {editVenue && (
          <VenueFormModal
            mode="edit"
            initial={editVenue}
            onClose={() => setEditVenue(null)}
            onSubmit={(data) =>
              updateMutation.mutate({
                id: editVenue.id,
                data: data as UpdateVenueInput,
              })
            }
            isPending={updateMutation.isPending}
          />
        )}

        {/* Toast */}
        {toast && (
          <div className="fixed bottom-6 left-1/2 z-50 -translate-x-1/2 rounded-xl border border-white/[0.08] bg-[#0C1B26] px-5 py-3 shadow-2xl shadow-black/40">
            <p className="body text-[#F7F7F7]/60">{toast}</p>
          </div>
        )}
      </section>
    </div>
  );
}

function VenueFormModal({
  mode,
  initial,
  onClose,
  onSubmit,
  isPending,
}: {
  mode: "add" | "edit";
  initial?: Venue;
  onClose: () => void;
  onSubmit: (data: VenueInput | UpdateVenueInput) => void;
  isPending: boolean;
}) {
  const [name, setName] = useState(initial?.name || "");
  const [location, setLocation] = useState(initial?.location || "");
  const [city, setCity] = useState(initial?.city || "");
  const [description, setDescription] = useState(initial?.description || "");
  const [openTime, setOpenTime] = useState(
    initial?.operatingHours?.open || "06:00",
  );
  const [closeTime, setCloseTime] = useState(
    initial?.operatingHours?.close || "23:00",
  );
  const [imageUrl, setImageUrl] = useState(initial?.imageUrl || "");
  const [coverError, setCoverError] = useState(false);
  const [photos, setPhotos] = useState<string[]>(initial?.photos ?? []);
  const [photoDraft, setPhotoDraft] = useState("");
  const [facilities, setFacilities] = useState<string[]>(
    initial?.facilities ?? [],
  );
  const [facilityDraft, setFacilityDraft] = useState("");

  const [isUploadingCover, setIsUploadingCover] = useState(false);
  const [isUploadingPhoto, setIsUploadingPhoto] = useState(false);

  const handleAddPhoto = () => {
    const val = photoDraft.trim();
    if (val && !photos.includes(val)) setPhotos([...photos, val]);
    setPhotoDraft("");
  };

  const handleAddFacility = () => {
    const val = facilityDraft.trim();
    if (val && !facilities.includes(val)) setFacilities([...facilities, val]);
    setFacilityDraft("");
  };

  const handleUploadCover = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    setIsUploadingCover(true);
    setCoverError(false);
    try {
      const url = await uploadVenueImage(file);
      setImageUrl(url);
    } catch (err: any) {
      alert(err.message || "Failed to upload image");
    } finally {
      setIsUploadingCover(false);
      e.target.value = "";
    }
  };

  const handleUploadPhoto = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    setIsUploadingPhoto(true);
    try {
      const url = await uploadVenueImage(file);
      if (!photos.includes(url)) {
        setPhotos((prev) => [...prev, url]);
      }
    } catch (err: any) {
      alert(err.message || "Failed to upload image");
    } finally {
      setIsUploadingPhoto(false);
      e.target.value = "";
    }
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (
      !name.trim() ||
      !location.trim() ||
      !city.trim() ||
      !description.trim() ||
      !openTime ||
      !closeTime
    ) {
      return;
    }
    onSubmit({
      name,
      location,
      city,
      description,
      openTime,
      closeTime,
      imageUrl: imageUrl.trim(),
      photos,
      facilities,
    });
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4">
      <div
        className="absolute inset-0 bg-[#06121A]/80 backdrop-blur-sm"
        onClick={onClose}
      />
      <div className="relative flex w-full max-w-lg max-h-[90vh] flex-col rounded-2xl border border-white/[0.06] bg-[#0C1B26] shadow-2xl">
        <div className="flex shrink-0 items-center justify-between border-b border-white/[0.06] p-6">
          <h2 className="heading-2 text-[#F7F7F7]">
            {mode === "add" ? "Add New Venue" : "Edit Venue"}
          </h2>
          <button
            onClick={onClose}
            className="text-[#F7F7F7]/40 hover:text-[#F7F7F7]"
          >
            <XCircle className="h-5 w-5" />
          </button>
        </div>

        <div className="overflow-y-auto p-6">
          <form onSubmit={handleSubmit} className="flex flex-col gap-8">
            <div className="space-y-4">
              <div>
                <label className="label text-[#F7F7F7]/40">Venue Name</label>
                <input
                  type="text"
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  placeholder="e.g. Padel Bali Arena"
                  className="body mt-1.5 w-full rounded-xl border border-white/[0.06] bg-white/[0.02] px-4 py-3 text-[#F7F7F7] placeholder:text-[#F7F7F7]/25 focus:border-[#E6FA50]/30 focus:outline-none"
                  required
                />
              </div>
              <div>
                <label className="label text-[#F7F7F7]/40">Location</label>
                <input
                  type="text"
                  value={location}
                  onChange={(e) => setLocation(e.target.value)}
                  placeholder="Full address"
                  className="body mt-1.5 w-full rounded-xl border border-white/[0.06] bg-white/[0.02] px-4 py-3 text-[#F7F7F7] placeholder:text-[#F7F7F7]/25 focus:border-[#E6FA50]/30 focus:outline-none"
                  required
                />
              </div>
              <div>
                <label className="label text-[#F7F7F7]/40">City</label>
                <input
                  type="text"
                  value={city}
                  onChange={(e) => setCity(e.target.value)}
                  placeholder="e.g. Bali"
                  className="body mt-1.5 w-full rounded-xl border border-white/[0.06] bg-white/[0.02] px-4 py-3 text-[#F7F7F7] placeholder:text-[#F7F7F7]/25 focus:border-[#E6FA50]/30 focus:outline-none"
                  required
                />
              </div>
              <div>
                <label className="label text-[#F7F7F7]/40">Description</label>
                <textarea
                  rows={3}
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  placeholder="Describe your venue..."
                  className="body mt-1.5 w-full resize-none rounded-xl border border-white/[0.06] bg-white/[0.02] px-4 py-3 text-[#F7F7F7] placeholder:text-[#F7F7F7]/25 focus:border-[#E6FA50]/30 focus:outline-none"
                  required
                />
              </div>
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="label text-[#F7F7F7]/40">Open Time</label>
                  <input
                    type="time"
                    value={openTime}
                    onChange={(e) => setOpenTime(e.target.value)}
                    className="body mt-1.5 w-full rounded-xl border border-white/[0.06] bg-white/[0.02] px-4 py-3 text-[#F7F7F7] focus:border-[#E6FA50]/30 focus:outline-none [color-scheme:dark]"
                    required
                  />
                </div>
                <div>
                  <label className="label text-[#F7F7F7]/40">Close Time</label>
                  <input
                    type="time"
                    value={closeTime}
                    onChange={(e) => setCloseTime(e.target.value)}
                    className="body mt-1.5 w-full rounded-xl border border-white/[0.06] bg-white/[0.02] px-4 py-3 text-[#F7F7F7] focus:border-[#E6FA50]/30 focus:outline-none [color-scheme:dark]"
                    required
                  />
                </div>
              </div>
            </div>

            <hr className="border-white/[0.06]" />

            {/* Cover Image */}
            <div>
              <div className="flex items-center justify-between mb-1.5">
                <label className="label text-[#F7F7F7]/40">
                  Cover Image URL (Optional)
                </label>
                <div className="flex items-center gap-2">
                  {isUploadingCover && (
                    <Loader2 className="h-4 w-4 animate-spin text-[#E6FA50]" />
                  )}
                  <label className="label cursor-pointer text-[#E6FA50] hover:underline">
                    Upload file
                    <input
                      type="file"
                      accept="image/*"
                      onChange={handleUploadCover}
                      disabled={isUploadingCover}
                      className="hidden"
                    />
                  </label>
                </div>
              </div>
              <input
                type="url"
                value={imageUrl}
                onChange={(e) => {
                  setImageUrl(e.target.value);
                  setCoverError(false);
                }}
                placeholder="https://..."
                className="body w-full rounded-xl border border-white/[0.06] bg-white/[0.02] px-4 py-3 text-[#F7F7F7] placeholder:text-[#F7F7F7]/25 focus:border-[#E6FA50]/30 focus:outline-none"
              />
              {imageUrl && !coverError && (
                <img
                  src={imageUrl}
                  alt="Cover preview"
                  className="mt-2 h-24 w-full rounded-xl object-cover"
                  onError={() => setCoverError(true)}
                />
              )}
            </div>

            {/* Photo Gallery */}
            <div>
              <div className="flex items-center justify-between mb-1.5">
                <label className="label text-[#F7F7F7]/40">
                  Photo Gallery (Optional)
                </label>
                <div className="flex items-center gap-2">
                  {isUploadingPhoto && (
                    <Loader2 className="h-4 w-4 animate-spin text-[#E6FA50]" />
                  )}
                  <label className="label cursor-pointer text-[#E6FA50] hover:underline">
                    Upload file
                    <input
                      type="file"
                      accept="image/*"
                      onChange={handleUploadPhoto}
                      disabled={isUploadingPhoto}
                      className="hidden"
                    />
                  </label>
                </div>
              </div>
              <div className="flex gap-2">
                <input
                  type="url"
                  value={photoDraft}
                  onChange={(e) => setPhotoDraft(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === "Enter") {
                      e.preventDefault();
                      handleAddPhoto();
                    }
                  }}
                  placeholder="Add photo URL..."
                  className="body w-full rounded-xl border border-white/[0.06] bg-white/[0.02] px-4 py-3 text-[#F7F7F7] placeholder:text-[#F7F7F7]/25 focus:border-[#E6FA50]/30 focus:outline-none"
                />
                <button
                  type="button"
                  onClick={handleAddPhoto}
                  className="label btn-lime shrink-0 rounded-xl px-4"
                >
                  Add
                </button>
              </div>
              {photos.length === 0 ? (
                <p className="body-sm mt-2 text-[#F7F7F7]/40">
                  No photos added yet.
                </p>
              ) : (
                <div className="mt-3 space-y-2">
                  {photos.map((p, idx) => (
                    <div
                      key={idx}
                      className="flex items-center justify-between rounded-xl border border-white/[0.06] bg-white/[0.02] p-2"
                    >
                      <div className="flex items-center gap-3 overflow-hidden">
                        <img
                          src={p}
                          alt="Thumbnail"
                          className="h-10 w-10 shrink-0 rounded object-cover"
                          onError={(e) => {
                            e.currentTarget.style.display = "none";
                          }}
                        />
                        <span className="body-sm truncate text-[#F7F7F7]/60">
                          {p}
                        </span>
                      </div>
                      <button
                        type="button"
                        onClick={() =>
                          setPhotos(photos.filter((_, i) => i !== idx))
                        }
                        className="ml-2 shrink-0 p-1 text-[#F7F7F7]/40 hover:text-red-400"
                      >
                        <X className="h-4 w-4" />
                      </button>
                    </div>
                  ))}
                </div>
              )}
            </div>

            {/* Facilities */}
            <div>
              <label className="label text-[#F7F7F7]/40">
                Facilities (Optional)
              </label>
              <div className="mt-1.5 flex gap-2">
                <input
                  type="text"
                  value={facilityDraft}
                  onChange={(e) => setFacilityDraft(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === "Enter") {
                      e.preventDefault();
                      handleAddFacility();
                    }
                  }}
                  placeholder="Add facility..."
                  className="body w-full rounded-xl border border-white/[0.06] bg-white/[0.02] px-4 py-3 text-[#F7F7F7] placeholder:text-[#F7F7F7]/25 focus:border-[#E6FA50]/30 focus:outline-none"
                />
                <button
                  type="button"
                  onClick={handleAddFacility}
                  className="label btn-lime shrink-0 rounded-xl px-4"
                >
                  Add
                </button>
              </div>
              <div className="mt-3 flex flex-wrap gap-2">
                {facilities.map((f, idx) => (
                  <span
                    key={idx}
                    className="caption flex items-center gap-1.5 rounded-full bg-white/[0.03] pl-3 pr-1.5 py-1 text-[#F7F7F7]/60"
                  >
                    {f}
                    <button
                      type="button"
                      onClick={() =>
                        setFacilities(facilities.filter((_, i) => i !== idx))
                      }
                      className="rounded-full p-0.5 hover:bg-white/[0.1] hover:text-[#F7F7F7]"
                    >
                      <X className="h-3 w-3" />
                    </button>
                  </span>
                ))}
              </div>
              <div className="mt-3 border-t border-white/[0.04] pt-3">
                <p className="section-label mb-2 text-[#F7F7F7]/40">
                  Quick Add:
                </p>
                <div className="flex flex-wrap gap-2">
                  {[
                    "Parking",
                    "Showers",
                    "Locker Room",
                    "Cafe",
                    "Pro Shop",
                    "WiFi",
                    "Equipment Rental",
                    "Seating Area",
                  ].map((preset) => (
                    <button
                      key={preset}
                      type="button"
                      onClick={() => {
                        if (!facilities.includes(preset))
                          setFacilities([...facilities, preset]);
                      }}
                      className="caption rounded-full border border-white/[0.06] px-2 py-1 text-[#F7F7F7]/40 transition-colors hover:border-[#E6FA50]/50 hover:text-[#F7F7F7]"
                    >
                      + {preset}
                    </button>
                  ))}
                </div>
              </div>
            </div>

            <div className="flex gap-3 pt-2">
              <button
                type="button"
                onClick={onClose}
                disabled={isPending}
                className="label flex-1 rounded-full border border-white/[0.08] py-3 text-[#F7F7F7]/60 transition-colors hover:border-white/[0.15] hover:text-[#F7F7F7]/80 disabled:opacity-50"
              >
                Cancel
              </button>
              <button
                type="submit"
                disabled={isPending}
                className="label btn-lime flex flex-1 items-center justify-center gap-2 rounded-full py-3 disabled:opacity-50"
              >
                {isPending && <Loader2 className="h-4 w-4 animate-spin" />}
                {mode === "add" ? "Submit for Approval" : "Save Changes"}
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  );
}

function VenueCard({
  venue,
  onEdit,
  showToast,
}: {
  venue: Venue;
  onEdit: (v: Venue) => void;
  showToast: (msg: string) => void;
}) {
  const status = venue.status ?? "PENDING";
  const config = STATUS_CONFIG[status] ?? STATUS_CONFIG.PENDING;
  const StatusIcon = config.icon;

  return (
    <div className="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6 transition-all hover:border-white/[0.1]">
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div className="flex-1 min-w-0">
          <div className="flex items-center gap-3">
            <h3 className="heading-3 truncate text-[#F7F7F7]">{venue.name}</h3>
            {venue.isVerified && (
              <span className="caption shrink-0 rounded-full bg-[#E6FA50] px-2 py-0.5 uppercase text-[#06121A]">
                Verified
              </span>
            )}
          </div>
          <p className="body-sm mt-1 flex items-center gap-1.5 text-[#F7F7F7]/40">
            <MapPin className="h-3.5 w-3.5" />
            {venue.location} · {venue.city}
          </p>
          <div className="mt-3 flex flex-wrap items-center gap-4">
            <span className="body-sm flex items-center gap-1.5 text-[#F7F7F7]/25">
              <Star className="h-3 w-3 fill-[#E6FA50] text-[#E6FA50]" />
              {venue.rating} ({venue.reviewCount})
            </span>
            <span className="body-sm text-[#F7F7F7]/25">
              {venue.courtCount ?? 0} courts
            </span>
            <span className="body-sm text-[#F7F7F7]/25">
              {venue.operatingHours.open} – {venue.operatingHours.close}
            </span>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <div
            className={`flex items-center gap-1.5 rounded-full px-3 py-1.5 ${config.bg}`}
          >
            <StatusIcon className={`h-3.5 w-3.5 ${config.color}`} />
            <span className={`caption ${config.color}`}>{config.label}</span>
          </div>
          <Link
            href={`/venues/${venue.id}`}
            className="flex h-9 w-9 items-center justify-center rounded-lg border border-white/[0.06] text-[#F7F7F7]/25 transition-colors hover:border-white/[0.12] hover:text-[#F7F7F7]/60"
            title="View venue"
          >
            <Eye className="h-3.5 w-3.5" />
          </Link>
          <button
            onClick={() => onEdit(venue)}
            className="flex h-9 w-9 items-center justify-center rounded-lg border border-white/[0.06] text-[#F7F7F7]/25 transition-colors hover:border-white/[0.12] hover:text-[#F7F7F7]/60"
            title="Edit venue"
          >
            <Edit3 className="h-3.5 w-3.5" />
          </button>
          <button
            onClick={() =>
              showToast("More options coming soon in backend integration.")
            }
            className="flex h-9 w-9 items-center justify-center rounded-lg border border-white/[0.06] text-[#F7F7F7]/25 transition-colors hover:border-white/[0.12] hover:text-[#F7F7F7]/60"
          >
            <MoreVertical className="h-3.5 w-3.5" />
          </button>
        </div>
      </div>

      {/* Facilities */}
      <div className="mt-4 flex flex-wrap gap-2 border-t border-white/[0.04] pt-4">
        {venue.facilities.map((f) => (
          <span
            key={f}
            className="caption rounded-full bg-white/[0.03] px-3 py-1 text-[#F7F7F7]/25"
          >
            {f}
          </span>
        ))}
      </div>
    </div>
  );
}

// apps/web/src/routes/dashboard/venues/+page.svelte
<script lang="ts">
import {
  Building2,
  CheckCircle2,
  Clock,
  Edit3,
  Eye,
  Loader2,
  MapPin,
  Plus,
  Star,
  Upload,
  X,
  XCircle,
} from "lucide-svelte";
import { onMount } from "svelte";
import { api } from "$lib/api/client";
import { authStore } from "$lib/auth/store.svelte";
import EmptyState from "$lib/components/ui/empty-state.svelte";
import TimeSelect from "$lib/components/ui/time-select.svelte";

const STATUS_CONFIG: Record<
  string,
  { label: string; icon: any; color: string; bg: string }
> = {
  APPROVED: {
    label: "Approved",
    icon: CheckCircle2,
    color: "text-green-400",
    bg: "bg-green-400/10",
  },
  PENDING: {
    label: "Pending Review",
    icon: Clock,
    color: "text-yellow-400",
    bg: "bg-yellow-400/10",
  },
  REJECTED: {
    label: "Rejected",
    icon: XCircle,
    color: "text-red-400",
    bg: "bg-red-400/10",
  },
  SUSPENDED: {
    label: "Suspended",
    icon: XCircle,
    color: "text-orange-400",
    bg: "bg-orange-400/10",
  },
};

const PRESET_FACILITIES = [
  "Parking",
  "Showers",
  "Locker Room",
  "Cafe",
  "Pro Shop",
  "WiFi",
  "Equipment Rental",
  "Seating Area",
];

let venues = $state<any[]>([]);
let isLoading = $state(true);
let toast = $state<string | null>(null);

// Modal state
let isModalOpen = $state(false);
let modalMode = $state<"add" | "edit">("add");
let editingVenue = $state<any | null>(null);
let isSubmitting = $state(false);

// Form state
let formName = $state("");
let formLocation = $state("");
let formCity = $state("");
let formDescription = $state("");
let formOpenTime = $state("06:00");
let formCloseTime = $state("23:00");
let formImageUrl = $state("");
let formPhotos = $state<string[]>([]);
let formFacilities = $state<string[]>([]);
let photoInput = $state("");
let facilityInput = $state("");

// Real File Picker references
let coverFileInputRef = $state<HTMLInputElement | null>(null);
let photoFileInputRef = $state<HTMLInputElement | null>(null);
let isUploadingCover = $state(false);
let isUploadingPhoto = $state(false);

function showToast(msg: string) {
  toast = msg;
  setTimeout(() => (toast = null), 3000);
}

async function loadOwnerVenues() {
  isLoading = true;
  try {
    const token = await authStore.firebaseUser?.getIdToken();
    if (!token) return;

    const res = await api.venues.manage.get({
      headers: { authorization: `Bearer ${token}` },
    });
    if (res.data && Array.isArray(res.data)) {
      venues = res.data;
    }
  } catch (e) {
    console.warn("Error fetching owner venues:", e);
  } finally {
    isLoading = false;
  }
}

function openAddModal() {
  modalMode = "add";
  editingVenue = null;
  formName = "";
  formLocation = "";
  formCity = "";
  formDescription = "";
  formOpenTime = "06:00";
  formCloseTime = "23:00";
  formImageUrl = "";
  formPhotos = [];
  formFacilities = [];
  photoInput = "";
  facilityInput = "";
  isModalOpen = true;
}

function openEditModal(v: any) {
  modalMode = "edit";
  editingVenue = v;
  formName = v.name || "";
  formLocation = v.location || "";
  formCity = v.city || "";
  formDescription = v.description || "";
  formOpenTime = v.operatingHours?.open || v.openTime || "06:00";
  formCloseTime = v.operatingHours?.close || v.closeTime || "23:00";
  formImageUrl = v.imageUrl || "";
  formPhotos = Array.isArray(v.photos) ? [...v.photos] : [];
  formFacilities = Array.isArray(v.facilities) ? [...v.facilities] : [];
  photoInput = "";
  facilityInput = "";
  isModalOpen = true;
}

function triggerCoverFilePicker() {
  if (coverFileInputRef) coverFileInputRef.click();
}

function triggerPhotoFilePicker() {
  if (photoFileInputRef) photoFileInputRef.click();
}

function handleCoverFileSelect(e: Event) {
  const target = e.target as HTMLInputElement;
  const file = target.files?.[0];
  if (!file) return;

  isUploadingCover = true;
  const reader = new FileReader();
  reader.onload = (evt) => {
    if (evt.target?.result) {
      formImageUrl = evt.target.result as string;
      showToast("Cover image loaded from disk.");
    }
    isUploadingCover = false;
    target.value = "";
  };
  reader.onerror = () => {
    showToast("Failed to read image file.");
    isUploadingCover = false;
    target.value = "";
  };
  reader.readAsDataURL(file);
}

function handlePhotoFileSelect(e: Event) {
  const target = e.target as HTMLInputElement;
  const file = target.files?.[0];
  if (!file) return;

  isUploadingPhoto = true;
  const reader = new FileReader();
  reader.onload = (evt) => {
    if (evt.target?.result) {
      const dataUrl = evt.target.result as string;
      if (!formPhotos.includes(dataUrl)) {
        formPhotos = [...formPhotos, dataUrl];
        showToast("Photo added to gallery.");
      }
    }
    isUploadingPhoto = false;
    target.value = "";
  };
  reader.onerror = () => {
    showToast("Failed to read image file.");
    isUploadingPhoto = false;
    target.value = "";
  };
  reader.readAsDataURL(file);
}

function addPhoto() {
  const url = photoInput.trim();
  if (url && !formPhotos.includes(url)) {
    formPhotos = [...formPhotos, url];
    photoInput = "";
  }
}

function removePhoto(idx: number) {
  formPhotos = formPhotos.filter((_, i) => i !== idx);
}

function addFacility(facilityName: string) {
  const f = facilityName.trim();
  if (f && !formFacilities.includes(f)) {
    formFacilities = [...formFacilities, f];
    facilityInput = "";
  }
}

function removeFacility(idx: number) {
  formFacilities = formFacilities.filter((_, i) => i !== idx);
}

async function handleSubmit() {
  if (
    !formName.trim() ||
    !formLocation.trim() ||
    !formCity.trim() ||
    !formDescription.trim() ||
    isSubmitting
  ) {
    showToast("Please fill in all required fields.");
    return;
  }

  isSubmitting = true;
  try {
    const token = await authStore.firebaseUser?.getIdToken();
    if (!token) return;

    const payload = {
      name: formName.trim(),
      location: formLocation.trim(),
      city: formCity.trim(),
      description: formDescription.trim(),
      openTime: formOpenTime,
      closeTime: formCloseTime,
      imageUrl: formImageUrl.trim() || undefined,
      photos: formPhotos,
      facilities: formFacilities,
    };

    if (modalMode === "edit" && editingVenue) {
      await api
        .venues({ id: editingVenue.id })
        .patch(payload, { headers: { authorization: `Bearer ${token}` } });
      showToast("Venue updated.");
    } else {
      await api.venues.post(payload, {
        headers: { authorization: `Bearer ${token}` },
      });
      showToast("Venue submitted for approval.");
    }

    isModalOpen = false;
    await loadOwnerVenues();
  } catch (err: any) {
    showToast(err.message || "Failed to save venue");
  } finally {
    isSubmitting = false;
  }
}

$effect(() => {
  if (authStore.isInitialized && authStore.user) {
    loadOwnerVenues();
  }
});

onMount(() => {
  if (authStore.user) loadOwnerVenues();
});

const inputWrapperClass =
  "relative flex h-11 w-full items-center overflow-hidden rounded-xl border border-white/[0.08] bg-white/[0.02] transition-colors focus-within:border-[#50C8C8]/40";
const inputClass =
  "body h-full w-full bg-transparent px-4 py-2.5 text-[#F7F7F7] placeholder:text-[#F7F7F7]/25 outline-none";
const integratedBtnClass =
  "label flex h-full shrink-0 items-center gap-2 border-l border-white/[0.08] bg-white/[0.04] px-4 text-xs font-medium text-[#F7F7F7]/70 transition-colors hover:bg-white/[0.08] hover:text-[#E6FA50]";
const labelClass = "mb-1.5 block caption text-[#F7F7F7]/40 font-medium";
</script>

<svelte:head>
  <title>Venues Management | Padelhive Owner</title>
</svelte:head>

<!-- Hidden File Inputs -->
<input
  bind:this={coverFileInputRef}
  type="file"
  accept="image/*"
  class="hidden"
  onchange={handleCoverFileSelect}
/>
<input
  bind:this={photoFileInputRef}
  type="file"
  accept="image/*"
  class="hidden"
  onchange={handlePhotoFileSelect}
/>

<div class="py-8">
  <section class="container">
    <!-- Header -->
    <div class="flex flex-col items-start justify-between gap-4 sm:flex-row sm:items-end">
      <div>
        <h1 class="heading-1 text-[#F7F7F7]">Venues</h1>
        <p class="body mt-1 text-[#F7F7F7]/40">
          Manage your padel venues
        </p>
      </div>
      <button
        type="button"
        onclick={openAddModal}
        class="label btn-lime flex h-11 w-full items-center justify-center gap-2 rounded-full px-5 sm:h-10 sm:w-auto"
      >
        <Plus class="h-4 w-4" />
        Add Venue
      </button>
    </div>

    <!-- Venue List -->
    <div class="mt-8 space-y-4">
      {#if isLoading}
        {#each Array.from({ length: 2 }) as _, i}
          <div class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6">
            <div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
              <div class="flex-1 min-w-0">
                <div class="flex items-center gap-3">
                  <div class="h-6 w-48 animate-pulse rounded-md bg-white/[0.04]"></div>
                </div>
                <div class="mt-2 h-4 w-64 animate-pulse rounded-md bg-white/[0.04]"></div>
                <div class="mt-4 flex flex-wrap items-center gap-4">
                  <div class="h-4 w-16 animate-pulse rounded-md bg-white/[0.04]"></div>
                  <div class="h-4 w-20 animate-pulse rounded-md bg-white/[0.04]"></div>
                  <div class="h-4 w-32 animate-pulse rounded-md bg-white/[0.04]"></div>
                </div>
              </div>
              <div class="flex items-center gap-2">
                <div class="h-8 w-24 animate-pulse rounded-full bg-white/[0.04]"></div>
                {#each Array.from({ length: 3 }) as _, j}
                  <div class="h-9 w-9 animate-pulse rounded-lg bg-white/[0.04]"></div>
                {/each}
              </div>
            </div>
            <div class="mt-4 flex flex-wrap gap-2 border-t border-white/[0.04] pt-4">
              {#each Array.from({ length: 4 }) as _, j}
                <div class="h-6 w-16 animate-pulse rounded-full bg-white/[0.04]"></div>
              {/each}
            </div>
          </div>
        {/each}
      {:else if venues.length === 0}
        <EmptyState
          icon={Building2}
          title="No venues yet"
          description="Add your first venue to start managing courts and bookings."
          actionLabel="Add Venue"
          onAction={openAddModal}
        />
      {:else}
        {#each venues as venue (venue.id)}
          {@const status = venue.status ?? "PENDING"}
          {@const config = STATUS_CONFIG[status] ?? STATUS_CONFIG.PENDING}
          {@const StatusIcon = config.icon}

          <div class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6 transition-all hover:border-white/[0.1]">
            <div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
              <div class="flex-1 min-w-0">
                <div class="flex items-center gap-3">
                  <h3 class="heading-3 truncate text-[#F7F7F7]">{venue.name}</h3>
                  {#if venue.isVerified}
                    <span class="caption shrink-0 rounded-full bg-[#E6FA50] px-2 py-0.5 uppercase text-[#06121A]">
                      Verified
                    </span>
                  {/if}
                </div>
                <p class="body-sm mt-1 flex items-center gap-1.5 text-[#F7F7F7]/40">
                  <MapPin class="h-3.5 w-3.5" />
                  {venue.location} · {venue.city}
                </p>
                <div class="mt-3 flex flex-wrap items-center gap-4">
                  <span class="body-sm flex items-center gap-1.5 text-[#F7F7F7]/25">
                    <Star class="h-3 w-3 fill-[#E6FA50] text-[#E6FA50]" />
                    {venue.rating || "5.0"} ({venue.reviewCount || 0})
                  </span>
                  <span class="body-sm text-[#F7F7F7]/25">
                    {venue.courtCount ?? 0} courts
                  </span>
                  <span class="body-sm text-[#F7F7F7]/25">
                    {venue.operatingHours?.open || venue.openTime || "06:00"} – {venue.operatingHours?.close || venue.closeTime || "23:00"}
                  </span>
                </div>
              </div>

              <div class="flex items-center gap-2">
                <div class="flex items-center gap-1.5 rounded-full px-3 py-1.5 {config.bg}">
                  <StatusIcon class="h-3.5 w-3.5 {config.color}" />
                  <span class="caption {config.color}">{config.label}</span>
                </div>
                <a
                  href={`/venues/${venue.id}`}
                  class="flex h-9 w-9 items-center justify-center rounded-lg border border-white/[0.06] text-[#F7F7F7]/25 transition-colors hover:border-white/[0.12] hover:text-[#F7F7F7]/60"
                  title="View venue"
                >
                  <Eye class="h-3.5 w-3.5" />
                </a>
                <button
                  type="button"
                  onclick={() => openEditModal(venue)}
                  class="flex h-9 w-9 items-center justify-center rounded-lg border border-white/[0.06] text-[#F7F7F7]/25 transition-colors hover:border-white/[0.12] hover:text-[#F7F7F7]/60"
                  title="Edit venue"
                >
                  <Edit3 class="h-3.5 w-3.5" />
                </button>
              </div>
            </div>

            {#if venue.facilities && venue.facilities.length > 0}
              <div class="mt-4 flex flex-wrap gap-2 border-t border-white/[0.04] pt-4">
                {#each venue.facilities as f}
                  <span class="caption rounded-full bg-white/[0.03] px-3 py-1 text-[#F7F7F7]/25">
                    {f}
                  </span>
                {/each}
              </div>
            {/if}
          </div>
        {/each}
      {/if}
    </div>

    <!-- Venue Add/Edit Modal -->
    {#if isModalOpen}
      <div class="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4 backdrop-blur-sm">
        <button
          type="button"
          class="absolute inset-0 bg-transparent w-full h-full border-0 cursor-default"
          onclick={() => (isModalOpen = false)}
          aria-label="Close modal backdrop"
        ></button>

        <div class="relative flex w-full max-w-3xl flex-col rounded-2xl border border-white/[0.08] bg-[#0C1B26] p-6 shadow-2xl z-10">
          <!-- Modal Header -->
          <div class="flex items-center justify-between border-b border-white/[0.06] pb-4 mb-5">
            <p class="section-label">
              {modalMode === "add" ? "Add New Venue" : "Edit Venue"}
            </p>
            <button
              type="button"
              onclick={() => (isModalOpen = false)}
              class="text-[#F7F7F7]/40 hover:text-[#F7F7F7]"
            >
              <X class="h-4 w-4" />
            </button>
          </div>

          <!-- 2-Column Form Body -->
          <div class="grid grid-cols-1 gap-6 md:grid-cols-2">
            <!-- Left Column: Core Info -->
            <div class="space-y-4">
              <div>
                <label class={labelClass} for="venue-name">Venue Name *</label>
                <div class={inputWrapperClass}>
                  <input
                    id="venue-name"
                    bind:value={formName}
                    placeholder="e.g. Padel Bali Arena"
                    class={inputClass}
                  />
                </div>
              </div>

              <div class="grid grid-cols-2 gap-3">
                <div>
                  <label class={labelClass} for="venue-city">City *</label>
                  <div class={inputWrapperClass}>
                    <input
                      id="venue-city"
                      bind:value={formCity}
                      placeholder="e.g. Bali"
                      class={inputClass}
                    />
                  </div>
                </div>
                <div>
                  <label class={labelClass} for="venue-location">Address *</label>
                  <div class={inputWrapperClass}>
                    <input
                      id="venue-location"
                      bind:value={formLocation}
                      placeholder="Jl. Sunset Road No. 88"
                      class={inputClass}
                    />
                  </div>
                </div>
              </div>

              <div class="grid grid-cols-2 gap-3">
                <div>
                  <label class={labelClass} for="venue-open">Open Time</label>
                  <TimeSelect
                    bind:value={formOpenTime}
                    ariaLabel="Open time"
                  />
                </div>
                <div>
                  <label class={labelClass} for="venue-close">Close Time</label>
                  <TimeSelect
                    bind:value={formCloseTime}
                    ariaLabel="Close time"
                  />
                </div>
              </div>

              <div>
                <label class={labelClass} for="venue-desc">Description *</label>
                <div class="relative flex w-full items-center overflow-hidden rounded-xl border border-white/[0.08] bg-white/[0.02] focus-within:border-[#50C8C8]/40">
                  <textarea
                    id="venue-desc"
                    rows={3}
                    bind:value={formDescription}
                    placeholder="Describe your venue facilities..."
                    class="body w-full bg-transparent px-4 py-2.5 text-[#F7F7F7] placeholder:text-[#F7F7F7]/25 outline-none resize-none"
                  ></textarea>
                </div>
              </div>
            </div>

            <!-- Right Column: Media & Facilities -->
            <div class="space-y-4">
              <!-- Integrated Cover Image Input with File Picker -->
              <div>
                <label class={labelClass} for="venue-cover">Cover Image URL (Optional)</label>
                <div class={inputWrapperClass}>
                  <input
                    id="venue-cover"
                    type="url"
                    bind:value={formImageUrl}
                    placeholder="https://images.unsplash.com/..."
                    class={inputClass}
                  />
                  <button
                    type="button"
                    onclick={triggerCoverFilePicker}
                    disabled={isUploadingCover}
                    class={integratedBtnClass}
                  >
                    {#if isUploadingCover}
                      <Loader2 class="h-3.5 w-3.5 animate-spin" />
                    {:else}
                      <Upload class="h-3.5 w-3.5" />
                    {/if}
                    Choose file
                  </button>
                </div>
              </div>

              <!-- Integrated Photo Gallery Input with File Picker -->
              <div>
                <label class={labelClass} for="venue-photo-draft">Photo Gallery (Optional)</label>
                <div class={inputWrapperClass}>
                  <input
                    id="venue-photo-draft"
                    type="url"
                    bind:value={photoInput}
                    onkeydown={(e) => e.key === "Enter" && (e.preventDefault(), addPhoto())}
                    placeholder="Photo URL..."
                    class={inputClass}
                  />
                  <button
                    type="button"
                    onclick={triggerPhotoFilePicker}
                    disabled={isUploadingPhoto}
                    class={integratedBtnClass}
                  >
                    {#if isUploadingPhoto}
                      <Loader2 class="h-3.5 w-3.5 animate-spin" />
                    {:else}
                      <Upload class="h-3.5 w-3.5" />
                    {/if}
                    Choose file
                  </button>
                </div>

                {#if formPhotos.length > 0}
                  <div class="mt-2 flex flex-wrap gap-1.5 max-h-20 overflow-y-auto no-scrollbar">
                    {#each formPhotos as p, idx}
                      <span class="caption flex items-center gap-1.5 rounded-lg bg-white/[0.04] px-2.5 py-1 text-[#F7F7F7]/60">
                        <span class="truncate max-w-[120px]">{p}</span>
                        <button type="button" onclick={() => removePhoto(idx)} class="text-white/40 hover:text-red-400">
                          <X class="h-3 w-3" />
                        </button>
                      </span>
                    {/each}
                  </div>
                {/if}
              </div>

              <!-- Integrated Facilities Input -->
              <div>
                <label class={labelClass} for="venue-facility-draft">Facilities (Optional)</label>
                <div class={inputWrapperClass}>
                  <input
                    id="venue-facility-draft"
                    type="text"
                    bind:value={facilityInput}
                    onkeydown={(e) => e.key === "Enter" && (e.preventDefault(), addFacility(facilityInput))}
                    placeholder="Custom facility..."
                    class={inputClass}
                  />
                  <button
                    type="button"
                    onclick={() => addFacility(facilityInput)}
                    class={integratedBtnClass}
                  >
                    <Plus class="h-3.5 w-3.5" />
                    Add
                  </button>
                </div>

                {#if formFacilities.length > 0}
                  <div class="mt-2 flex flex-wrap gap-1.5">
                    {#each formFacilities as f, idx}
                      <span class="caption flex items-center gap-1 rounded-full bg-[#E6FA50]/10 px-2.5 py-0.5 text-[#E6FA50]">
                        {f}
                        <button type="button" onclick={() => removeFacility(idx)} class="hover:text-white">
                          <X class="h-3 w-3" />
                        </button>
                      </span>
                    {/each}
                  </div>
                {/if}

                <div class="mt-2">
                  <p class="caption text-[#F7F7F7]/30 mb-1">Quick Add:</p>
                  <div class="flex flex-wrap gap-1">
                    {#each PRESET_FACILITIES as preset}
                      <button
                        type="button"
                        onclick={() => addFacility(preset)}
                        disabled={formFacilities.includes(preset)}
                        class="caption rounded-md border border-white/[0.06] px-2 py-0.5 text-[11px] text-[#F7F7F7]/40 hover:border-[#E6FA50]/40 hover:text-[#F7F7F7] disabled:opacity-20"
                      >
                        + {preset}
                      </button>
                    {/each}
                  </div>
                </div>
              </div>
            </div>
          </div>

          <!-- Modal Footer -->
          <div class="mt-6 flex justify-end gap-3 border-t border-white/[0.06] pt-4">
            <button
              type="button"
              onclick={() => (isModalOpen = false)}
              disabled={isSubmitting}
              class="label rounded-full border border-white/[0.08] px-5 py-2.5 text-[#F7F7F7]/60 transition-colors hover:border-white/[0.15] disabled:opacity-40"
            >
              Cancel
            </button>
            <button
              type="button"
              onclick={handleSubmit}
              disabled={isSubmitting || !formName.trim() || !formLocation.trim() || !formCity.trim()}
              class="btn-lime label flex items-center justify-center gap-2 rounded-full px-6 py-2.5 disabled:opacity-40"
            >
              {#if isSubmitting}
                <Loader2 class="h-3.5 w-3.5 animate-spin" />
              {:else if modalMode === "edit"}
                Save Changes
              {:else}
                Submit for Approval
              {/if}
            </button>
          </div>
        </div>
      </div>
    {/if}

    <!-- Toast -->
    {#if toast}
      <div class="fixed bottom-6 left-1/2 z-50 -translate-x-1/2 rounded-xl border border-white/[0.08] bg-[#0C1B26] px-5 py-3 shadow-2xl shadow-black/40">
        <p class="body text-[#F7F7F7]/60">{toast}</p>
      </div>
    {/if}
  </section>
</div>
