// apps/web/src/routes/admin/+page.svelte
<script lang="ts">
import {
  Building2,
  CalendarCheck,
  CheckCircle2,
  Clock,
  DollarSign,
  RotateCcw,
  TrendingUp,
} from "lucide-svelte";
import { onMount } from "svelte";
import { api } from "$lib/api/client";
import { authStore } from "$lib/auth/store.svelte";

let data = $state<any | null>(null);
let isLoading = $state(true);

async function loadAdminOverview() {
  isLoading = true;
  try {
    const token = await authStore.firebaseUser?.getIdToken();
    if (!token) return;

    const res = await api.admin.overview.get({
      headers: { authorization: `Bearer ${token}` },
    });
    if (res.data) {
      data = res.data;
    }
  } catch (e) {
    console.warn("Admin overview fetch error:", e);
  } finally {
    isLoading = false;
  }
}

onMount(() => {
  loadAdminOverview();
});

function formatCurrency(amount: number): string {
  if (!amount) return "Rp 0";
  if (amount >= 1_000_000_000)
    return `Rp ${(amount / 1_000_000_000).toFixed(1)}B`;
  if (amount >= 1_000_000) return `Rp ${(amount / 1_000_000).toFixed(1)}M`;
  if (amount >= 1_000) return `Rp ${(amount / 1_000).toFixed(0)}K`;
  return `Rp ${amount}`;
}
</script>

<svelte:head>
  <title>Operations Overview | PadelHive Admin</title>
</svelte:head>

<div class="px-6 pb-6 pt-element lg:px-8 lg:pb-8 pt-8">
  <div class="mb-8">
    <p class="caption text-[#F7F7F7]/25">Marketplace Admin</p>
    <h1 class="heading-1 mt-2 text-2xl text-[#F7F7F7] md:text-3xl">
      Operations <span class="text-[#E6FA50]">Overview</span>
    </h1>
  </div>

  {#if isLoading}
    <!-- Primary KPIs skeleton -->
    <div class="grid grid-cols-2 gap-4 lg:grid-cols-4 mb-6">
      {#each Array.from({ length: 4 }) as _, i}
        <div
          class="h-[120px] animate-pulse rounded-2xl border border-white/[0.06] bg-[#0C1B26]"
        ></div>
      {/each}
    </div>
  {:else if data}
    <!-- Primary KPIs -->
    <div class="grid grid-cols-2 gap-4 lg:grid-cols-4 mb-6">
      <div
        class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-5"
      >
        <div class="flex items-center justify-between">
          <TrendingUp class="h-4 w-4 text-[#50C8C8]" />
        </div>
        <p class="metric mt-3 text-[#F7F7F7]">{formatCurrency(data.gmv)}</p>
        <p class="caption mt-1 text-[#F7F7F7]/25">GMV This Month</p>
      </div>

      <div
        class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-5"
      >
        <div class="flex items-center justify-between">
          <DollarSign class="h-4 w-4 text-[#50C8C8]" />
        </div>
        <p class="metric mt-3 text-[#F7F7F7]">
          {formatCurrency(data.commissionRevenue)}
        </p>
        <p class="caption mt-1 text-[#F7F7F7]/25">Commission Revenue</p>
      </div>

      <div
        class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-5"
      >
        <div class="flex items-center justify-between">
          <CalendarCheck class="h-4 w-4 text-[#50C8C8]" />
        </div>
        <p class="metric mt-3 text-[#F7F7F7]">
          {data.totalBookings.toLocaleString()}
        </p>
        <p class="caption mt-1 text-[#F7F7F7]/25">Total Bookings</p>
      </div>

      <div
        class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-5"
      >
        <div class="flex items-center justify-between">
          <Building2 class="h-4 w-4 text-[#50C8C8]" />
        </div>
        <p class="metric mt-3 text-[#F7F7F7]">{data.activeVenues}</p>
        <p class="caption mt-1 text-[#F7F7F7]/25">Active Venues</p>
      </div>
    </div>

    <!-- Secondary KPIs -->
    <div class="grid grid-cols-2 gap-4 lg:grid-cols-3 mb-8">
      <div
        class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-5"
      >
        <div class="flex items-center justify-between">
          <Clock class="h-4 w-4 text-amber-400" />
        </div>
        <p class="metric mt-3 text-[#F7F7F7]">{data.pendingApprovals}</p>
        <p class="caption mt-1 text-[#F7F7F7]/25">Pending Approvals</p>
      </div>

      <div
        class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-5"
      >
        <div class="flex items-center justify-between">
          <RotateCcw class="h-4 w-4 text-amber-400" />
        </div>
        <p class="metric mt-3 text-[#F7F7F7]">{data.refundRequests}</p>
        <p class="caption mt-1 text-[#F7F7F7]/25">Refund Requests</p>
      </div>

      <div
        class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-5"
      >
        <div class="flex items-center justify-between">
          <CheckCircle2 class="h-4 w-4 text-[#E6FA50]" />
        </div>
        <p class="metric mt-3 text-[#F7F7F7]">{data.paymentSuccessRate}%</p>
        <p class="caption mt-1 text-[#F7F7F7]/25">Payment Success</p>
      </div>
    </div>

    <!-- Quick Stats -->
    <div class="grid grid-cols-1 gap-5 md:grid-cols-2">
      <div
        class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6 text-center"
      >
        <p class="metric text-[#E6FA50]">
          {formatCurrency(data.avgBookingValue)}
        </p>
        <p class="heading-3 mt-2 text-[#F7F7F7]">Avg. Booking Value</p>
        <p class="caption mt-1 text-[#F7F7F7]/25">
          Per transaction average, this month
        </p>
      </div>

      <div
        class="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6 text-center"
      >
        <p class="metric text-[#E6FA50]">
          {data.avgCommissionRate.toFixed(1)}%
        </p>
        <p class="heading-3 mt-2 text-[#F7F7F7]">Avg. Commission</p>
        <p class="caption mt-1 text-[#F7F7F7]/25">Weighted platform fee</p>
      </div>
    </div>
  {/if}
</div>

// apps/web/src/app/admin/page.tsx
"use client";

import { useQuery } from "@tanstack/react-query";
import {
  Building2,
  CalendarCheck,
  CheckCircle2,
  Clock,
  DollarSign,
  RotateCcw,
  TrendingUp,
} from "lucide-react";
import { ErrorBanner } from "@/components/ui/error-state";
import { getAdminOverview } from "@/lib/api";
import { queryKeys } from "@/lib/queries";

export default function AdminOverviewPage() {
  const { data, isLoading, isError, error, refetch, isFetching } = useQuery({
    queryKey: queryKeys.admin.overview(),
    queryFn: getAdminOverview,
  });

  if (isLoading) {
    return (
      <div className="px-6 pb-6 pt-element lg:px-8 lg:pb-8">
        <div className="mb-8">
          <p className="caption text-[#F7F7F7]/25">Marketplace Admin</p>
          <h1 className="heading-1 mt-2 text-[#F7F7F7]">
            Operations <span className="text-[#E6FA50]">Overview</span>
          </h1>
        </div>

        {/* Primary KPIs */}
        <div className="grid grid-cols-2 gap-4 lg:grid-cols-4 mb-6">
          {[...Array(4)].map((_, i) => (
            <div
              key={i}
              className="h-[120px] animate-pulse rounded-2xl border border-white/[0.06] bg-[#0C1B26]"
            />
          ))}
        </div>

        {/* Secondary KPIs */}
        <div className="grid grid-cols-2 gap-4 lg:grid-cols-3 mb-8">
          {[...Array(3)].map((_, i) => (
            <div
              key={i}
              className="h-[120px] animate-pulse rounded-2xl border border-white/[0.06] bg-[#0C1B26]"
            />
          ))}
        </div>

        {/* Quick Stats */}
        <div className="grid grid-cols-1 gap-5 md:grid-cols-2">
          {[...Array(2)].map((_, i) => (
            <div
              key={i}
              className="h-[140px] animate-pulse rounded-2xl border border-white/[0.06] bg-[#0C1B26]"
            />
          ))}
        </div>
      </div>
    );
  }

  if (isError || !data) {
    return (
      <div className="px-6 pb-6 pt-element lg:px-8 lg:pb-8">
        <div className="mb-8">
          <p className="caption text-[#F7F7F7]/25">Marketplace Admin</p>
          <h1 className="heading-1 mt-2 text-2xl text-[#F7F7F7] md:text-3xl">
            Operations <span className="text-[#E6FA50]">Overview</span>
          </h1>
        </div>
        <div className="mb-6">
          <ErrorBanner
            title="Couldn't load admin metrics"
            error={error}
            onRetry={() => refetch()}
            isRetrying={isFetching}
          />
        </div>
      </div>
    );
  }

  return (
    <div className="px-6 pb-6 pt-element lg:px-8 lg:pb-8">
      <div className="mb-8">
        <p className="caption text-[#F7F7F7]/25">Marketplace Admin</p>
        <h1 className="heading-1 mt-2 text-2xl text-[#F7F7F7] md:text-3xl">
          Operations <span className="text-[#E6FA50]">Overview</span>
        </h1>
      </div>

      {/* Primary KPIs */}
      <div className="grid grid-cols-2 gap-4 lg:grid-cols-4 mb-6">
        <KPI
          icon={TrendingUp}
          label="GMV This Month"
          value={formatCurrency(data.gmv)}
        />
        <KPI
          icon={DollarSign}
          label="Commission Revenue"
          value={formatCurrency(data.commissionRevenue)}
        />
        <KPI
          icon={CalendarCheck}
          label="Total Bookings"
          value={data.totalBookings.toLocaleString()}
        />
        <KPI
          icon={Building2}
          label="Active Venues"
          value={data.activeVenues.toString()}
        />
      </div>

      {/* Secondary KPIs */}
      <div className="grid grid-cols-2 gap-4 lg:grid-cols-3 mb-8">
        <KPI
          icon={Clock}
          label="Pending Approvals"
          value={data.pendingApprovals.toString()}
          variant="warning"
        />
        <KPI
          icon={RotateCcw}
          label="Refund Requests"
          value={data.refundRequests.toString()}
          variant="warning"
        />
        <KPI
          icon={CheckCircle2}
          label="Payment Success"
          value={`${data.paymentSuccessRate}%`}
          variant="success"
        />
      </div>

      {/* Quick Stats */}
      <div className="grid grid-cols-1 gap-5 md:grid-cols-2">
        <QuickStat
          label="Avg. Booking Value"
          value={formatCurrency(data.avgBookingValue)}
          description="Per transaction average, this month"
        />
        <QuickStat
          label="Avg. Commission"
          value={`${data.avgCommissionRate.toFixed(1)}%`}
          description="Weighted platform fee"
        />
      </div>
    </div>
  );
}

function formatCurrency(amount: number): string {
  if (amount >= 1_000_000_000)
    return `Rp ${(amount / 1_000_000_000).toFixed(1)}B`;
  if (amount >= 1_000_000) return `Rp ${(amount / 1_000_000).toFixed(1)}M`;
  if (amount >= 1_000) return `Rp ${(amount / 1_000).toFixed(0)}K`;
  return `Rp ${amount}`;
}

function KPI({
  icon: Icon,
  label,
  value,
  trend,
  trendUp,
  variant,
}: {
  icon: React.ComponentType<{ className?: string }>;
  label: string;
  value: string;
  trend?: string;
  trendUp?: boolean;
  variant?: "warning" | "danger" | "success";
}) {
  const iconColor =
    variant === "danger"
      ? "text-red-400"
      : variant === "warning"
        ? "text-amber-400"
        : variant === "success"
          ? "text-[#E6FA50]"
          : "text-[#50C8C8]";

  return (
    <div className="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-5">
      <div className="flex items-center justify-between">
        <Icon className={`h-4 w-4 ${iconColor}`} />
      </div>
      <p className="metric mt-3 text-[#F7F7F7]">{value}</p>
      <p className="caption mt-1 text-[#F7F7F7]/25">{label}</p>
    </div>
  );
}

function QuickStat({
  label,
  value,
  description,
}: {
  label: string;
  value: string;
  description: string;
}) {
  return (
    <div className="rounded-2xl border border-white/[0.06] bg-[#0C1B26] p-6 text-center">
      <p className="metric text-[#E6FA50]">{value}</p>
      <p className="heading-3 mt-2 text-[#F7F7F7]">{label}</p>
      <p className="caption mt-1 text-[#F7F7F7]/25">{description}</p>
    </div>
  );
}
