// apps/web/src/app/(app)/booking/[id]/success/page.tsx
"use client";

import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { CalendarDays, CheckCircle2, Clock, CreditCard, MapPin, Loader2, XCircle } from "lucide-react";
import { getBookingById, getPayment } from "@/lib/api";
import { useQuery } from "@tanstack/react-query";
import { queryKeys } from "@/lib/queries";
import { formatBookingDate, formatBookingTimeRange } from "@/lib/format";

export default function BookingSuccessPage({ params }: { params: { id: string } }) {
  const searchParams = useSearchParams();
  const paymentId = searchParams.get("paymentId");

  const { data: booking, isLoading: isBookingLoading } = useQuery({
    queryKey: queryKeys.bookings.detail(params.id),
    queryFn: () => getBookingById(params.id),
  });

  const { data: payment } = useQuery({
    queryKey: queryKeys.payments.detail(paymentId ?? ""),
    queryFn: () => getPayment(paymentId!),
    enabled: !!paymentId,
    refetchInterval: (query) => {
      const status = query.state.data?.status;
      return (status === "PAID" || status === "FAILED") ? false : 3000;
    }
  });

  const venue = booking?.venue.name ?? "—";
  const court = booking?.court.name ?? "—";
  const date = booking?.bookingDate;
  const start = booking?.startsAt;
  const end = booking?.endsAt;
  const amount = payment?.amount ?? booking?.payment?.amount ?? booking?.courtAmount ?? 0;

  const resolvedPaymentStatus = payment?.status ?? booking?.payment?.status;
  
  let isPaid = false;
  let isFailed = false;
  let displayStatus = "PENDING";

  if (resolvedPaymentStatus) {
    isPaid = resolvedPaymentStatus === "PAID";
    isFailed = resolvedPaymentStatus === "FAILED";
    displayStatus = resolvedPaymentStatus;
  } else if (booking) {
    if (booking.status === "CONFIRMED") {
      isPaid = true;
      displayStatus = "PAID";
    } else if (booking.status === "CANCELLED" || booking.status === "EXPIRED") {
      isFailed = true;
      displayStatus = "FAILED";
    }
  }

  if (isBookingLoading) {
    return (
      <div className="min-h-screen pt-20 flex items-center justify-center">
        <Loader2 className="h-8 w-8 animate-spin text-[#E6FA50]" />
      </div>
    );
  }

  return (
    <div className="min-h-screen pt-20">
      <div className="container max-w-2xl py-12">
        <div className="rounded-3xl border border-white/[0.06] bg-[#0C1B26] p-6 text-center md:p-8">
          
          {isPaid ? (
            <>
              <div className="mx-auto flex h-20 w-20 items-center justify-center rounded-full bg-[#E6FA50]/10">
                <CheckCircle2 className="h-10 w-10 text-[#E6FA50]" />
              </div>
              <p className="mt-6 text-[11px] font-semibold uppercase tracking-[0.18em] text-[#E6FA50]">
                Booking Confirmed
              </p>
              <h1 className="heading-1 mt-3 text-2xl text-[#F7F7F7] md:text-4xl">
                Court secured for your match
              </h1>
              <p className="mx-auto mt-3 max-w-md text-sm leading-6 text-[#F7F7F7]/40">
                Your payment was successful and the court is confirmed.
              </p>
            </>
          ) : isFailed ? (
            <>
              <div className="mx-auto flex h-20 w-20 items-center justify-center rounded-full bg-red-500/10">
                <XCircle className="h-10 w-10 text-red-500" />
              </div>
              <p className="mt-6 text-[11px] font-semibold uppercase tracking-[0.18em] text-red-500">
                Payment Failed
              </p>
              <h1 className="heading-1 mt-3 text-2xl text-[#F7F7F7] md:text-4xl">
                Payment could not be processed
              </h1>
              <p className="mx-auto mt-3 max-w-md text-sm leading-6 text-[#F7F7F7]/40">
                We could not confirm your payment. Please try again.
              </p>
            </>
          ) : (
            <>
              <div className="mx-auto flex h-20 w-20 items-center justify-center rounded-full bg-yellow-500/10">
                <Loader2 className="h-10 w-10 animate-spin text-yellow-500" />
              </div>
              <p className="mt-6 text-[11px] font-semibold uppercase tracking-[0.18em] text-yellow-500">
                Payment Pending
              </p>
              <h1 className="heading-1 mt-3 text-2xl text-[#F7F7F7] md:text-4xl">
                Waiting for confirmation
              </h1>
              <p className="mx-auto mt-3 max-w-md text-sm leading-6 text-[#F7F7F7]/40">
                We are waiting for the payment provider to confirm your payment. This screen will update automatically.
              </p>
            </>
          )}

          <div className="mt-8 rounded-2xl border border-white/[0.06] bg-[#06121A] p-5 text-left">
            <div className="flex items-start justify-between gap-4 border-b border-white/[0.06] pb-4">
              <div>
                <p className="text-xs uppercase tracking-[0.12em] text-[#F7F7F7]/40">Booking ID</p>
                <p className="mt-1 text-sm font-medium text-[#F7F7F7]/80">{params.id}</p>
              </div>
              <span className={`rounded-full px-3 py-1 text-[11px] font-semibold uppercase tracking-[0.08em] ${isPaid ? "bg-[#E6FA50]/10 text-[#E6FA50]" : isFailed ? "bg-red-500/10 text-red-500" : "bg-yellow-500/10 text-yellow-500"}`}>
                {displayStatus}
              </span>
            </div>

            <div className="mt-5 grid gap-4 sm:grid-cols-2">
              <div className="rounded-xl bg-white/[0.03] p-4">
                <div className="flex items-center gap-2 text-xs uppercase tracking-[0.12em] text-[#F7F7F7]/40">
                  <MapPin className="h-3.5 w-3.5" />
                  Venue
                </div>
                <p className="mt-2 text-sm font-medium text-[#F7F7F7]/80">{venue}</p>
                <p className="mt-1 text-xs text-[#F7F7F7]/40">{court}</p>
              </div>

              <div className="rounded-xl bg-white/[0.03] p-4">
                <div className="flex items-center gap-2 text-xs uppercase tracking-[0.12em] text-[#F7F7F7]/40">
                  <CalendarDays className="h-3.5 w-3.5" />
                  Date
                </div>
                <p className="mt-2 text-sm font-medium text-[#F7F7F7]/80">{formatBookingDate(date)}</p>
              </div>

              <div className="rounded-xl bg-white/[0.03] p-4">
                <div className="flex items-center gap-2 text-xs uppercase tracking-[0.12em] text-[#F7F7F7]/40">
                  <Clock className="h-3.5 w-3.5" />
                  Time
                </div>
                <p className="mt-2 text-sm font-medium text-[#F7F7F7]/80">
                  {formatBookingTimeRange(start, end)}
                </p>
              </div>

              <div className="rounded-xl bg-white/[0.03] p-4">
                <div className="flex items-center gap-2 text-xs uppercase tracking-[0.12em] text-[#F7F7F7]/40">
                  <CreditCard className="h-3.5 w-3.5" />
                  Payment
                </div>
                <p className="mt-2 text-sm font-medium text-[#F7F7F7]/80">
                  {amount > 0 ? `Rp ${amount.toLocaleString("id-ID")}` : "—"}
                </p>
              </div>
            </div>
          </div>

          <div className="mt-8 flex flex-col gap-3 sm:flex-row sm:justify-center">
            {isFailed ? (
              <Link
                href={`/booking/${params.id}/payment`}
                className="btn-lime flex h-12 items-center justify-center rounded-full px-6 text-[11px] font-semibold uppercase tracking-[0.08em]"
              >
                Try Payment Again
              </Link>
            ) : (
              <Link
                href="/profile/bookings"
                className="btn-lime flex h-12 items-center justify-center rounded-full px-6 text-[11px] font-semibold uppercase tracking-[0.08em]"
              >
                View My Bookings
              </Link>
            )}
            <Link
              href="/venues"
              className="flex h-12 items-center justify-center rounded-full border border-white/[0.08] px-6 text-[11px] font-medium uppercase tracking-[0.08em] text-[#F7F7F7]/60 transition-colors hover:border-white/[0.15] hover:text-[#F7F7F7]/80"
            >
              Book Another Court
            </Link>
          </div>
        </div>
      </div>
    </div>
  );
}

// apps/web/src/routes/booking/[id]/success/+page.svelte
<script lang="ts">
import {
  CalendarDays,
  CheckCircle2,
  Clock,
  CreditCard,
  Loader2,
  MapPin,
  XCircle,
} from "lucide-svelte";
import { onMount } from "svelte";
import { page } from "$app/state";
import { api } from "$lib/api/client";
import { authStore } from "$lib/auth/store.svelte";
import { formatBookingDate, formatBookingTimeRange } from "$lib/format";

const bookingId = $derived((page.params.id as string) || "");

let booking = $state<any | null>(null);
let isLoading = $state(true);

async function loadBooking() {
  if (!bookingId) return;
  isLoading = true;
  try {
    const token = await authStore.firebaseUser?.getIdToken();
    if (!token) return;

    const res = await api.bookings({ id: bookingId }).get({
      headers: { authorization: `Bearer ${token}` },
    });
    if (res.data) {
      booking = res.data;
    }
  } catch (e) {
    console.warn("Booking success fetch error:", e);
  } finally {
    isLoading = false;
  }
}

onMount(() => {
  loadBooking();
});

const isPaid = $derived(
  booking?.status === "CONFIRMED" || booking?.payment?.status === "PAID",
);
const isFailed = $derived(
  booking?.status === "CANCELLED" || booking?.payment?.status === "FAILED",
);
</script>

<svelte:head>
  <title>Booking Confirmed | PadelHive</title>
</svelte:head>

<div class="min-h-screen pt-20 pb-24 bg-[#06121A]">
  <div class="container max-w-2xl py-12">
    {#if isLoading}
      <div class="rounded-3xl border border-white/[0.06] bg-[#0C1B26] p-8 text-center space-y-4">
        <div class="mx-auto h-20 w-20 rounded-full bg-white/5 animate-pulse"></div>
        <div class="mx-auto h-4 w-32 rounded-full bg-white/5 animate-pulse"></div>
        <div class="mx-auto h-8 w-64 rounded-full bg-white/5 animate-pulse"></div>
      </div>
    {:else}
      <div class="rounded-3xl border border-white/[0.06] bg-[#0C1B26] p-6 text-center md:p-8">
        {#if isPaid}
          <div class="mx-auto flex h-20 w-20 items-center justify-center rounded-full bg-[#E6FA50]/10">
            <CheckCircle2 class="h-10 w-10 text-[#E6FA50]" />
          </div>
          <p class="mt-6 section-label text-[#E6FA50]">Booking Confirmed</p>
          <h1 class="heading-1 mt-3 text-[#F7F7F7]">
            Court secured for your match
          </h1>
          <p class="body mx-auto mt-3 max-w-md text-[#F7F7F7]/40">
            Your payment was successful and the court is confirmed.
          </p>
        {:else if isFailed}
          <div class="mx-auto flex h-20 w-20 items-center justify-center rounded-full bg-red-500/10">
            <XCircle class="h-10 w-10 text-red-500" />
          </div>
          <p class="mt-6 section-label text-red-500">Payment Failed</p>
          <h1 class="heading-1 mt-3 text-[#F7F7F7]">
            Payment could not be processed
          </h1>
          <p class="body mx-auto mt-3 max-w-md text-[#F7F7F7]/40">
            We could not confirm your payment. Please try again.
          </p>
        {:else}
          <div class="mx-auto flex h-20 w-20 items-center justify-center rounded-full bg-yellow-500/10">
            <Loader2 class="h-10 w-10 animate-spin text-yellow-500" />
          </div>
          <p class="mt-6 section-label text-yellow-500">Payment Pending</p>
          <h1 class="heading-1 mt-3 text-[#F7F7F7]">
            Waiting for confirmation
          </h1>
          <p class="body mx-auto mt-3 max-w-md text-[#F7F7F7]/40">
            We are waiting for confirmation of your payment.
          </p>
        {/if}

        {#if booking}
          <div class="mt-8 rounded-2xl border border-white/[0.06] bg-[#06121A] p-5 text-left">
            <div class="flex items-start justify-between gap-4 border-b border-white/[0.06] pb-4">
              <div>
                <p class="section-label text-[#F7F7F7]/40">Booking ID</p>
                <p class="body mt-1 text-[#F7F7F7]/80">{booking.id}</p>
              </div>
              <span
                class="caption rounded-full px-3 py-1 uppercase font-semibold {isPaid
                  ? 'bg-[#E6FA50]/10 text-[#E6FA50]'
                  : isFailed
                    ? 'bg-red-500/10 text-red-500'
                    : 'bg-yellow-500/10 text-yellow-500'}"
              >
                {booking.status}
              </span>
            </div>

            <div class="mt-5 grid gap-4 sm:grid-cols-2">
              <div class="rounded-xl bg-white/[0.03] p-4">
                <div class="section-label flex items-center gap-2 text-[#F7F7F7]/40">
                  <MapPin class="h-3.5 w-3.5" />
                  Venue
                </div>
                <p class="body mt-2 text-[#F7F7F7]/80">{booking.venue?.name}</p>
                <p class="body-sm mt-1 text-[#F7F7F7]/40">{booking.court?.name}</p>
              </div>

              <div class="rounded-xl bg-white/[0.03] p-4">
                <div class="section-label flex items-center gap-2 text-[#F7F7F7]/40">
                  <CalendarDays class="h-3.5 w-3.5" />
                  Date
                </div>
                <p class="body mt-2 text-[#F7F7F7]/80">
                  {formatBookingDate(new Date(booking.bookingDate))}
                </p>
              </div>

              <div class="rounded-xl bg-white/[0.03] p-4">
                <div class="section-label flex items-center gap-2 text-[#F7F7F7]/40">
                  <Clock class="h-3.5 w-3.5" />
                  Time
                </div>
                <p class="body mt-2 text-[#F7F7F7]/80">
                  {formatBookingTimeRange(booking.startsAt, booking.endsAt)}
                </p>
              </div>

              <div class="rounded-xl bg-white/[0.03] p-4">
                <div class="section-label flex items-center gap-2 text-[#F7F7F7]/40">
                  <CreditCard class="h-3.5 w-3.5" />
                  Payment
                </div>
                <p class="price mt-2 text-[#F7F7F7]/80">
                  Rp {((booking.finalAmount || 200000) / 1000).toFixed(0)}K
                </p>
              </div>
            </div>
          </div>
        {/if}

        <div class="mt-8 flex flex-col gap-3 sm:flex-row sm:justify-center">
          {#if isFailed}
            <a
              href="/booking/{bookingId}/payment"
              class="label btn-lime flex h-12 items-center justify-center rounded-full px-6"
            >
              Try Payment Again
            </a>
          {:else}
            <a
              href="/bookings"
              class="label btn-lime flex h-12 items-center justify-center rounded-full px-6"
            >
              View My Bookings
            </a>
          {/if}
          <a
            href="/venues"
            class="label flex h-12 items-center justify-center rounded-full border border-white/[0.08] px-6 text-[#F7F7F7]/60 transition-colors hover:border-white/[0.15] hover:text-[#F7F7F7]/80"
          >
            Book Another Court
          </a>
        </div>
      </div>
    {/if}
  </div>
</div>
